### ISSUE TITLE
Detect and rewrite import of all hbs files

### ISSUE THREAD

**Issue by tomdale** [embroider-build/embroider#10]
Currently, Embroider has a Babel plugin that rewrites all imports of template files to include the `.hbs` suffix, so `import template from '../../templates/my-component'` becomes `import template from '../../templates/my-component.hbs'`.

Unfortunately, this currently relies on detecting `/templates/` in the import path to know that the type being imported is a template. We should instead provide the Babel plugin a list of template files ahead of time, so it can append the suffix correctly, no matter what the import path.

Motivating addon: `ember-collapsible-panel`, where component files do `import template from './template'`: https://github.com/embermap/ember-collapsible-panel/blob/master/addon/components/cp-panel/component.js#L6

**Comment by lifeart** [comment]
https://github.com/embroider-build/embroider/blob/master/packages/compat/src/babel-plugin.ts#L38

**Comment by acorncom** [comment]
Looks like the plugin has been moved to 
https://github.com/embroider-build/embroider/blob/4af5ab3b929c93583a6ae6b0f319a7eaabffb785/packages/core/src/babel-plugin-adjust-imports.ts#L53
