### ISSUE TITLE
Contextual modifiers and helpers not supported?

### ISSUE THREAD

**Issue by simonihmig** [embroider-build/embroider#1018]
Ember 3.27 introduced the `(modifier)` and `(helper)` helper counterparts to `(component)`. Using `(modifier)` in an addon to yield a contextual modifier works in non-Embroider and the "safe" scenario, but fails in "optimized" mode with `Missing helper: modifier`.

It seems this new feature is not properly supported yet? I guess we need similar special treatment for these as we have for the [component helper](https://github.com/embroider-build/embroider/blob/dcd4eaaf851368e3393367c474e9eccdfbae13e9/packages/compat/src/resolver-transform.ts#L249)?

**Comment by ef4** [comment]
Yes, we need to make them work almost exactly the same as the component helper, just resolving to slightly different paths.

Along with this we also still need a staticModifiers mode. None of it is very different from staticHelpers and staticComponents.

**Comment by simonihmig** [comment]
> Yes, we need to make them work almost exactly the same as the component helper, just resolving to slightly different paths.

Thanks for confirming!

> Along with this we also still need a staticModifiers mode. None of it is very different from staticHelpers and staticComponents.

Yup, I raised this already here: https://github.com/embroider-build/embroider/issues/603 🙂

Maybe I can find some time for this, but no promises...

**Comment by rahulk94** [comment]
Looks like this has been added but missed from being added as a config option in the README.

**Comment by Windvis** [comment]
AFAIK this hasn't been implemented yet? The PR which is referenced here only added the `staticModifiers` option.

**Comment by simonihmig** [comment]
I think you are right, so I reopened this issue!

**Comment by rahulk94** [comment]
Woops my bad 🤦🏾‍♂️  sorry team

**Comment by Windvis** [comment]
@ef4 Forgive my ignorance but do we also need to add `ensureSafeHelper` and `ensureSafeModifier` utils to fully support these helpers?

**Comment by ef4** [comment]
I think "no", because I'm pretty sure the newly added helper-helper and modifier-helper never accepted dynamic values. They only accept string literals.

So it's not possible to write a component that accepts a helper as an argument "the wrong way", by accepting the string name of the helper, rather than the helper itself.

**Comment by Windvis** [comment]
As of the 1.4.0 release both these helpers should now be fully supported. :tada:
