### ISSUE TITLE
Cannot import from `@glimmer/tracking/primitives/cache`

### ISSUE THREAD

**Issue by NullVoxPopuli** [embroider-build/embroider#1020]
Using 
`@embroider/test-setup` 0.47.2
`ember-source` ~3.28.0
`ember-cli-babel` ^7.26.6

And this code:
```js
import { getValue } from '@glimmer/tracking/primitives/cache';
```

I'm getting this error:
```
Module not found: Error: Can't resolve '@glimmer/tracking/primitives/cache' in '$TMPDIR/embroider/2340f5/node_modules/ember-resources/dist/index.js'
Did you mean 'cache.js'?
BREAKING CHANGE: The request '@glimmer/tracking/primitives/cache' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

build: https://github.com/NullVoxPopuli/ember-resources/runs/4205184397?check_suite_focus=true#step:5:145

**Comment by NullVoxPopuli** [comment]
also occurs on ember-source ~4.0.0

**Comment by simonihmig** [comment]
Worth noting that this (failing) import is in a **v2 addon** (`ember-resources`)! 👆

I guess this might be related to `@glimmer/tracking` being a "virtual package"? 

I looked and debugged a bit into https://github.com/embroider-build/embroider/blob/master/packages/core/src/babel-plugin-adjust-imports.ts, especially [this part](https://github.com/embroider-build/embroider/blob/master/packages/core/src/babel-plugin-adjust-imports.ts#L288-L307). Don't know if that's relevant, unfortunately I was not able to draw any conclusions...

Note that there are even more errors for different packages (see linked CI run above):
```
Module not found: Error: Can't resolve '../../../../externals/@ember/application' in '$TMPDIR/embroider/2340f5/node_modules/ember-resources/dist'
Did you mean 'application.js'?
```

**Comment by NullVoxPopuli** [comment]
there is also this: https://github.com/embroider-build/embroider/blob/master/packages/compat/src/compat-adapters/%40glimmer/tracking.ts#L23

**Comment by ef4** [comment]
No, v2 addons don't run through the compat adapters. They exist to help convert v1 to v2.

But if you're asking if a v2 addon that consumes a v1 addon will see the v1 addon after it has gone through a compat adapter, yes, it needs to work that way.

**Comment by nightire** [comment]
@NullVoxPopuli Can't wait to use ember-resources@4 any longer 😭

**Comment by NullVoxPopuli** [comment]
I think this is resolved?

@nightire you can use latest ember-resources with embroider now <3

**Comment by nightire** [comment]
> I think this is resolved?
> 
> @nightire you can use latest ember-resources with embroider now <3

Yes, I can confirm it works now, congrats!

**Comment by angelayanpan** [comment]
what was the fix again?  I'm seeing `Can't resolve '@glimmer/tracking'`
