### ISSUE TITLE
@embroider/addon-dev should provide a command to link v2 addons w/ watched rebuilds

### ISSUE THREAD

**Issue by NullVoxPopuli** [embroider-build/embroider#1022]
I don't know the exact details of this, but I'm imagining something like:

In the app
```
yarn addon-dev watch <addon-name>
```
and it would run the rollup watch command: https://rollupjs.org/guide/en/#-w--watch
every time a file changes within addon-dev? :shrug: 

Or maybe, we can have `watchDependeiencs` run the compile-watch for us?

Currently, this has to be done
- in the addon directory
  - `rollup -c --watch`
  - `yarn link`
- in the app directory
  - add to `ember-cli-build.js`
   
    ```js
    autoImport: {
      watchDependencies: Object.keys(packageJson.dependencies),
    },
    ```
  - `yarn link <addon name>`    
  - `ember s`
  

I suppose in a monorepo, it's two less steps, :thinking: 
  then it's just 
  - `rollup -c --watch` (in addon)
  - ensure `watchDependencies`
  - ember s
   doesn't seem _too_ bad :thinking:

**Comment by ef4** [comment]
I think a blueprint can make this clearer, not sure that it needs a dedicated command. 

For example, ember-welcome-page uses npm-run-all to do `rollup -c --watch` and `cd test-app && ember s`.

**Comment by NullVoxPopuli** [comment]
right, but in a monorepo example, let's say you are working on something "complicated" with maybe.. 5 addons.
you now need 1 command + an additional command for each addon (to do the compile watching).

would it be reasonable to have "some standard" so that `watchDependencies` can see if packages change and run the compile command for that package (less resource intensive than constant compile watching?)

**Comment by ef4** [comment]
> see if packages change and run the compile command for that package

Starting a refresh process to compile every time is likely to be a lot slower than watching, because watching gives the tool (rollup, etc) control over it's own in-memory caching of all the unchanged parts of the project, and the file watcher event tells it exactly what to invalidate.

(I haven't looked at rollup's implementation in particular, but I know this makes a huge difference for webpack and I have no reason to believe other build tools wouldn't take advantage of similar rebuild optimizations.)

**Comment by NullVoxPopuli** [comment]
alright, I mean, that's good.
But what if we have `watchDependencies` "essentially" mean:
```
ember s
  for each watched dependency
     if isAddon?
       if has watch command?
         run npm/yarn watch
```

**Comment by NullVoxPopuli** [comment]
I no longer thing this should be the responsibility of addon-dev.

If a monorepo, for example, has 30 addons in a monorepo, starting _all_ those in watch mode would be catastrophic lol.

turborepo, for example, can handle monorepo's build addons before apps sort of behavior, and then if we _default_ to the `ember-cli-build.js` config that says "watch my dependencies", then you can freely start up watch mode and things will "just work" with the app's hot reload behavior
