### ISSUE TITLE
Build dies when using incorrect helper/component in template

### ISSUE THREAD

**Issue by mydea** [embroider-build/embroider#1026]
Let's say I make a typo in my hbs template in an embroider build:

```hbs
{{#let (my-helpter @arg) as |something|}}
  {{! oops, should be (my-helper) !! }}
{{/let}}
```

With embroider, my dev. server dies with an error:

```
Build Error (PackagerRunner) in components/my-component.hbs

Module Error (from ../../../home/my-app/node_modules/thread-loader/dist/cjs.js):
Missing helper: my-helpter in components/my-component.hbs

# ... much more details
error Command failed with exit code 1.
```

It is correct to fail, but after that I have to run `ember s` again, booting up everything etc. 
It would be much nicer if it would "just" recover from this error when I fix the typo and save my file.

**Comment by void-mAlex** [comment]
hello @mydea would like to confirm this is still an issue or if it can be closed

**Comment by mydea** [comment]
Not sure TBH, but I guess we can close this as it's been some time and a new issue can always be opened if it still pops up 😅
