### ISSUE TITLE
Wrong version check in dependencySatisfies 

### ISSUE THREAD

**Issue by simonihmig** [embroider-build/embroider#1051]
It seems `dependencySatisfies` needs a similar fix as as https://github.com/babel/ember-cli-babel/pull/396 and https://github.com/ember-cli/ember-cli-htmlbars/pull/741.

In a monorepo with one app running on 3.26 and others on 3.28, [this check](https://github.com/embroider-build/embroider/blob/master/packages/util/addon/ember-private-api.js#L10-L12) in `@embroider/util` returns true, as both `@embroider/util` and `ember-source` are in the hoisted main `node_modules`, while the app in question has its own version of Ember in its *local* `node_modules`.

**Comment by ef4** [comment]
I think this was probably fixed by https://github.com/embroider-build/embroider/pull/1053

`@embroider/util` needed peerDep on ember-source in order to guarantee that it will resolve the app's copy.

**Comment by ef4** [comment]
This is a general thing -- dependencySatisfies makes the most sense with peerDeps (which can also be optional peerDeps). Because your own dependencies are generally known, and non-dependencies can't be reliably resolved.
