### ISSUE TITLE
dependencySatisfies + macroCondition ignores ember-source >= 4.0.0Z

### ISSUE THREAD

**Issue by NullVoxPopuli** [embroider-build/embroider#1057]
I found an incorrect modifier manager right now:
![image](https://user-images.githubusercontent.com/199018/146491413-58e5398a-aaf8-4c8d-b6e0-02c51fbff04a.png)

and without sourcemaps:
![image](https://user-images.githubusercontent.com/199018/146491590-28f365c6-b5e5-4760-9c20-dcaec4695eac.png)

I'm using ember-source-4.2-alpha.4

**Comment by NullVoxPopuli** [comment]
I wonder if this is related to: https://github.com/embroider-build/embroider/issues/1038

which, I took a stab at fixing here: https://github.com/embroider-build/embroider/pull/1053

but I don't know what's supposed to happen.

**Comment by ef4** [comment]
I think this was fixed in #1053.

**Comment by NullVoxPopuli** [comment]
I don't think this is resolved:
![image](https://user-images.githubusercontent.com/199018/148605410-6014699e-649f-48be-a577-c32a498a7a36.png)

(unless #1053 isn't released?)

**Comment by NullVoxPopuli** [comment]
```js
if ((0,_home_nullvoxpopuli_Development_NullVoxPopuli_limber_node_modules_embroider_macros_src_addon_runtime__WEBPACK_IMPORTED_MODULE_0__.macroCondition)(false)) {
  // new enough ember has a real module we can import
  runtime = __webpack_require__(/*! ../../../../externals/@glimmer/runtime */ "../../externals/@glimmer/runtime.js");
} else {
  // older ember has its own internal loader
  runtime = window.Ember.__loader.require('@glimmer/runtime');
}
```
