### ISSUE TITLE
Uncaught SyntaxError: Cannot use import statement outside a module with ember-novnc-shim/novnc

### ISSUE THREAD

**Issue by vihai** [embroider-build/embroider#1073]
Hello,

I was trying to use Embroider in my app and I encountered this issue. The loading of vendor.js fails in brower with a:

```
Uncaught SyntaxError: Cannot use import statement outside a module
```

The module causing the issue is `novnc` imported via `ember-novnc-shim` in file `@novnc/novnc/lib/base64.js`:

```
import * as Log from './util/logging.js';
```

May `ember-novnc-shim` be incompatible with Embroider?

**Comment by Windvis** [comment]
I would try uninstalling `ember-novnc-shim`, install `@novnc/novnc` as a dependency of your app and import the package directly. With ember-auto-import I don't think you need the shim anymore. 

The shim addon also seems very outdated so it's very likely that it's simply not compatible with Embroider.

**Comment by vihai** [comment]
Uh... wow... I removed `ember-novnc-shim` and installed `@novnc/novnc` directly... and the import wasn't working with a:

```
Uncaught (in promise) Error: Could not find module `@novnc/novnc/core/rfb` imported from `(require)`
```

Then, by chance, I added a _comment_ after the import line and it started working.
Then I did more tests and it seems that when there is exactly one white line between the import of RFB and the export it does not work (!!!).

For example, this code does not work:

```
import Component from '@glimmer/component';
import { action } from '@ember/object';
import RFB from '@novnc/novnc/core/rfb';

export default class LcdDisplayComponent extends Component {
```

This does work:
```
import Component from '@glimmer/component';
import { action } from '@ember/object';
import RFB from '@novnc/novnc/core/rfb'; //whatever

export default class LcdDisplayComponent extends Component {
```

And also this works:
```
import Component from '@glimmer/component';
import RFB from '@novnc/novnc/core/rfb';
import { action } from '@ember/object';

export default class LcdDisplayComponent extends Component {
```

Any idea of what it could possibly be?

**Comment by ef4** [comment]
Maybe a caching problem is confusing matters? That could be why the comment would change the results. Try `rm -rf $TMPDIR/embroider` to see if that changes the behavior.

**Comment by ef4** [comment]
Oof. Yeah, caches are tricky. We're using some of webpack's caching features because it definitely makes builds faster, but there are some rough edges like this.

If you have a chance to figure out repeatable steps that cause the caching problem, please file an issue about it.

**Comment by vihai** [comment]
It will be hard but I will keep an eye out, thank you!

**Comment by Windvis** [comment]
Closing since the original issue has been resolved.
