### ISSUE TITLE
Default to watching dependencing in development?

### ISSUE THREAD

**Issue by NullVoxPopuli** [embroider-build/embroider#1090]
Assume a monorepo setup, where many addons are linked by default:
 - a person launches an app via `ember s`
 - but then decides they want to edit an addon (and rebuild it // `rollup -c --watch`)
 - when the v2 addon re-outputs its artifacts, the host app should detect that
 
 Reasoning:
  - until we get to a dev-time environment as efficient as Vite, the initial startup time for apps can be costly (though, I've yet to experience what a large app is like with all v2 addons --- I'll know more on this in the coming months though)

**Comment by NullVoxPopuli** [comment]
Proposal (potential blueprint change?):

adding (whatever the embroider equiv of autoImport.watchDependencies is): to ember-cli-build.js:
```js
const EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function (defaults) {
  let app = new EmberApp(defaults, {
    name: 'ember-app',
    autoImport: {
      watchDependencies: [Object.keys(require('./package').dependencies)],
    // ...
```

Does this make sense to be in this file?
Should it be an implicit default? (or would that cause to many "watchers" to be consumed?)

**Comment by NullVoxPopuli** [comment]
Related: https://github.com/embroider-build/embroider/issues/1089

**Comment by lifeart** [comment]
Ya, I don't like idea where ember-cli is watching for every item in node_modules.

Some possible optimizations:
 - create watched tree only for specified deps
 - autodetect watched deps (if it's symlink or package.json has "file:" reference to it)

**Comment by NullVoxPopuli** [comment]
with 
```
      watchDependencies: [Object.keys(require('./package').dependencies)],
```
only direct dependencies are watched, so that eliminates still 99% of node_modules.
if it's possible to only use one watcher on the entirety of a package's output folder, that would still be a pretty good DX improvement for monorepos, where package resolution of addons is neither file, nor symlink

**Comment by lifeart** [comment]
deps could have nested node_modules, and may be not a case (one dev-dep could lead us to bunch of side watched folders inside node_modules/{dep}/node_modules/{...}

**Comment by NullVoxPopuli** [comment]
> deps could have nested node_modules, and may be not a case

I'm proposing to ignore those.
To _only_ watch what is specified in an app's `package.json#dependencies 
 - _only_ if :
   - they are within the same repo
   - or if they are linked (like your suggestion says 🥳 )

> one dev-dep could lead us to bunch of side watched folders inside node_modules/{dep}/node_modules/{...}

If we only watch _the shallow dependencies-of-the-app_'s output folder (dist in most cases), then none of nested 'node_modules' would matter

**Comment by lifeart** [comment]
also, `ember-cli` unable to hot-reload middlewares and do not recreate trees, it's leads us to case where it make sence to watch for dep only if `dep/{app,addon}` scope is changed

**Comment by NullVoxPopuli** [comment]
Gonna close this, as determining which addons should be in watch more I think is best determined by a project/team than by us, the embroider people.
