### ISSUE TITLE
Cannot find peerDependency (miragejs) with importSync 

### ISSUE THREAD

**Issue by jrjohnson** [embroider-build/embroider#1091]
Getting the error `Could not find module miragejs imported from (require)` with miragejs in the `devDependencies` as well as `peerDependencies`. I created a reproduction and you can see the error at https://github.com/jrjohnson/test-miragejs-import/runs/4962685303?check_suite_focus=true#step:6:19 this is a new addon with miragejs installed and then used like:

```
if (macroCondition(dependencySatisfies('miragejs', '*'))) {
  const { Response } = importSync('miragejs');
  console.log(Response);
}
```

Not sure if I'm using this wrong or there is an issue with this specific import.

**Comment by Windvis** [comment]
You need to install `ember-auto-import` as a dependency when you import npm packages in addon code. After doing that (and returning `Response` from the util,) the test doesn't seem to fail anymore.

**Comment by jrjohnson** [comment]
Thank you so much @Windvis! Really really appreciate the help here. It seems maybe intuitive, but I would never have tried that assuming that `importSync` would bring it's own stuff and not rely on EAI. You've gotten me through a very frustrating situation and I can't thank you enough. I'm going to touch up the docs if I have a moment, but go ahead and close this issue.
