### ISSUE TITLE
[addon-dev] Allow TS files in publicEntrypoints / appReexports

### ISSUE THREAD

**Issue by josemarluedke** [embroider-build/embroider#1094]
For addons authoring their code in TS (or soon gjs/gts), currently is not possible to use `@embroider/addon-dev`'s `publicEntrypoints` or `appReexports` methods. 

We cannot use them because the dist files will end up with the same extension as the input.

In glimmer-apollo, I ended up doing a simple replace of `.ts` with `.js`. 

https://github.com/josemarluedke/glimmer-apollo/blob/main/packages/glimmer-apollo/rollup.config.js#L7-L23

**Comment by NullVoxPopuli** [comment]
It turns out this isn't needed - stay tuned!

**Comment by NullVoxPopuli** [comment]
I think the solution in #1099 is solid~ish, but I need to figure out a peerDep issue -- https://github.com/embroider-build/embroider/issues/1062
I _think_ I'm getting two copies of `xstate` in the consuming app, and it's only revealing itself because of component-manager's reliance on object identity. :thinking:

**Comment by rwjblue** [comment]
@josemarluedke - Can you put up a separate (smaller) PR from #1099 that ensures that the output path is `.js` similar to what you did [here](https://github.com/josemarluedke/glimmer-apollo/blob/6671a2191f2032cfe6e0cad018d9f66fbb10af75/packages/glimmer-apollo/rollup.config.js#L8-L23) (though with more robust extension replacement support probably)?

**Comment by josemarluedke** [comment]
@rwjblue Can definitely do it. Should extension replacement support the following mapping? 

- `ts` -> `js`
- `gts` -> `js`
- `gjs` -> `js`
- `hbs` -> `js`

**Comment by rwjblue** [comment]
yep! but I think we already have `hbs` -> `js` done right?

**Comment by josemarluedke** [comment]
@rwjblue PR here: https://github.com/embroider-build/embroider/pull/1106
