### ISSUE TITLE
Non dynamic component in template considered unsafe unless called with <this.component />

### ISSUE THREAD

**Issue by x8BitRain** [embroider-build/embroider#1118]
I'm trying to get an ember 3.26 app to work with embroider with 

```js 
staticAddonTestSupportTrees: true,
staticAddonTrees: true,
staticHelpers: true,
staticComponents: true,
```

When building the app I get errors for all template files that contain call normal non-dynamic components like this:

```bash
ERROR in ./templates/login.hbs
Module Error (from ../../../../../../../../Users/user/ember-web/node_modules/thread-loader/dist/cjs.js):
Unsafe dynamic component: cannot statically analyze this expression in templates/login.hbs
 @ ./assets/ember-web.js 1481:13-44
```

The template in question looks like this:
```hbs
{{page-title "Login"}}

{{#if this.showBranding}}
  <div class="login split">
    <div class="split__page">
      <LoginForm class="bright-form bright" />
    </div>
  </div>
{{else}}
  <div class="login centered">
    <div class="centered__page">
      <LoginForm class="bright-form bright" />
    </div>
  </div>
{{/if}}
```

But the above Unsafe dynamic component error does not happen if I call the component with `this.` in front of the component name.

```hbs
{{page-title "Login"}}

{{#if this.showBranding}}
  <div class="login split">
    <div class="split__page">
      <this.LoginForm class="bright-form bright" />
    </div>
  </div>
{{else}}
  <div class="login centered">
    <div class="centered__page">
      <this.LoginForm class="bright-form bright" />
    </div>
  </div>
{{/if}}
```
Invocation with <this.component/> doesn't render anything.
Is this a bug or am I doing something wrong?  Thanks))

**Comment by x8BitRain** [comment]
I was using ember-ast-hot-reload at the same time, removing the package fixed the issue, thanks))

**Comment by NullVoxPopuli** [comment]
Great thing about embroider's direction, is that we'll _eventually_ be able to use package-specific hot loading, which will be way more supported and feature-rich :D

**Comment by ef4** [comment]
Yeah it's already possible to use webpack-dev-server which provides hot reloading by the default. But it requires a bunch of mucking around. Work is underway to package that up and document it.

**Comment by lifeart** [comment]
Linking issues here: https://github.com/lifeart/ember-ast-hot-load/issues/692
