### ISSUE TITLE
V2 addons: initializers are duplicated or ran in the wrong context? 

### ISSUE THREAD

**Issue by NullVoxPopuli** [embroider-build/embroider#1127]
Reproduction: https://github.com/NullVoxPopuli/ember-addon-v2-duplicate-modules

I first noticed this when I was messing with: https://github.com/NullVoxPopuli/ember-statechart-component/pull/244 (which relies on an initializer to utilize `setComponentManager`) -- it presented itself via ember saying that it didn't know of a component manager to handle `StateNode` (from xstate) -- which now makes sense, because the initializer code is in a chunk that runs _after_ initializers are needed.

Odd things that can be noticed:
 - the module can be imported twice (a log is at module-level in the initializer, and logs when the app/test boots, and again during import)
 - the initializer only runs once (when called manually in the test) -- I'd expect the initializer to run during app/test boot?

**Comment by ef4** [comment]
The reason your initializer isn't running normally is that your test isn't using one of the setup functions from ember-qunit. You need at least `import { setupTest } from 'ember-qunit'`. 

The reason your module is getting duplicated is that your **app** imports the initializer from the path 

```js
my-addon/instance-initializers/test-initializer.js
```

but your **test suite** imports the initializer from the path

```js
my-addon/instance-initializers/test-initializer
```

And this seems to be enough to confuse ember-auto-import, so I filed https://github.com/ef4/ember-auto-import/issues/503
