### ISSUE TITLE
Updating @embroider/util cause build error

### ISSUE THREAD

**Issue by usamahamed** [embroider-build/embroider#1136]
I am currently trying to update `@embroider/util` to version `1.2.0` but for me, it cause a build error, it wroking before with version `0.47.2`

My  node version: `16.14.0`
My  npm version: `18.3.1`

<img width="1114" alt="image" src="https://user-images.githubusercontent.com/23267284/154944918-15220cec-8444-48ad-95cc-b37b260b1388.png">

**Comment by Windvis** [comment]
You are running into https://github.com/embroider-build/embroider/issues/1077. Something in your dependency tree is pulling in an older version. If you run `npm ls @embroider/macros` you should see a list of all versions in your node_modules folder. The addons that bring in older version might have updated it in a new release so bumping the version of those might help. You can send PRs to the others that haven't had the version bump yet.

To make the builds work again you can work around the issue by using npm overrides and forcing all versions to be v1+.

**Comment by Windvis** [comment]
Closing since it's a duplicate.
