### ISSUE TITLE
Support importSync with static config value

### ISSUE THREAD

**Issue by anehx** [embroider-build/embroider#1138]
It would be nice if `importSync` would allow for values that can be statically analyzed, e.g a value in the static configuration:

```js
importSync(getOwnConfig().someConfiguredPath);
```
IMO this should be statically analyzable, right?

Are there any plans for something like this?

**Comment by bertdeblock** [comment]
It _seems_ this is already supported https://github.com/embroider-build/embroider/blob/main/packages/macros/tests/babel/import-sync.test.ts#L49-L55 ?

**Comment by ef4** [comment]
Yes, as far as I know this scenario works.
