### ISSUE TITLE
Error: Cannot find module './ember-gestures.css' & './app/styles/mapbox-gl.css'

### ISSUE THREAD

**Issue by AndreJoaquim** [embroider-build/embroider#115]
- embroider: 0.3.0
- ember-cli: 3.8.1

After running `ember serve`, it gives an error about not finding a `.css` module:

```bash
Cannot find module './ember-gestures.css' from '/private/var/folders/px/k5qdw6s161n4t35jzbjsy2300000gp/T/embroider/5bf392/node_modules/ember-gestures'
```

I've removed that add-on -- `ember-gestures` -- to see what other errors I would have, and I've got the following:

```bash
Cannot find module './app/styles/mapbox-gl.css' from '/private/var/folders/px/k5qdw6s161n4t35jzbjsy2300000gp/T/embroider/5bf392/node_modules/@embroider/synthesized-vendor'
```

I don't know it both errors relate to the same problem or not, but it's my standing point :) I can share the error report, if needed. Thanks for the awesome work!

**Comment by AndreJoaquim** [comment]
`ember-mapbox-gl` uses the [`treeForStyles`](https://github.com/kturney/ember-mapbox-gl/blob/master/index.js#L46) hook to add the mentioned `.css`

**Comment by ef4** [comment]
Thanks for reporting these.

The ember-gestures problem was recently fixed in https://github.com/embroider-build/embroider/pull/111.

Is mapbox-gl.css being added by an addon? Which one? Or is it being added directly via something like `app.import()`?

**Comment by raido** [comment]
I got a similar issue but instead it reports error for own addon that I try to "ember serve" with Embroider.

`Cannot find module './@<scoped-package>/<module-name>.css' from '/private/var/folders/jp/2wh258pj23xg7sqgdf8g7gnc0000gn/T/embroider/2a62ff'`

**Comment by ef4** [comment]
@raido please try embroider 0.3.1, I think your case is probably also already fixed.

**Comment by raido** [comment]
Indeed but now I get another error:

```
Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.
```

After I add `@babel/core@~7.0.0` to my package.json I get yet another error:

```
Cannot find module '@babel/plugin-transform-block-scoping'
```

I am using:

```
* ember-decorators
* @ember-decoratos/babel-transforms
* ember-cli-typescript
```

Possibly one of those does not play well.

**Comment by ef4** [comment]
Please try 0.3.3 and open a new issue if this can still be reproduced. I think everything in the original thread here is fixed.

**Comment by AndreJoaquim** [comment]
Thanks @ef4! Sorry for not answering sooner, but I was in my holidays and I turned off all of my notifications. I'll try the newer version :)
