### ISSUE TITLE
v2 addon files not resolvable when brought into app through v1 addon

### ISSUE THREAD

**Issue by simonihmig** [embroider-build/embroider#1175]
The scenario where this comes up seems to be:
```mermaid
graph TD
    A[app] -->|has devDependency| B(v1 addon)
    B --> |has dependency| C(v2 addon)
```

This was uncovered for `ember-focus-trap` (a v2 addon), see https://github.com/josemarluedke/ember-focus-trap/issues/59.

In my particular case I have `ember-boostrap` (v1) depend on it. Another addon (`ember-bootstrap-changeset-validation`) depends on that, but its dummy app fails when running in Embroider *safe* mode: `Module not found: Error: Can't resolve 'ember-focus-trap/modifiers/focus-trap.js'`. See https://github.com/kaliber5/ember-bootstrap-changeset-validations/runs/5792294552?check_suite_focus=true. However strangely enough, it works in *optimized* mode! (see CI scenario).

Adding `ember-focus-trap` as a devDepencency to `ember-bootstrap-changeset-validation` fixes the issue. But that's obviously not expected.

**Comment by NullVoxPopuli** [comment]
Is moving the dep to dependencies an option?

**Comment by rogeraraujo90** [comment]
Yeah, I've faced the same issue here in my project and the workaround was add the dep to the project dependencies.

**Comment by BryanCrotaz** [comment]
I'm seeing this even when not adding other addons that also reference `ember-focus-trap`
https://github.com/ember-bootstrap/ember-bootstrap/issues/1831
Reproduction steps in a comment

**Comment by amiarSlimane** [comment]
Still getting the same error 
```
Build Error (PackagerRunner) in modifiers/focus-trap.js

Module not found: Error: Can't resolve '/home/user/project/node_modules/ember-focus-trap/modifiers/focus-trap.js' in '$TMPDIR/embroider/6a5753/modifiers/focus-trap.js'
```

```
ember-cli: 4.9.2
node: 18.8.0
os: linux x64
```

focus-trap only used in ember-bootstrap 
```
"ember-source": "~4.9.1",
"ember-bootstrap": "^5.1.1",

"@embroider/compat": "^2.0.2",
"@embroider/core": "^2.0.2",
"@embroider/webpack": "^2.0.2",
    
```

i have added `focus-trap` as dependency to the project and i am getting the same error.
