### ISSUE TITLE
Typescript Support for v2 Addons

### ISSUE THREAD

**Issue by runspired** [embroider-build/embroider#1182]
While not directly the responsibility of embroider, given the focus on bringing typescript to the ember eco-system I think we need to polish up this story. @josemarluedke and @NullVoxPopuli have explored this space a bit, finding many issues with component colocation / template-only components in the process.

I suspect we could make this story quite nice by doing something along the lines of "add X deps to devDependencies" for typescript, enhancing the babel.config.js/json file for typescript support, and then something along the lines of `addon.typescript({ tsConfig: "../path/to/tsconfig.json" })` to make sure the addon is properly setup.

**Comment by NullVoxPopuli** [comment]
anything wrong with the rollup-plugin-ts approach?

component co-location is separate from babel and is what the `addon.hbs()` plugin provides / helps with.

**Comment by NullVoxPopuli** [comment]
Support for this has landed in `@embroider/addon-dev@2.0.0`, an example can be seen here: https://github.com/NullVoxPopuli/ember-popperjs/pull/204/commits/d4a615581b902af60f734480b10ba40b4bec46a6

Documentation / setup of a `--typescript` flag will be handled over on this repo: https://github.com/embroider-build/addon-blueprint
