### ISSUE TITLE
Feat: v2 equivalent of isDevelopingAddon => true for mono-repo dependencies

### ISSUE THREAD

**Issue by runspired** [embroider-build/embroider#1184]
In a mono-repo with multiple apps/addons/engines, it would be great if when building and serving an app we did not need to run the individual serve commands for each v2 addon. This *might* be the intent of `EMBROIDER_REBUILD_ADDON`, but manually listing every addon/engine within the start command of each app would be very tedious.

For how @bendemboski got around this in the past (no longer functional) take a look at https://dev.to/bendemboski/embroider-from-zero-to-route-splitting-in-3-5-weeks-5abo#rebuild-on-addon-changes

It would be great to come up with automatic detection for mono-repo dependencies, and in the absence of that detection have a simpler way of declaring a v2 addon/engine should always rebuild. Tbh I'm somewhat partial towards bringing back the hook as part of the addon-main.

**Comment by NullVoxPopuli** [comment]
The approach I like from ember-auto-import, and what I'm using in my work monorepo (which isn't on embroider yet) is:
```js
// ember-cli-build.js
autoImport: {
  watchDependencies: Object.keys(packageJson.dependencies),
}
```
I'd prefer more this behavior as devDependencies should not be watched (unless specifically build tooling, but I think that's a separate scope).

Related discussion: https://github.com/embroider-build/embroider/issues/1090

**Comment by NullVoxPopuli** [comment]
the v2 addon blueprint solved the 2 terminal/process problem this way:

```
      start: "concurrently 'npm:start:*' --restart-after 5000 --prefix-colors cyan,white,yellow",
      'start:addon': `npm start --workspace ${addonName} -- --no-watch.clearScreen`,
      'start:test-app': `npm start --workspace ${testAppName}`,
```

the app should already watch changes to the addon. 
if there is still an issue present, could we open a new issue with a reproduction? Thanks!!
