### ISSUE TITLE
The Readme for @embroider/macros isn't getting deployed to npm properly

### ISSUE THREAD

**Issue by mansona** [embroider-build/embroider#1185]
Hey folks 👋  

I can't count how many times I've googled `@embroider/macros` and landed on a blank page on npm at this point https://www.npmjs.com/package/@embroider/macros 🙈  I don't know what's going wrong with the deployment but I suspect it's something to do with the monorepo? Is it possible to make sure that the Readme makes its way to npm?

**Comment by NullVoxPopuli** [comment]
I think it's because your search result is taking you to the explore tab instead of the README. The README has always been there afaict

**Comment by Windvis** [comment]
@mansona could you clarify what exactly isn't working? The link you posted does show the readme contents and I've never seen it not work :smile:, but maybe I misunderstood.

**Comment by angelayanpan** [comment]
hi @mansona, can this be closed? not reproducible from my side either
