### ISSUE TITLE
Template-only component resolution fails if only referenced in JS

### ISSUE THREAD

**Issue by mydea** [embroider-build/embroider#1197]
I have a component, that is _only_ used like this in my app code:

```js
// helper
import Component1 from 'my-app/components/component-1';
import Component2 from 'my-app/components/component-2';

export default function getComponent(type) {
  let map: = {
    c1: Component1,
    c2: Component2
  };

  return map[type];
}
```

```js
// usage
{{#let (get-component 'c1') as |Comp|}}
  <Comp />
{{/let}}
```

This works just fine when using a JS+HBS component, but when I try to make e.g. Component1 a template-only class, it fails when building this in an Embroider app, when I try to use the component directly in a test:

```js
await render(hbs`<Component1 />`);
```

I get

```
Build Error (PackagerRunner) in tests/integration/components/component1-test.ts

Module not found: Error: Can't resolve '../../../../../../components/component-1.ts' in '$TMPDIR/embroider/d7920e/tests/integration/components/component1-test.ts'
```

I guess this is _somewhat_ of an edge case, but should still work I guess? It works as soon as I add an empty backing class, or when I remove the test.

**Comment by NullVoxPopuli** [comment]
any chance you have a reproduction? I use this pattern quite a bit

**Comment by mydea** [comment]
Hmm, I will try to make a reproduction! I tried something similar with a blank app and it seemed to work, so maybe it is something else at play, or some dependency somewhere, a bit hard to say :cold_sweat:

**Comment by angelayanpan** [comment]
hi, following up. Do you have a repro?  haven't run into this issue in my own work yet.

**Comment by ef4** [comment]
We can reopen if we get a reproduction.
