### ISSUE TITLE
V2 addon.hbs() doesn't compile hbs files into the associated JS/TS file

### ISSUE THREAD

**Issue by runspired** [embroider-build/embroider#1198]
given

```
src/components/a-comp.js
src/components/a-comp.hbs
```

And the default plugin configuration for rollup, the built output will include no hbs files and the associated js file will also not include the compiled template.

**Comment by runspired** [comment]
The solution here (which should be added to the default config)

1. import the colocation babel plugin

```ts
import colocate from "@embroider/addon-dev/template-colocation-plugin";
```

2. update the babel config to include the plugin

```ts
    babel({
      plugins: [colocate],
    }),
 ```

**Comment by NullVoxPopuli** [comment]
I haven't experienced what you're experiencing. js + hbs files are already compiled together with the default rollup sample

**Comment by runspired** [comment]
@NullVoxPopuli `addon.hbs()` is also necessary, however it is not currently sufficient.

**Comment by NullVoxPopuli** [comment]
can you provide a reproduction?


works here: https://github.com/NullVoxPopuli/ember-addon-v2-colocated-component


![image](https://user-images.githubusercontent.com/199018/165604763-f2a754af-1369-42c4-8070-89c215f063e0.png)

**Comment by runspired** [comment]
ahhhh I did not, needed to be added there. I should have thought to have added it there anyway. Must have gotten removed when I added the ts plugin 🤔

**Comment by pjcarly** [comment]
Shouldn't this best be mentioned in the below migration guide?
[Porting addons to V2](https://github.com/embroider-build/embroider/blob/main/PORTING-ADDONS-TO-V2.md)
