### ISSUE TITLE
live reload broken (duplicate scripts like vendor.js appear)

### ISSUE THREAD

**Issue by jacobq** [embroider-build/embroider#1211]
Reproduction: https://github.com/jacobq/embroider-live-reload-bug-repro

Enabling embroider in minimal (ember-cli v4.2.0) app breaks live reload feature. When `ember s` first gets run things are OK. However, changing a file (triggering update/reload) causes something weird to happen such that multiple `vendor.js` scripts appear (one gets added after each change/reload).

Compare link for v1.6.0 vs v1.7.1 (known good / bad):
https://github.com/embroider-build/embroider/compare/v1.6.0...v1.7.1

**Comment by bertdeblock** [comment]
Seeing this issue as well. Downgrading to v1.6.0 seems to resolve it for now.

**Comment by bwbuchanan** [comment]
Also seeing this issue. I narrowed it down to @embroider/webpack. Pinning that package to 1.6.0 resolves the problem.

**Comment by ef4** [comment]
Most likely culprit is https://github.com/embroider-build/embroider/pull/1177.

**Comment by krisselden** [comment]
I'm taking a look at this, thank you for the reproduction.

**Comment by muziejus** [comment]
This error caught me yesterday, but I wanted to report a side effect. I don't know a lot about how yarn's internals work, but I had two apps, one with the embroider addons at `^1.7.1` and one at `^1.5.0`. As soon as the problem expressed itself in the former, it started expressing itself in the latter, too, and no amount of deleting `node_modules`, etc., fixed it. I finally pinned both apps at `1.6.0` (no caret), and now seem to be doing ok.

**Comment by ef4** [comment]
@jacobq #1208 should only effect embroider's own test suite. The yarn.lock here doesn't have any impact on apps that use embroider.

**Comment by jacobq** [comment]
Commenting out these 3 lines makes the problem go away:

https://github.com/embroider-build/embroider/blob/7099a11224b09cc98a6868a35a367382db69f994/packages/webpack/src/ember-webpack.ts#L280-L283

Maybe somehow we're re-adding the changed files each time?

**Comment by jacobq** [comment]
In case it's helpful for anyone, here's a little script to link/unlink each embroider package (not sure if there's an easier way to do this):

<details><summary>yarn-link-or-unlink.cjs</summary>

```js
// yarn-link-or-unlink.cjs
// (assumes 
const { execSync } = require('child_process');
const { readdirSync } = require('fs');
const { argv } = require('process');
const path = require('path');
// change this if you put this script somewhere besides the root of the embroider repo
const embroiderPackagesDir = path.join(__dirname, 'packages'); 

function log(...args) { console.log(...args); }

const action = argv[2] === 'unlink' ? 'unlink' : 'link';
log(`action = ${action}`);

const packages = readdirSync(embroiderPackagesDir);
log('packages -->', packages);

for (const packageName of packages) {
  const packagePath = path.join(embroiderPackagesDir, packageName);
  log(`${action}ing ${packageName} (in ${packagePath})`);
  execSync(`yarn ${action}`, { cwd: packagePath, encoding: 'utf-8' });
}
```

</details>
