### ISSUE TITLE
Add rollup plugin that verifies and fixes the package.json (or other files)

### ISSUE THREAD

**Issue by NullVoxPopuli** [embroider-build/embroider#1212]
_¿porque?_

A number of issues that are _really hard_ to debug come from misconfigured package.jsons
 - https://github.com/embroider-build/embroider/issues/1116
 - potentially, https://github.com/embroider-build/embroider/issues/1132

This _could_ be done via lints, which we can discuss, I suppose.
I was kinda thinking that since we have a rollup plugin that already alters the package.json, maybe we add another one that does stuff like:
 - ensures data/structures exist:
   - `type` is unspecified
   - keywords has "ember-addon"
     - `ember-addon` has:
     - version: 2
     - type: addon
   - files has at least 
      - output folder
    - if `exports` is specified,
      - all paths exist (imports, types, etc)
   - repository is correct (url, path, etc)

**Comment by ef4** [comment]
Yes, it would be good to implement this via eslint. Along with any v2-addon-specific rules, we probably want to add some of the standard eslint-plugin-ember rules to the blueprint too.
