### ISSUE TITLE
for v2 addons, can we remove the addon-shim?

### ISSUE THREAD

**Issue by NullVoxPopuli** [embroider-build/embroider#1264]
I don't remember what the purpose of the addon-shim is in v2 addons.

Do we need it? 
Since v2 addons are 'just npm packages', can we remove the shim, and 'just rely on auto import' to handle the v2 package, like it would anything off npm?

**Comment by ef4** [comment]
It's the only thing that makes them fully work in classic ember-cli apps. There are several things that still aren't "just NPM", like the app-js reexports that remain necessary for most addons until all their users are entirely on gjs.
