### ISSUE TITLE
Cannot find module './app/styles/cropper.css'

### ISSUE THREAD

**Issue by bobisjan** [embroider-build/embroider#128]
- `embroider 0.3.3`
- `ember-cli 3.9.0`

```
Cannot find module './app/styles/cropper.css' from '/private/var/folders/m3/2d92q9yx06j2q51zh2_w8js80000gn/T/embroider/585bc0/node_modules/@embroider/synthesized-vendor'
```

This [add-on](https://github.com/danielthall/ember-cropperjs) uses `ember-cli-sass` and only file with styles I've found is at https://github.com/danielthall/ember-cropperjs/blob/master/addon/styles/addon.scss.

[UPDATE]
It copies `croperrjs/cropper.css` to `app/styles/cropper.css` https://github.com/danielthall/ember-cropperjs/blob/15d002acf9d3799796322b9afc7869773af1acc8/index.js#L31

**Comment by bobisjan** [comment]
@ef4, this is still an issue with the latest release of Embroider, I’m not sure on which side should it be fixed (supported)?

**Comment by alexlafroscia** [comment]
I think that the addon should probably just put their stylesheet inside `app/styles/cropper.css` to begin with rather than using Broccoli to move it around at build-time. I have other addons that just put styles in their `app` tree and they can be imported just fine.

**Comment by inscroggnito** [comment]
Hi @bobisjan - I'm building out an application and have run into this exact issue. Were you able to work out a fix for these issues concerning the use of `treeForStyles()`?

**Comment by bobisjan** [comment]
@inscroggnito 👋, I've re-tested `ember-cropperjs` add-on, and with `0.9.0` this seems to fixed by https://github.com/danielthall/ember-cropperjs/commit/3e0e47b0079218ba40b653a51861170abfcd8850.

I think this could be closed then.

**Comment by ef4** [comment]
Glad you have a fix. It would still be good to investigate why the previous pattern didn’t work.
