### ISSUE TITLE
Editing CSS files causes whole page to reload

### ISSUE THREAD

**Issue by 12finger** [embroider-build/embroider#1315]
preface: possible duplicate/re-opening of https://github.com/ef4/ember-auto-import/issues/469
but as it still happens with an up-to-date version of ember-auto-import, my guess would be it has to do with embroider?

please find a minimal reproduction repo here: https://github.com/12finger/embroider-demo-full-page-reload
- the main branch with a pure initial ember 3.25 commit = working CSS live reload
- the `add-embroider` branch. with embroider 1.9, (and several up-to-date libs) = broken CSS live reload

the issue is the _**_exact same_**_ as in the aforementioned issue https://github.com/ef4/ember-auto-import/issues/469#issuecomment-970711910. WS websocktes  .. 

> messages are sent to reload both index files as well as the CSS.
 
my issue is regarding an older ember version, i know! it should be supported by embroider 1.9 just fine, right?
we have a huge app and are in the process of octanifying it, slowly over time. so an instant update to >= 3.28 is currently no option for us. so we came to embroider as it really speeds up `ember serve` locally, which brings huge gains in  dev mode 👏 .
but the missing live reload feature is hurting hard, as we have deeply nested views which are not 100% driven by the URL, so when editing CSS the _full_ page reloads and we loose the context and have to click through the UI to get back to our views we were working on ...
I also tried embroider 1.6, 1.7, 1.8.3 to no avail.

Maybe there is a teeny-tiny  code change we could (manually?) backport from the 2.x versions to 1.9.x, so we get the benefits of a working live reloading?

**Comment by ef4** [comment]
I tested this fix on 1.9 in your reproduction and it worked. 

The only reason I was retargeting the branch here was to get CI to run. I do want to release a 1.9.1 with this.

**Comment by 12finger** [comment]
Thanks for clarifying about your process!

 I must have made a mistake earlier when i tried to apply your patch to our app. 
 I tried again, differently, and can confirm it works like a charm. ☀️🌞
 
 Looking forward to a backported release,
 Thank you for getting this sorted!
