### ISSUE TITLE
Failing to statically import addon modifiers

### ISSUE THREAD

**Issue by ztjohns** [embroider-build/embroider#1316]
Hello, I am looking to turn on some of the static functionality and seeing the following errors when I turn *staticModifiers* on.
```
You may need additional loader to handle the result of these loaders.
> import did-update from "../../modifiers/did-update.js
```
We essentially get a error for every modifier that was included with an addon, such as the render-modifiers you see in this short example.

I cannot figure out how to resolve loading these.  Looking for any help!  Thank you

**Comment by ztjohns** [comment]
Ok so I booted up a clean new application using embroider 1.5 modules and only using a single modifiers source (@ember/render-modifiers).  This works with:
```
return require('@embroider/compat').compatBuild(app, Webpack, {
  staticAddonTestSupportTrees: true,
  staticAddonTrees: true,
  staticHelpers: true,
  staticModifiers: true,
  staticComponents: true
})
```

I installed version 2.0.2 of embroider modules with the following dependency exceptions:
- babel-import-util@1.3.0 => we can only get 1.2.2 currently
- ember-template-imports@3.4.0 => we can only get 3.3.1 currently

This build breaks with failure to resolve the imports of modifiers.  Hope this extra information helps. If it is as simple as we need the latest import util, then hopefully we can get that imported quickly.

**Comment by ztjohns** [comment]
Ok just for another test... with the original project i had issues with, I rolled embroider back from 2.0.2 to 1.9.0 and it works with the following config:
```
staticAddonTestSupportTrees: true,
staticAddonTrees: true,
staticModifiers: true,
```

So seems to be in the v2 and it probably has to do with those two dependencies that I do not have access too.

**Comment by ef4** [comment]
Yes, this is definitely because you need babel-import-util 1.3.0. The specific feature was https://github.com/ef4/babel-import-util/pull/8.

**Comment by ztjohns** [comment]
> Yes, this is definitely because you need babel-import-util 1.3.0. The specific feature was [ef4/babel-import-util#8](https://github.com/ef4/babel-import-util/pull/8).

Thanks for getting back to me on this, just before I left the office I got an email letting me know my imports of these dependencies was ready.  I'm excited with your verification to get this running next time I am in the office.

Thanks

**Comment by ef4** [comment]
Maybe your stylesheets are relying on broccoli-asset-rev in production (the "fingerprint" options in ember-cli-build.js)? That doesn't do anything under embroider.

**Comment by ztjohns** [comment]
> 

Thanks for the quick response. We have fingerprint set as `exclude: ["image"]`.  I will try removing this entirely.  This is the only thing hanging up turning on embroider for us.
