### ISSUE TITLE
Stylesheets return content of index.html on localhost

### ISSUE THREAD

**Issue by bobisjan** [embroider-build/embroider#132]
Hello,

I'm testing Embroider in our application, and when open `http://localhost:4200`, fetched styles (both `vendor` and `app`) failed to load, because the content of them is same as `index.html`.

`Refused to apply style from 'http://localhost:4200/assets/styles/vendor.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

- `embroider 0.3.4`
- `ember-cli 3.9.0`

**Comment by ef4** [comment]
This is the same issue as #133. When any file is missing from `dist`, ember-cli assumes it's a route in your application and serves up the index.html file.
