### ISSUE TITLE
can't locate @ember-data/record-data/-private referred to in module rules

### ISSUE THREAD

**Issue by mansona** [embroider-build/embroider#1322]
I'm running tests in ember-try `embroider-safe` and we're getting the following error: 

```
Build Error (WaitForTrees)

can't locate @ember-data/record-data/-private referred to in module rules:{
  "dependsOnModules": [
    "@ember-data/record-data/-private"
  ]
}
```

I've done some debugging and I've found the error that is being thrown in the `resolver.js`

```
'Cannot find module '@ember-data/record-data/-private' from '/private/var/folders/r5/bw5frvnn5k794hk62w3vp7km0000gn/T/embroider/2daa8e/node_modules/.pnpm/@ember-data+store@4.8.4_k6kp2ds5o4a3bn46aja3did5ee/node_modules/@ember-data/store''
```

I had a look at the file on disk and it looks like it's right, there was no sibling to `@ember-data/store` for `record-data` and normal node resolution would be expected to fail.

**Comment by mkszepp** [comment]
Beginning with `ember-data v4.10.x` (atm alpha version 15) there is necessary to remove the addon dependency rules, because they have moved files / modified the build process in `ember-data`
https://github.com/embroider-build/embroider/blob/aa97453277272f533c97db174f6d4b1851e77f9d/packages/compat/src/addon-dependency-rules/ember-data.ts#L3-L18

As workaround for this problem, you can use this lines:

`ember-cli-build.js`
```
   packageRules: [
      {
        package: '@ember-data/store',
        addonModules: {
          '-private.js': {
            dependsOnModules: [],
          },
          '-private/system/core-store.js': {
            dependsOnModules: [],
          },
          '-private/system/model/internal-model.js': {
            dependsOnModules: [],
          },
        },
      },
    ],
``` 

After this fix, you get the next error, which i think is a problem in `ember-data` (starting with v.4.8.x).
`Error while processing route: index Assertion Failed: Expected store.createRecordDataFor to be implemented but it wasn't`

With Ember data 4.8.x you need a other workaround to fix the build process https://github.com/emberjs/data/issues/8296#issuecomment-1314860277
But also with this workaround you are running in the error ´store.createRecordDataFor`

With `ember-data v4.9.1` there is no workaround necessary for embroider, but there is necessary to solve this issue https://github.com/emberjs/data/issues/8396

Since now, i havn't found a complete workaround to fix `ember-data` with `embroider` (without making forks)

**Comment by runspired** [comment]
this should be closable. For 4.8+ embroider should fully deactivate all compat adapters for ember-data.

EmberData's own embroider build at this point specifies the following:

```ts
return require('@embroider/compat').compatBuild(app, Webpack, {
    skipBabel: [
      {
        package: 'qunit',
      },
    ],
    compatAdapters: new Map([
      ['@ember-data/store', null],
      ['@ember-data/record-data', null],
      ['@ember-data/serializer', null],
      ['@ember-data/adapter', null],
      ['@ember-data/model', null],
      ['@ember-data/debug', null],
      ['@ember-data/tracking', null],
      ['@ember-data/request', null],
      ['@ember-data/private-build-infra', null],
      ['@ember-data/canary-features', null],
      ['ember-data', null],
    ]),
    packageRules: [
      {
        package: '@ember-data/store',
        addonModules: {
          '-private.js': {
            dependsOnModules: ['@ember-data/json-api/-private'],
          },
        },
      },
    ],
  });
```

**Comment by mkszepp** [comment]
@runspired i think we can also remove all  `packageRules`, when the app is using ember-data `v4.11.x`.

i think, Embroider doen't need anymore any workarounds for `ember-data`.

```js
packageRules: [
      {
        package: '@ember-data/store',
        addonModules: {
          '-private.js': {
            dependsOnModules: [],
          },
          '-private/system/core-store.js': {
            dependsOnModules: [],
          },
          '-private/system/model/internal-model.js': {
            dependsOnModules: [],
          },
        },
      },
    ],
```

**Comment by ef4** [comment]
We support version ranges on the package rules, so a PR updating the built-in package rules so they stop applying to new-enough versions would be great.

**Comment by esbanarango** [comment]
What's the `@embroider/*` version expected to avoid this error? I'm getting this same error after bumping ember-data to `4.12.0`?

```
    "@embroider/addon-shim": "^1.8.4",
    "@embroider/compat": "2.1.1",
    "@embroider/core": "2.1.1",
    "@embroider/macros": "^1.10.0",
    "@embroider/router": "2.0.0",
    "@embroider/util": "^1.10.0",
    "@embroider/webpack": "2.1.1",
```

**Comment by NullVoxPopuli** [comment]
@esbanarango at present, you need to use the `unstable`-tagged releases to get the work in this PR

**Comment by esbanarango** [comment]
Unfortunately, latest `unstabled`-tagged release completely breaks the app:

```
    "@embroider/addon-shim": "1.8.5-unstable.3a9d8ad",
    "@embroider/compat": "2.1.2-unstable.3a9d8ad",
    "@embroider/core": "2.1.2-unstable.3a9d8ad",
    "@embroider/macros": "1.10.1-unstable.3a9d8ad",
    "@embroider/router": "2.0.1-unstable.3a9d8ad",
    "@embroider/util": "1.10.1-unstable.3a9d8ad",
    "@embroider/webpack": "2.1.2-unstable.3a9d8ad",
```

<img width="1264" alt="SignalUi_Tests" src="https://user-images.githubusercontent.com/1156865/231501609-bff49869-fec4-4c8f-a225-c40a13847a81.png">

**Comment by vlascik** [comment]
as a workaround, you can delete the `node_modules/@embroider/compat/src/addon-dependency-rules/ember-data.js` file.

**Comment by mkszepp** [comment]
the workaround, without removing files is, to add packageRules like described here see https://github.com/embroider-build/embroider/issues/1322#issuecomment-1445804265 So you don't need to use the "unstable" version

```
packageRules: [
      {
        package: '@ember-data/store',
        addonModules: {
          '-private.js': {
            dependsOnModules: [],
          },
          '-private/system/core-store.js': {
            dependsOnModules: [],
          },
          '-private/system/model/internal-model.js': {
            dependsOnModules: [],
          },
        },
      },
    ],
```

**Comment by mkszepp** [comment]
but we run in an other problem with ember-data :(, ember-data is atm not anymore compatible with embroider :(

![grafik](https://user-images.githubusercontent.com/19845290/231664269-663a705b-b55f-4c3f-895b-6414c13ddaf6.png)

**Comment by runspired** [comment]
^ note that this last comment is not an issue with embroider but an issue with the app extending the store from @ember-data/store instead of `ember-data/store` when using `ember-data` which results in incomplete configuration.
