### ISSUE TITLE
Cannot read properties of undefined (reading 'registerV2Addon')

### ISSUE THREAD

**Issue by gossi** [embroider-build/embroider#1325]
I'm hunting a NPE for quite some time now - might be related to #1108 

```
Cannot read properties of undefined (reading 'registerV2Addon')
```

I _may_ have found a fix, but cannot be sure about this 100% yet - but enough to share here already.

## The Situation

I'm upgrading [hokulea](https://github.com/hokulea/hokulea) to [`addons-v2`](https://github.com/hokulea/hokulea/tree/addons-v2). And with these addons v2 I see the error message above. Here is the monorepo and the dependency tree of relevant addons:

```
@hokulea/ember-actions-test-app
|- @hokulea/ember-actions
   |- ember-modifier
   `- @hokulea/ember-foundation
      `- ember-modifer
```

These are the noticable v2 addons, that will go through `@embroider/addon-shim`.

## The Problem

Starting `ember serve` in `@hokulea/ember-actions-test-app` shows the error, that happens when an addon v2 depends on an addon v2 depends on an addon v2 - Two levels is the "threshold" here.

Reason for this in this line:

https://github.com/embroider-build/embroider/blob/aa97453277272f533c97db174f6d4b1851e77f9d/packages/addon-shim/src/index.ts?rgh-link-date=2022-02-04T12%3A53%3A26Z#L77

which calls this method:

https://github.com/embroider-build/embroider/blob/aa97453277272f533c97db174f6d4b1851e77f9d/packages/addon-shim/src/index.ts?rgh-link-date=2022-02-04T12%3A53%3A26Z#L161-L163

Now `autoImportInstance` is set in the code block linked above. Here is the trace in prose:

1. this instance is only available to its direct children `@hokulea/ember-actions` (in the tree above). 
2. That is `@hokulea/ember-actions` has the chance to register its direct v2 addons (`ember-modifer` + `@hokulea/ember-foundation`). 
3. But at the addon instance of `@hokulea/ember-foundation` this `autoImportInstance` is `undefined`
4. `@hokulea/ember-foundation` throws the error above

Given `autoImportInstance` is a local variable not "deeply" available, which makes sense and the reason for two levels being the threshold

1. first level: instantiation
2. second level: use
3. third level+: `undefined` 💣 

## The Suggested Fix

The fix is mentioned in the comment:

https://github.com/embroider-build/embroider/blob/aa97453277272f533c97db174f6d4b1851e77f9d/packages/addon-shim/src/index.ts?rgh-link-date=2022-02-04T12%3A53%3A26Z#L75-L76

but not applied, it is not thrown "higher and higher". The fix would target `registerV2Addon()` method:

```ts
    registerV2Addon(name: string, root: string): void {
      if (autoImportInstance) {
        autoImportInstance.registerV2Addon(name, root);
      } else if (this.parent && this.parent.registerV2Addon) {
        this.parent.registerV2Addon(name, root);
      }
    },
```

Why I'm saying this is only a _suggested_ fix: I'm not sure, if this piece of code is in the intention of the comment or if that means a different implementation (given I have basically no real knowledge about embroider).

What I can say, this makes my build _passes_ this step - I have errors later on, so I cannot be sure as well.

This is ready enough for me for now to share. If my suggested fix is enough, then cool. If not a hint would be nice, so the next time I'm working on this, I can continue digging into it.

**Comment by ACsi** [comment]
I have had the same issue for some time now and have a similar solution. You can check it out here:

https://github.com/ACsi/embroider/tree/fix-addon-shim-registerv2addon-for-deeply-nested-addons
