### ISSUE TITLE
 How to get CSS related assets fingerprinted by Embroider ?

### ISSUE THREAD

**Issue by wandroll** [embroider-build/embroider#1333]
We've struggled when migrating our apps to Embroider to get our assets fingerprinted since broccoli-asset-rev is not compatible with Embroider.

This topic has been partially addressed in the [Asset Importing spec ](https://github.com/emberjs/rfcs/blob/asset-importing-spec/text/0763-asset-importing-spec.md#asset-import-spec) and [this related issue](https://github.com/embroider-build/embroider/issues/755). Though it is still unclear to me how to effectively set it in practice. 
 
Our technique so far has been to :
1 - Setup webpack asset modules in webpack config : 

```js
//ember-cli-build.js
  let { Webpack } = require('@embroider/webpack');
  return require('@embroider/compat').compatBuild(app, Webpack, {
    extraPublicTrees: [redirectTree, versionsTree],
    packagerOptions: {
      webpackConfig:  {
        module: {
          rules: [
            {
              test: /\.(png|jpe?g|svg|)$/i,
              type: env ==='production ? 'asset' : 'asset/resource',
              generator: {
                filename: 'static/[name].[hash][ext][query]',
              },
            },
          ],
    }
    },
  });
  ```
  
  
2 - implement a helper relying on importSync to imports the file : 
```js
import { helper } from '@ember/component/helper';
import { importSync } from '@embroider/macros';

export function importAsset([asset]) {
  return importSync(`/static/${asset.replace(/^\//, '')}`).default;
}

export default helper(importAsset);
```
it seems that way that Webpack is capable of fingerprinting the whole `app/static` folder and pinpoint to the right asset 

and then use it in templates  

``<img src = {{import-asset "/illustration/foo.png"}} />``

Here the path to foo.png  is actually `app/static/illustration/foo.png` and it gets bundled under `dist/static`.

This handles imported assets from templates but it leaves assets imported from CSS ( including fonts for instance) like : 

```css
.foo {
background-image: url("/illustrations/bar.jpeg");
```

Is there any way to make sure Webpack does see them and fingerprint them?

**Comment by ef4** [comment]
This is supposed to work in the default config, because we install [css-loader](https://github.com/webpack-contrib/css-loader).

I'm not sure if it will understand origin-relative URLs, so you might want to try something like:

```diff
-url("/illustrations/bar.jpeg")
+url("../illustrations/bar.jpeg")
```

**Comment by dbendaou** [comment]
It would work for CSS background images, but it wouldn't work for templates, right?

If I've understood correctly, CSS loader is only working for CSS. So we would need to write our custom loader for templates? Or I'm missing something 😄

**Comment by wandroll** [comment]
A bit later, I think I  found what I missed :

- If a component explicitly  imports a CSS file , then it gets through CSS-loader and any assets loaded via url() gets through asset modules  and is fingerprinted.

- CSS loaded via app/styles/app.css doesn't get through Webpack CSS-loader and url() imports can only mention assets that are in the public folder.
