### ISSUE TITLE
Error importing component classes (TypeScript)

### ISSUE THREAD

**Issue by esbanarango** [embroider-build/embroider#1341]
### 🐞 Bug description
Importing a component class ends up being a different object than the class itself. Preventing extending it or interacting with it.

_**This works fine without using TypeScript**_

### 👨‍🔬 Example
Trying to stub some properties or methods of a _Component_ class.

```ts
// This is no longer a valid/normal Class as Embroider has converted into a different (owner) object.
import TestComponent from 'owner-embroider-issue/components/test-component';

module('Integration | Component | test-component', function (hooks) {
  setupRenderingTest(hooks);

  test('...', async function (assert) {
    this.owner.register(
      'component:test-component',
      class extends TestComponent {
        // Propertier and methods I want to override
      }
    );

    await render(hbs`<TestComponent />`);
  });
});
```
When doing: `import TestComponent from 'owner-embroider-issue/components/test-component';`, `TestComponent` is no longer a Class, but a different "object", so we can not "extend" it anymore.

### 😕 Actual Behavior
<img width="1570" alt="215009088-21f31d51-9678-4d68-9d91-cbd6a75d890b_png__2532×1606__🔊" src="https://user-images.githubusercontent.com/1156865/215010662-36bea68d-1a77-4aa4-a8d6-0eb1533e30f0.png">
<img width="946" alt="✖_OwnerEmbroiderIssue_Tests_🔊" src="https://user-images.githubusercontent.com/1156865/215009456-97fd6307-01f2-40e9-9c66-a06fa7ba2aed.png">

### 🤔 Expected Behavior
This is the output without using Typescript
<img width="1244" alt="Cursor_and_OwnerEmbroiderIssue_Tests_🔊" src="https://user-images.githubusercontent.com/1156865/215010353-fb1fc433-1283-4a35-b0b8-a0d6fc48283d.png">

### 🌍 Environment
```json
"@embroider/compat": "^2.0.2",
"@embroider/core": "^2.0.2",
"@embroider/webpack": "^2.0.2",
"ember-source": "~4.10.0",
"ember-cli": "~4.10.0",
"ember-cli-typescript": "^5.2.1",
"typescript": "^4.9.4",
"webpack": "^5.75.0"
```

### 🔀 App to reproduce the issue

https://github.com/esbanarango/owner-embroider-issue/tree/typescript

**Comment by dmuneras** [comment]
Got the same issue :(

**Comment by ef4** [comment]
I think this and https://github.com/embroider-build/embroider/issues/1336 are probably the same bug.

**Comment by ef4** [comment]
Fixed in https://github.com/embroider-build/embroider/pull/1342 and I confirmed that it fixes your reproduction.
