### ISSUE TITLE
Can't get build with `ensureSafeComponent`-call (addon with typescript)

### ISSUE THREAD

**Issue by onechiporenko** [embroider-build/embroider#1356]
According to [REPLACING-COMPONENT-HELPER](https://github.com/embroider-build/embroider/blob/main/REPLACING-COMPONENT-HELPER.md), I'm trying to do next:

```ts
import Component from '@glimmer/component';
import { ensureSafeComponent } from '@embroider/util';
import ABComponent from 'some-addon/components/a-b';

export default class BCComponent extends Component {
  get comp() {
    return ensureSafeComponent(ABComponent, this);
  }
}
```

Next error appears:

```bash
addon/components/b-c.ts:7:32 - error TS2345: Argument of type 'typeof ABComponent' is not assignable to parameter of type 'string | ComponentLike<unknown>'.
  Types of construct signatures are incompatible.
    Type 'new (owner: unknown, args: EmptyObject) => ABComponent' is not assignable to type 'abstract new (...args: any) => InvokableInstance<() => ComponentReturn<FlattenBlockParams<{}>, unknown>>'.
      Property '[Invoke]' is missing in type 'ABComponent' but required in type 'InvokableInstance<() => ComponentReturn<FlattenBlockParams<{}>, unknown>>'.

7     return ensureSafeComponent(ABComponent, this);
                                 ~~~~~~~~~~~

  node_modules/@glint/template/-private/integration.d.ts:22:72
    22 export type InvokableInstance<T extends AnyFunction = AnyFunction> = { [Invoke]: T };
                                                                              ~~~~~~~~
    '[Invoke]' is declared here.
```

ENV:
```bash
$ node -v
v16.14.2

$ npm -v
8.5.0

$ ember -v
ember-cli: 4.10.0
node: 16.14.2
os: win32 x64
```

Repo with demo-project - https://github.com/onechiporenko/ts-embroider-issue-demo

---

Firstly this issue appeared for me in the https://github.com/onechiporenko/ember-models-table here - https://github.com/onechiporenko/ember-models-table/actions/runs/4005420420/jobs/6875751474:
```bash
node_modules/@embroider/util/index.d.ts:1:31 - error TS2307: Cannot find module '@glint/template' or its corresponding type declarations.
```
After adding `@glint/template` to deps next errors appeared - https://github.com/onechiporenko/ember-models-table/actions/runs/4015094016/jobs/6896412016:
```bash
error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'string | ComponentLike<unknown>'.
```
Later I've created a separated repo with new addon and single usage of `ensureSafeComponent` (link above).

**Comment by TusharKoul** [comment]
@onechiporenko were you able to find a solution to this? I'm stuck with the exact same issue

**Comment by onechiporenko** [comment]
@TusharKoul try next:

add to `package.json`:
```
    "@glint/core": "^1.0.2",
    "@glint/environment-ember-loose": "^1.0.2",
    "@glint/template": "^1.0.2",
    "@embroider/macros": "^1.8.0",
    "@embroider/util": "^1.12.0",
```

create `types/glint.d.ts`:
```
import '@glint/environment-ember-loose';
```

add to `tsconfig.json`:
```
"glint": {
    "environment": ["ember-loose"]
  }
```

I'm not sure if that all you need, so feel free to check https://github.com/onechiporenko/ember-models-table repo

**Comment by TusharKoul** [comment]
I'm using ember 3.28 so decided not to use this method at all, since [from the doc](https://github.com/embroider-build/embroider/blob/main/docs/replacing-component-helper.md?rgh-link-date=2024-01-08T17%3A53%3A54Z) it says

> On old Ember versions (< 3.25), when ensureSafeComponent sees a component class, it converts it into a component definition so it can be safely invoked. On newer Ember versions, it does nothing because component classes are directly invokable.
