### ISSUE TITLE
Error with ember-private-api.js and __loader

### ISSUE THREAD

**Issue by ynotdraw** [embroider-build/embroider#1378]
For some reason this morning across multiple repos I'm getting the following error in our v2 add-ons using embroider optimized in our ember-try configs:

```bash
not ok 1 Chrome 111.0 - [undefined ms] - Global error: Uncaught TypeError: Cannot read properties of undefined (reading '__loader') at webpack://test-app/../node_modules/.pnpm/@embroider+util@1.10.0_o3ueax46tohlct7p74rdwqxbue/node_modules/@embroider/util/ember-private-api.js?, line 16
94
    ---
95
        browser log: |
96
            {"type":"error","text":"Uncaught TypeError: Cannot read properties of undefined (reading '__loader') at webpack://test-app/../node_modules/.pnpm/@embroider+util@1.10.0_o3ueax46tohlct7p74rdwqxbue/node_modules/@embroider/util/ember-private-api.js?, line 16\n","testContext":{}}
```

Which points to https://github.com/embroider-build/embroider/blob/00ec2e7e58f546a5e19a23740302e49883d664d3/packages/util/addon/ember-private-api.js#L18

The ember-try config we are using:

- https://github.com/CrowdStrike/ember-headless-form/blob/main/test-app/config/ember-try.js#L60-L75
- https://github.com/CrowdStrike/ember-toucan-core/blob/main/test-app/config/ember-try.js#L44-L59

I'm still digging through the code, but I'm curious why it is going this route, when this macro condition should be met as we are using a new-ish version of Ember?

https://github.com/embroider-build/embroider/blob/00ec2e7e58f546a5e19a23740302e49883d664d3/packages/util/addon/ember-private-api.js#L11

Other potentially helpful links:

- [Toucan-Core master](https://github.com/CrowdStrike/ember-toucan-core/actions/runs/4500544412/jobs/7920001488)
- [Headless-form dummy commit off of master](https://github.com/CrowdStrike/ember-headless-form/pull/102) this morning that was passing [a few days ago](https://github.com/CrowdStrike/ember-headless-form/actions/runs/4479781638)
- [Headless-form Actions Output](https://github.com/CrowdStrike/ember-headless-form/actions/runs/4501225556/jobs/7921394110)

**Comment by ynotdraw** [comment]
> did your lockfile change?

The super interesting thing to me is I just [created a PR](https://github.com/CrowdStrike/ember-headless-form/pull/102) based off of `main` in `ember-headless-form` to get a build and it's now failing with no "real" code changes (only a format to ci.yml); however, `main` was [fine 2 days ago.](https://github.com/CrowdStrike/ember-headless-form/actions/runs/4479781638)

Will give the other options a go! @nicolechung is giving above a try

**Comment by NullVoxPopuli** [comment]
Of note, you're using a floating version of `pnpm` in C.I.: https://github.com/CrowdStrike/ember-headless-form/blob/main/.github/actions/pnpm/action.yml#L8

so it's possible that a recent update in pnpm is causing this -- you could verify by updating your local version to the latest (7.30.1 at the time of writing)

**Comment by NullVoxPopuli** [comment]
Also, this was a temporary fix for a temporary pnpm problem: https://github.com/CrowdStrike/ember-headless-form/blob/main/.github/actions/pnpm/action.yml#L16

you may want to back that out or remove the custom pnpm action entirely in favor of: https://github.com/NullVoxPopuli/limber/blob/main/.github/workflows/ci.yml#L40
