### ISSUE TITLE
`{{ensure-safe-component}}` not working with template tags

### ISSUE THREAD

**Issue by simonihmig** [embroider-build/embroider#1382]
We have an interoperability issue here:
* the `resolver-transform` checks for the existence `ensure-safe-component` helper by a simple [string comparison](https://github.com/embroider-build/embroider/blob/936fd6373339a6848260f6c0a52f426127023299/packages/compat/src/resolver-transform.ts#L233), allowing for the helper to be used _only_ when having exactly that dasherized name
* in a template tag environment, we need to import the helper instead of referring to it by that global string reference. But we cannot import it or alias it using that name, as dashes are not valid identifiers in JS scope

> Note: in my use case there is currently no way to _not_ use `ensure-safe-component`, as I need currying and the curried component is not resolvable using a string. And we don't have a variant of the component helper that does only the currying, without the string lookup (which would then be safe under Embroider)...

Reproduction in this PR: https://github.com/CrowdStrike/ember-headless-form/pull/84/files#diff-e61a0d763a79e50ad7c8eb97240e695edaacc3dde08a2f7669013a45a544f709R527. 
Works fine in classic, but Embroider fails with [`Unsafe dynamic component: cannot statically analyse this expression`](https://github.com/CrowdStrike/ember-headless-form/actions/runs/4542183105/jobs/8005314215#step:5:537) as it does not recognise the camelcased reference.

**Comment by NullVoxPopuli** [comment]
Why use `this`?

I mean, it def should work, but if you need to be unblocked for now, i wouldn't say you need it. Since Field component is just an assignment 

https://github.com/CrowdStrike/ember-headless-form/pull/84/files#diff-e61a0d763a79e50ad7c8eb97240e695edaacc3dde08a2f7669013a45a544f709R195

You could?:
```
        (hash
          Field=(component
            FieldComponent
            data=this.etc
```
Though, maybe i'm missing something?

**Comment by simonihmig** [comment]
> Why use this?

This was needed to fix the linting issue you also saw in your PR, due to the yielded component having a generic type (the `DATA` of the field needs to be the same as that of the parent form). 

But `this` is not even the problem here. Even without it we had that, as you [observed yourself](https://github.com/CrowdStrike/ember-headless-form/pull/90#issuecomment-1478444989). So Embroider will only consider `(component "some-string")` safe, but `(component FieldComponent)` and `(component this.FieldComponent)` are equally considered unsafe, AFAIK.

**Comment by NullVoxPopuli** [comment]
Attempt at test here: https://github.com/embroider-build/embroider/pull/1383
if anything looks off, lemme know

**Comment by simonihmig** [comment]
I can confirm #1383 successfully fixes this! :tada:
