### ISSUE TITLE
Incorrect `rootElement` when running tests on localhost:4200/tests when `storeConfigInMeta: false`

### ISSUE THREAD

**Issue by achambers** [embroider-build/embroider#1387]
I'm not exactly clear why, but it seems that when running tests from localhost:4200/tests and when `storeConfigInMeta: false`, the `rootElement` is not set to `#ember-testing`, but the rootElement used in dev/prod (by default this is `body` but we specify our own selector)

This causes an error in `event_dispatcher.js` that tries to find the root element and attach events to it but can't because it doesn't exist in the DOM. It's looking for `document.querySelector('body');` when it should be looking for `document.querySelector('#ember-testing');` when in `test`.

I have created a minimal reproduction with instructions on how to reproduce the error. You can find it at https://github.com/achambers/repro-embroider-testing-root-element-error

Embroider versions being used:

```
    "@embroider/compat": "^2.1.1",
    "@embroider/core": "^2.1.1",
    "@embroider/macros": "^1.10.0",
    "@embroider/webpack": "^2.1.1",
```

[Extra context on this in Discord, here](https://discord.com/channels/480462759797063690/1090582157728153680/1090582471621484584).

**Comment by achambers** [comment]
Some extra context as I dive in to this.

Given the app name of `with-embroider` and the following setup:

```html
<!-- app/index.html -->

<!-- ...snip... -->

<body>
  <div class="cheese" />
</body>
```

```html
<!-- tests/index.html -->

<!-- ...snip... -->

<body>
  <div id="ember-testing" />
</body>
```

```js
// config/environment.js

module.exports = function (environment) {
  const ENV = {
    APP: {
      rootElement: '.cheese'
    }
  };

  if (environment === 'test') {
    ENV.APP.rootElement = '#ember-testing';
  }
}
```

### Classic Build
When running `ember t -s` with a classic build, searching for `define('with-embroider/config/environment'` we get 3 results.

![image](https://user-images.githubusercontent.com/416724/228816424-24e4ec2b-3c83-41c8-a8ca-74e03021b1ef.png)

As we can see, there are 3 files generated that define the config.

`/assets/tests.js` and `/assets/vendor/ember-cli/app-config.js` both have `rootElement: '#ember-testing'`.
`/assets/with-embroider.js` has `rootElement: '.cheese'`

The `/assets/test.js` and the `/assets/with-embroider.js` files make complete sense to me and explains why the `rootElement` is set as it is. **I'm not familiar with the `/assets/vendor/ember-cli/app-config.js` file however**.

### Embroider Build

When running `ember t -s` with an embroider build, searching for `with-embroider/config/environment` yields 2 results.

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/416724/228828330-47fbe7d6-b096-4e4c-b0d2-05b083babe59.png">

As we can see, there are 3 files generated (`/assets/chunk.<sha>.js` and `/assets/with-embroider.js`) that define the config and both have `rootElement: '.cheese'`

Interestingly the `/assets/with-embroider.js` file path is `webpack://with-embroider/assets.with-embroider.js` where as the other file is `localhost:7021/assets/chunk.<sha>.js`. Is the latter just the compiled version of the former?

**Does this suggest that the "test" config is not actually being generated at all? Like it is in the `/assets/tests.js` file in the classic build?**

@ef4 said:
> I'm guessing that the config module gets produced twice, and one of them lives in the tests.js file and overwrites the app's copy at runtime.

Yep, this seems to be the case to me. However, it also seems that the test config isn't being produced at all for tests.

### Extra context

I just did a search for a test name to find the JS file that the tests are in. It is a different chunk file than is specified above. And, interestingly, that file suggests that it is the compiled version of `/assets/test.js`.

<img width="745" alt="image" src="https://user-images.githubusercontent.com/416724/228830297-879b3fb3-9d77-43ff-b7d1-7ee06290a6f6.png">

Is that the embroider equivalent of the `/assets/tests.js` file in classic? The file does not have any reference to `config/environment` (or `rootElement` for that matter) suggesting it does not redefine the config in the file.

@ef4 I feel like I'm reaching the limits of my knowledge and understanding here. I've been stepping through the classic and embroider build code and have found myself deep in the bowels of both code paths but I feel like I'm not getting much closer to the answer.

Would it be possible to pair on this for 15 mins to identify the root cause and the appropriate fix?

**Comment by achambers** [comment]
Related: Similar issue in the classic build https://github.com/ember-cli/ember-cli/pull/7528

**Comment by acorncom** [comment]
Looks like this issue should be closed given https://github.com/embroider-build/embroider/pull/1412 was merged
