### ISSUE TITLE
Support for nested modules

### ISSUE THREAD

**Issue by tomdale** [embroider-build/embroider#14]
Apologies if this is already covered, I just wanted to get this down so I don't forget.

Ember's JS module API follows a set of rules to help make them more consistent and easier to remember. In particular, classes are intended to be a default export, while things like helper functions should be named exports. Given that a single package may have multiple classes, Ember uses nested modules (e.g. `import MapWithDefault from '@ember/map/with-default'`).

Naturally, addons may want to follow this style, particularly "first-party" addons like Ember Data. We should make sure we have an answer for how addons can provide something like `import JSONAdapter from '@ember-data/adapter/json'` conveniently. It would not be ideal to require users to have to import from paths like `@ember-data/adapter/src/data/adapters/json`.

cc @runspired

**Comment by ef4** [comment]
This is already well supported, closing issue.
