### ISSUE TITLE
Authoring Format ?

### ISSUE THREAD

**Issue by gossi** [embroider-build/embroider#145]
While embroider so far put focus on the publishing format, I had ideas for an authoring format, see here: https://gos.si/blog/thoughts-on-improving-developer-ergonomics-for-emberjs/

I was wondering if they both can go together?

/cc @tomdale

**Comment by Turbo87** [comment]
I don't think that we should conflate the two topics. let's land this incrementally and then worry about the authoring format when the rest is somewhat stable.

**Comment by villander** [comment]
I think the we must focus on the publishing format as well, code splitting and lazy loading is something that we never worries. Is not a good idea huge the world without to do the basic work. We need make embroider more stable and so think about future.

Your point is very good @gossi, but is better like a RFC to embroider

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? If it isn't, maybe we can close this issue?

By closing some old issues we reduce the list of open issues to a more manageable set.
