### ISSUE TITLE
Need to state compatible Ember versions with Embroider

### ISSUE THREAD

**Issue by EWhite613** [embroider-build/embroider#1457]
From the looks of it, it seems like >= 3.28 based on [changelog](https://github.com/embroider-build/embroider/blob/main/CHANGELOG.md#embroidercompat-190---200)?

Probably put in the readme

**Comment by void-mAlex** [comment]
3.28.11 to be precise
happy to take a pr with that
we have a note of that in the upgrade guides here 
https://github.com/embroider-build/embroider/blob/main/docs/upgrade-guides.md?plain=1#L52
