### ISSUE TITLE
Investigate test flakiness of rollup --watch tests on windows in CI

### ISSUE THREAD

**Issue by NullVoxPopuli** [embroider-build/embroider#1465]
passed on the 5th run 
https://github.com/embroider-build/embroider/actions/runs/5198120927

**Comment by ef4** [comment]
I meant to do [3936fdb](https://github.com/embroider-build/embroider/commit/3936fdba9cd0e401f94c47c70cdb4010f3852e3e) in a PR but pushed it directly to main by mistake. I have since updated the branch-protection rules so that they also apply to admins (by default they do not).

**Comment by NullVoxPopuli** [comment]
Resolved in #1473
