### ISSUE TITLE
Build fails if rootURL is not default "/"

### ISSUE THREAD

**Issue by raido** [embroider-build/embroider#151]
It fails with error: `could not find app javascript in index.html`

Reason is that methods in this class: https://github.com/embroider-build/embroider/blob/master/packages/compat/src/v1-app.ts are not `rootURL` aware.

Example: https://github.com/embroider-build/embroider/blob/master/packages/compat/src/v1-app.ts#L540

In case `rootURL` is not `/` then this line `script => script.src === this.app.options.outputPaths.app.js`

Will actually compare something like `/myRootUrl/assets/app.js === /assets/app.js` which obviously fails.

Same issue is with other methods that try to lookup assets from JSDom.

**Comment by astronomersiva** [comment]
This is the same as #148.

I worked around this in my app by changing the conditions to the following pattern:

`script.src.includes(this.app.options.outputPaths.app.js)`

**Comment by ef4** [comment]
It's not quite the same as #148, which involves arbitrarily customizing the output bundle names. `rootUrl` is more constrained and we intend to support it.

It definitely used to work, it looks like we regressed and didn't notice because there's no test coverage for that case.

**Comment by raido** [comment]
Awesome! Waiting for the release to try it out.
