### ISSUE TITLE
Attempted to resolve `did-insert`, which was expected to be a modifier, but nothing was found

### ISSUE THREAD

**Issue by simonihmig** [embroider-build/embroider#1514]
Seeing [this error](https://github.com/simonihmig/ember-stargate/actions/runs/5457107753/jobs/9930794915#step:5:97) pop up (in this [PR](https://github.com/simonihmig/ember-stargate/pull/655), second [70c78db](https://github.com/simonihmig/ember-stargate/pull/655/commits/70c78db19c8cb9c006d2a9b68b0f3102acb65b51) commit). 

I am using `@ember/render-modifiers` (which I probably should get rid off, but they should work nevertheless), but they don't seem to be included into the build. This does get "fixed" by [downgrading to Embroider 2](https://github.com/simonihmig/ember-stargate/pull/655/commits/d4c72a74ffcf674a158dab5a93dc09b12199eb79)!

**Comment by mansona** [comment]
I just confirmed this issue and I have a fix for it (but it is not a good permanent solution) 

Essentially this is the same case that I brought up in the embroider meeting yesterday, the components that are being re-exported via the app exports are depending on something that is in the **dependencies** of the addon. This doesn't work and we agreed that this should be considered a bug from the embroider perspective

The "fix" that I was talking about was to move `@ember/render-modifiers` to be a peer-dependency of the addon and install it directly in the app, but that isn't something that you probably want to ship and we should just fix it upstream
