### ISSUE TITLE
[Octane] babel plugin doesn't seem to be enabled

### ISSUE THREAD

**Issue by balinterdi** [embroider-build/embroider#154]
I tried to integrate embroider (both latest stable, 0.3.4 and canary) into my Octane app but received the following error when doing `ember build`:

> @ember/object does not have a action export

<details>
<summary>Click to expand stack trace</summary>

```
Module build failed (from /Users/balint/code/balinterdi/emberjs/embroider/packages/webpack/node_modules/babel-loader/lib/index.js):
SyntaxError: /private/var/folders/qb/zkbx5mt13qggl5zc8h19fy4h0000gn/T/embroider/1ad5c3/sac-sac-mate/components/detailed-player-card.js: @ember/object does not have a action export
  2 | import move from 'ember-animated/motions/move';
  3 | import scale from 'ember-animated/motions/scale';
> 4 | import { computed, action } from '@ember/object';
    | ^
  5 | 
  6 | export default class DetailedPlayerCard extends Component {
  7 |   selectedFormats = {
    at File.buildCodeFrameError (/Users/balint/code/balinterdi/emberjs/embroider/packages/webpack/node_modules/@babel/core/lib/transformation/file/file.js:261:12)
    at NodePath.buildCodeFrameError (/Users/balint/code/balinterdi/emberjs/embroider/packages/webpack/node_modules/@babel/traverse/lib/path/index.js:157:21)
    at ImportDeclaration.specifiers.forEach.specifierPath (/Users/balint/code/balinterdi/emberjs/embroider/packages/compat/node_modules/babel-plugin-ember-modules-api-polyfill/src/index.js:116:26)
    at Array.forEach (<anonymous>)
    at PluginPass.ImportDeclaration (/Users/balint/code/balinterdi/emberjs/embroider/packages/compat/node_modules/babel-plugin-ember-modules-api-polyfill/src/index.js:78:22)
    at newFn (/Users/balint/code/balinterdi/emberjs/embroider/packages/webpack/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (/Users/balint/code/balinterdi/emberjs/embroider/packages/webpack/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/balint/code/balinterdi/emberjs/embroider/packages/webpack/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/balint/code/balinterdi/emberjs/embroider/packages/webpack/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/Users/balint/code/balinterdi/emberjs/embroider/packages/webpack/node_modules/@babel/traverse/lib/context.js:118:16)
```
</details>

The imports in the file look like this:

```js
import Component from '@ember/component';
import move from 'ember-animated/motions/move';
import scale from 'ember-animated/motions/scale';
import { computed, action } from '@ember/object'; // <= this line throws

export default class DetailedPlayerCard extends Component {
  // (...)
}
```

I asked on Discord and Ed told me that

> @ember/object is supposed to be compiled away by babel because it's not a real package. It sounds like that is not happening for some reason.

I don't see exactly how to interpret that because I don't know about how packages can be real and how babel can compile away "unreal" (virtual?) packages but interestingly, if I remove the `action` from the import and just have `import { computed } from '@ember/object';`, it works fine.

I also went into the folder that embroider builds into and have found the following content in `vendor.js`:

<details>
<summary>The `@ember/object/index` module in the build output (click to expand)</summary>

```
enifed("@ember/object/index", ["exports", "@ember/debug", "@ember/polyfills", "@ember/-internals/metal"], function (_exports, _debug, _polyfills, _metal) {
  "use strict";

  _exports.action = void 0;

  let action;
  _exports.action = action;

  if (true
  /* EMBER_NATIVE_DECORATOR_SUPPORT */
  ) {
      let BINDINGS_MAP = new WeakMap();

      let setupAction = function (target, key, actionFn) {
        if (target.constructor !== undefined && typeof target.constructor.proto === 'function') {
          target.constructor.proto();
        }

        if (!target.hasOwnProperty('actions')) {
          let parentActions = target.actions; // we need to assign because of the way mixins copy actions down when inheriting

          target.actions = parentActions ? (0, _polyfills.assign)({}, parentActions) : {};
        }

        target.actions[key] = actionFn;
        return {
          get() {
            let bindings = BINDINGS_MAP.get(this);

            if (bindings === undefined) {
              bindings = new Map();
              BINDINGS_MAP.set(this, bindings);
            }

            let fn = bindings.get(actionFn);

            if (fn === undefined) {
              fn = actionFn.bind(this);
              bindings.set(actionFn, fn);
            }

            return fn;
          }

        };
      };

      _exports.action = action = function action(target, key, desc) {
        let actionFn;

        if (!(0, _metal.isElementDescriptor)([target, key, desc])) {
          actionFn = target;

          let decorator = function (target, key, desc, meta, isClassicDecorator) {
            true && !isClassicDecorator && (0, _debug.assert)('The @action decorator may only be passed a method when used in classic classes. You should decorate methods directly in native classes', isClassicDecorator);
            true && !(typeof actionFn === 'function') && (0, _debug.assert)('The action() decorator must be passed a method when used in classic classes', typeof actionFn === 'function');
            return setupAction(target, key, actionFn);
          };

          (0, _metal.setClassicDecorator)(decorator);
          return decorator;
        }

        actionFn = desc.value;
        true && !(typeof actionFn === 'function') && (0, _debug.assert)('The @action decorator must be applied to methods when used in native classes', typeof actionFn === 'function');
        return setupAction(target, key, actionFn);
      };

      (0, _metal.setClassicDecorator)(action);
    }
});
```
</details>

It seems to me that the module does have an `action` export but I'm probably missing something.

Any pointers to what's wrong or how I could start tracking down the issue would be appreciated. Thank you.

**Comment by buschtoens** [comment]
`ember-cli-babel` uses [`ember-rfc176-data`](https://github.com/ember-cli/ember-rfc176-data) under the hood to substitute module imports with access to the global `Ember` namespace. In your case, usages of `action` from `@ember/object` get replaced with `Ember._action`.

I have no on-hands experience with Embroider yet, but I would assume that most likely your version of `ember-cli-babel` is not the latest one yet and uses an outdated version of `ember-rfc176-data` that misses the `action` substitution.

Can you try upgrading `ember-cli-babel`?

**Comment by balinterdi** [comment]
Thank you, Jan, you're a genius.

I'm still not there but at least I understand a bit better what's going on.

A mapping for `action` was only added to ember-rfc176-data in version 0.3.8 ([link](https://github.com/ember-cli/ember-rfc176-data/releases/tag/v0.3.8)).

The explicitly defined version of `ember-cli-babel` in my package.json was ^7.7.0 (resolved to 7.7.0) but it turns out I also have ember-cli-babel versions, 6.17.2 and 6.18.0 (required by other packages like `ember-ajax`, `ember-auto-import`, etc.)

One of the dependencies of `ember-cli-babel@6.17.2` is babel-plugin-ember-modules-api-polyfill@^2.5.0 which resolved to 2.5.0. This version depends on a version of `ember-rfc176-data` that is older than `0.3.8` (and thus doesn't have a mapping for the `action` import).

I thought I had the solution: I'd just define a resolution for ember-rfc176-data to make sure I have the right version that contains the `@action` mapping:

```js
// package.json
  "resolutions": {
    "har-validator": "5.1.3",
    "ember-cli-mirage/ember-inflector": "3.0.0",
    "ember-rfc176-data": "^0.3.8"
  }
```

I verified after the yarn install that indeed only version 0.3.8 of ember-rfc176-data is present (checked in `yarn.lock`).

However, nothing much has changed, the app still breaks the same way 🤷‍♂

**Comment by balinterdi** [comment]
Oh, wait! After nuking both the `node_modules` and the `dist` folder in my app (and re-yarning), the build now fails with another error:

```
Build Error (PackagerRunner) in components/board-square.js:4

/private/var/folders/qb/zkbx5mt13qggl5zc8h19fy4h0000gn/T/embroider/1ad5c3/components/board-square.js:

Support for the experimental syntax 'classProperties' isn't currently enabled (4:8):

  2 | 
  3 | export default class BoardSquareComponent extends Component {
> 4 |   rank = null;
    |        ^
  5 |   file = null;
  6 |   numericFile = null;
  7 | 

Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.
```

That seems way better, I'll try to fix this soon. Thanks once more!

**Comment by balinterdi** [comment]
I made some progress but it seems like it's of the "one step forward, two steps back" kind:

The above error could be done away with explicitly installing the `@babel/plugin-proposal-class-properties` package and enabling it in the babel configuration. After that I got another error for a decorator, saying `Support for the experimental syntax 'decorators-legacy' isn't currently enabled`.

I thought Octane does this all by itself (by virtue of having EMBER_NATIVE_DECORATOR_SUPPORT turned on), but I'd reinstalled the `@ember-decorators/babel-transforms` (that I removed when upgrading to Octane) just to see if it solves that problem.

It did, so with these two changes, Embroider has now built my app:

```js
  "devDependencies": {
    "@babel/plugin-proposal-class-properties": "^7.4.4",
    "@ember-decorators/babel-transforms": "^5.2.0",
    (...)
  }
```

```js
module.exports = function(defaults) {
  let app = new EmberApp(defaults, {
    // Add options here
    babel: {
      plugins: [
        "@babel/plugin-proposal-class-properties"
      ]
    }
  });
  (...)
}
```

I felt like these shouldn't be necessary and the solution is fragile and I turned out to be right. When loading up my app, I got a runtime error for a decorator:

```js
  class ComputedDescriptor {
    constructor() {
      this.enumerable = true;
      this.configurable = true;
      this._dependentKeys = undefined;
      this._meta = undefined;
    }

    setup(_obj, keyName, _propertyDesc, meta$$1) {
      meta$$1.writeDescriptors(keyName, this);
    }

    teardown(_obj, keyName, meta$$1) {
      meta$$1.removeDescriptors(keyName);
    }

  }
```

The error was the following:

> Cannot read property 'writeDescriptors' of undefined

I suspect that there is a mismatch of decorator implementations, and the (a) "wrong" one is attempted to be used.

I'll revert the manual babel installs and configurations and try to find out what's wrong with babel support.

**Comment by balinterdi** [comment]
I've verified that the `@babel/plugin-proposal-class-properties` is present in the `yarn.lock` file but the plugin is not present in the `_babel_config_.js` file of the output build.

@ef4 I could spend some time digging into this if it's the right path I'm going down on. It might just be that I need to explicitly tell Embroider somehow to use that babel plugin?

**Comment by stefanpenner** [comment]
Should be fixed by https://github.com/embroider-build/embroider/pull/218

**Comment by stefanpenner** [comment]
fixed https://github.com/embroider-build/embroider/pull/218
