### ISSUE TITLE
Vite 🙃: Uncaught SyntaxError: ambiguous indirect export: has

### ISSUE THREAD

**Issue by NullVoxPopuli** [embroider-build/embroider#1570]
I haven't debugged this yet, but wanted to start an issue in case others run in to this:

Here is the PR where I switch from `@embroider/webpack` to `@embroider/vite`
- https://github.com/NullVoxPopuli/limber/pull/1183
- https://github.com/NullVoxPopuli/polaris-starter/pull/5

The error I get is
```
Uncaught SyntaxError: 
  The requested module '/@id/embroider_virtual:/@embroider/ext-cjs/require' 
    does not provide an export named 'default' (at index.js:4:8)
```
![image](https://github.com/embroider-build/embroider/assets/199018/2da18525-fd9e-4548-afdc-a61dd8e610fd)
![image](https://github.com/embroider-build/embroider/assets/199018/51a58849-2dd0-469f-8edf-f1b49ff943c2)

I've copied all the setup I could find from the https://github.com/embroider-build/embroider/tree/main/tests/vite-app -- but I suspect I'm doing something goofy that's causing `require` to be dumped in there? 
idk, debug time later

**Comment by ef4** [comment]
You missed https://github.com/embroider-build/embroider/blob/e209cc9395c1b271a59e6c7ded663c9b44303f52/tests/vite-app/ember-cli-build.js#L18-L20

**Comment by NullVoxPopuli** [comment]
thanks, confirmed progress.

also, 
![image](https://github.com/embroider-build/embroider/assets/199018/9aba2c7e-d72e-4ec1-bf34-86e18c3903ff)




that's a _really_ nice error. 
great work! :clap: :clap: :clap: :clap:
