### ISSUE TITLE
Ember inspector breaks when `staticEmberSource` is enabled

### ISSUE THREAD

**Issue by Windvis** [embroider-build/embroider#1575]
It seems that when the [`staticEmberSource`](https://github.com/embroider-build/embroider/pull/1521) flag is enabled, all of the ember-source modules (besides `ember/index`) are no longer pushed into the loader.js system. This breaks the Ember inspector since it expects some of those modules to be available. It does have some fallbacks but those are more intended for older Ember versions so those don't work either.

Since the AMD environment is [most likely going away](https://github.com/emberjs/rfcs/pull/938) in the future we probably want an alternative solution for the inspector.

(I'm opening the issue here since it's the new `staticEmberSources` flag that uncovered the problem, but it might be more suited in the ember source or ember-inspector repos.)

**Comment by lifeart** [comment]
Here is minimal config to get `ember-inspector` working without `amd` modules: https://github.com/lifeart/demo-ember-vite/blob/master/src/config/inspector.ts

**Comment by patricklx** [comment]
This is mostly fixed by https://github.com/emberjs/ember-inspector/pull/2475 
Ember inspector can load, but some features like tracked detection and tracked dependencies will be missing
