### ISSUE TITLE
treeForAddon sometimes contains both directory formats

### ISSUE THREAD

**Issue by ef4** [embroider-build/embroider#158]
Some versions of `ember-cli `expected the `treeForAddon` output to be wrapped in a directory named "modules", and others do not. Unfortunately, this means that addons who were doing shenanigans try to mimic either of these behaviors, and we already have code to detect one or the other.

But the bug here is that some addons actually have *both* formats simultaneously. They merge `_super.treeForAddon()` (which on modern ember-cli versions has no `modules` subdir) with their own custom tree that includes the `modules` subdir.

Found while working with @stefanpenner.

**Comment by stefanpenner** [comment]
@ef4 I put together what I believe is a representative example of the `shenanigans` addon -> https://github.com/stefanpenner/addon-shenanigans

List of known issues:

name + moduleName() differ
addon/index.js imports shenanigans/bar which although contained within this modules moduleName is provided via pre-built vendor tree
treeForVendor pulls in an external file, and uses the ember-cli-babel addon to compile it's contents, including it's es module
Note: I have also included other funky things it does, just in-case those also cause grief.


I haven't had a chance yet to add the appropriate test case to embroider, but if I have a few free minutes this weekend I plan to.
