### ISSUE TITLE
Feature Request: Add optional feature detection to @embroider/macros

### ISSUE THREAD

**Issue by rwjblue** [embroider-build/embroider#162]
It is common for addons (and sometimes app code, during a transitionary period) to want to use an optional feature (by way of [@ember/optional-features](https://github.com/emberjs/ember-optional-features)) to do different things.

For example, ember-data would love to be able to do something like:

```js
// app/adapters/rest.js
import { valueForOptionalFeature } from '@embroider/macros';

const useFetch = valueForOptionalFeature('jquery-integration') === false;

// ...snip...
export default Adapter.extend({
  useFetch,
}),
```

---

I'm proposing to add a new `valueForOptionalFeature` macro (for both templates and JS files) that would be replaced at build time with the literal value for the optional feature (values would be `undefined`, `true`, or `false` but could eventually be any JSON serializable value).

**Comment by ef4** [comment]
Closing this because we since added a feature that can do this: `getGlobalConfig` / `setGlobalConfig`. The `@ember/optional-features` package can use it like:

```js
included() {
    this._super.included.apply(this, arguments);
    MacrosConfig.for(this._findHost()).setGlobalConfig(__filename, '@ember/optional-features', {
       SOME_FEATURE: true,
    });
}
```

Then any other package can say:

```js
import { getGlobalConfig } from '@embroider/macros';

const useSomeFeature = getGlobalConfig()['@ember/optional-features'].SOME_FEATURE;
```
