### ISSUE TITLE
Implement and properly test reverse-exports package

### ISSUE THREAD

**Issue by mansona** [embroider-build/embroider#1651]
It's probably best to create a new branch and PR that cherry-picks this commit: https://github.com/embroider-build/embroider/pull/1648/commits/79e377b280ce459c45fcdce9db917c834658d77d

then start adding test cases, and once we're happy we can start on the implementation 👍

**Comment by lolmaus** [comment]
https://github.com/embroider-build/embroider/pull/1652

**Comment by lolmaus** [comment]
Some references:

* https://nodejs.org/api/packages.html#package-entry-points
* https://webpack.js.org/guides/package-exports/

**Comment by mansona** [comment]
Fixed in https://github.com/embroider-build/embroider/pull/1652
