### ISSUE TITLE
Latest release breaks the build

### ISSUE THREAD

**Issue by aklkv** [embroider-build/embroider#1659]
```
node_modules/@embroider/webpack/src/webpack-resolver-plugin.js:91
        return new Promise(resolve => {
               ^

RangeError: Maximum call stack size exceeded

Exception in PromiseRejectCallback:
node:internal/process/promises:116
      unhandledRejection(promise, reason);
      ^
```

**Comment by Yelinz** [comment]
Also have this issue going on, not sure what exactly is causing this. Trying to figure it out.
One of the pipeline runs that failed because of this error:
https://github.com/projectcaluma/ember-alexandria/actions/runs/6875449062/job/18699154732?pr=525

**Comment by void-mAlex** [comment]
thank you I think that can count as a reproduction, it's not minimal, but gives us something to work with
what I find interesting is that it only happens in compat mode and not strict by the looks of it

**Comment by Yelinz** [comment]
Nothing changed and the bugged pipelines pass now, was probably something even more upstream.
Will keep an eye on it.

**Comment by mansona** [comment]
@Yelinz something did change 😂 https://github.com/embroider-build/embroider/pull/1670 fixed this bug and since you're using ember-try it will always use floating dependencies and you will get it automatically 👍
