### ISSUE TITLE
Regression in rebuild times introduced in `@embroider/compat@3.3.1` and `@embroider/core@3.4.1`

### ISSUE THREAD

**Issue by achambers** [embroider-build/embroider#1669]
Hi 👋

When I upgraded `@embroider/compat` and `@embroider/core` to the versions below I noticed a large rebuild time regression.

```diff
- "@embroider/compat": "^3.2.3",
+ "@embroider/compat": "^3.3.0",

- "@embroider/core": "^3.3.0",
+ "@embroider/core": "^3.4.0",
```

I suspect this regression is due to https://github.com/embroider-build/embroider/pull/1627

Below are the timings of rebuilds in both versions

## @embroider/core@3.4.0 (bad)

```bash
Build successful (51382ms) – Serving on http://localhost:4200/a/

Slowest Nodes (totalTime >= 5%)    | Total (avg)
-----------------------------------+---------
@embroider/webpack (2)             | 47871ms (23935 ms)


Build successful (45543ms) – Serving on http://localhost:4200/a/

Slowest Nodes (totalTime >= 5%)    | Total (avg)
-----------------------------------+---------
@embroider/webpack (2)             | 42440ms (21220 ms)
```

## @embroider/core@3.3.0 (good)

```bash
Build successful (11508ms) – Serving on http://localhost:4200/a/

Slowest Nodes (totalTime >= 5%)    | Total (avg)
-----------------------------------+---------
@embroider/webpack (2)             | 8659ms (4329 ms)
Funnel (1938)                      | 1237ms (0 ms)
@embroider/compat/app (1)          | 1047ms


Build successful (10568ms) – Serving on http://localhost:4200/a/

Slowest Nodes (totalTime >= 5%)    | Total (avg)
-----------------------------------+---------
@embroider/webpack (2)             | 7509ms (3754 ms)
Funnel (1938)                      | 1424ms (0 ms)
@embroider/compat/app (1)          | 1059ms
```

**Comment by ef4** [comment]
Please compare the resolver debug logs. `DEBUG=embroider:resolver`. 

Also, double check that when you run with `DEBUG=embroider:debug`, rebuilds should print `reusing webpack config` and not `configuring webpack`.

**Comment by achambers** [comment]
> Please compare the resolver debug logs. `DEBUG=embroider:resolver`.
> 
> Also, double check that when you run with `DEBUG=embroider:debug`, rebuilds should print `reusing webpack config` and not `configuring webpack`.

Yep, will do that tomorrow.

**Comment by raycohen** [comment]
Are you also seeing an initial build time regression? I'm seeing a jump from ~8 minutes to ~11 minutes on my initial build with the latest versions, after updating from `compat 3.2.2 -> 3.3.1` and `core 3.3.0 -> 3.4.2`. I also suspected #1627 might be related.
