### ISSUE TITLE
move the app files in an embroider rewritten app into virtualised content

### ISSUE THREAD

**Issue by mansona** [embroider-build/embroider#1708]
Right now there are some things that require the rewritten-app to have extra imports added to it. For example, if you look at `node_modules/.emberoider/rewritten-app/assets/app-name.js` you will see a long list of `define()` calls with importSync() to parts of your app.

This needs to work more like the `-emborider-implicit-modules` and it should have a pojo that is imported and then defined in a loop 👍

**Comment by lolmaus** [comment]
# Notes

Embroider currently works in three stages:

1. Rewrite addons, outputting it into `my-app/node_modules/.embroider/rewritten-addons/`.
2. Rewrite the app, outputting it into `my-app/node_modules/.embroider/rewritten-app/`.
3. Vite/Webpack takes over, and it uses hooks to interact with Embroider.

Currently, the output of stages 1 and 2 is the input for stage 3, and we want to change stage 2. `rewritten-app/` are now physical files on disk, and we want to virtualize them: Vite/Webpack will be asking Embroider to get the content of those files.

> 💡 In dev mode, the output of Vite is dynamic: when a browser requests a page, Vite would (re)build relevant content and serve it.
> 
> In production mode, the output is a `dist/` folder, but Vite is not doing anything, it's a Rollup build.
>
> In Vite 6, this approach may change.

**Comment by lolmaus** [comment]
> 💡 Future `app/app.js` content:

```js
import Application from '@ember/application';
import Resolver from 'ember-resolver';
import loadInitializers from 'ember-load-initializers';
import config from './config/environment';

// New! In future, this will be part of new app blueprint
i("./-embroider-implicit-modules.js");

import allAppFiles from './-embroider-app-files.js';

for (const name of Object.keys(allAppFiles)) {
  d(name, function () { return allAppFiles[name]}); // no importSync
}
// End New!

export default class App extends Application {
  modulePrefix = config.modulePrefix;
  podModulePrefix = config.podModulePrefix;
  Resolver = Resolver;
}

loadInitializers(App, config.modulePrefix);
```

**Comment by lolmaus** [comment]
Currently, in `my-app/node_modules/.embroider/rewritten-app/assets/app-template.js`, the long list of imports like this:

```
d("app-template/adapters/post", function(){ return i("app-template/adapters/post.js");});
d("app-template/app", function(){ return i("app-template/app.js");});
d("app-template/config/environment", function(){ return i("app-template/config/environment.js");});
d("app-template/models/post", function(){ return i("app-template/models/post.js");});
d("app-template/router", function(){ return i("app-template/router.js");});
d("app-template/serializers/application", function(){ return i("app-template/serializers/application.js");});
d("app-template/component-managers/glimmer", function(){ return i("app-template/component-managers/glimmer.js");});
d("app-template/services/-ensure-registered", function(){ return i("app-template/services/-ensure-registered.js");});
d("app-template/initializers/load-bootstrap-config", function(){ return i("app-template/initializers/load-bootstrap-config.js");});
d("app-template/initializers/app-version", function(){ return i("app-template/initializers/app-version.js");});
d("app-template/data-adapter", function(){ return i("app-template/data-adapter.js");});
d("app-template/initializers/ember-data", function(){ return i("app-template/initializers/ember-data.js");});
d("app-template/services/store", function(){ return i("app-template/services/store.js");});
d("app-template/transforms/boolean", function(){ return i("app-template/transforms/boolean.js");});
d("app-template/transforms/date", function(){ return i("app-template/transforms/date.js");});
d("app-template/transforms/number", function(){ return i("app-template/transforms/number.js");});
d("app-template/transforms/number", function(){ return i("app-template/transforms/number.js");});
d("app-template/transforms/string", function(){ return i("app-template/transforms/string.js");});
d("app-template/services/page-title-list", function(){ return i("app-template/services/page-title-list.js");});
d("app-template/services/page-title", function(){ return i("app-template/services/page-title.js");});
d("app-template/initializers/container-debug-adapter", function(){ return i("app-template/initializers/container-debug-adapter.js");});
d("app-template/templates/ember-data-example", function(){ return i("app-template/templates/ember-data-example.hbs");});
d("app-template/routes/ember-data-example", function(){ return i("app-template/routes/ember-data-example.js");});
d("app-template/templates/application", function(){ return i("app-template/templates/application.hbs");});
d("app-template/templates/components-example", function(){ return i("app-template/templates/components-example.hbs");});
d("app-template/templates/helpers-example", function(){ return i("app-template/templates/helpers-example.hbs");});
d("app-template/templates/macros-example", function(){ return i("app-template/templates/macros-example.hbs");});
d("app-template/templates/static-component-rules-example", function(){ return i("app-template/templates/static-component-rules-example.hbs");});
```

...references two types of modules:

1. templates from the app, because Vite is clueless about `.hbs`;
2. modules from the `app/` folders of addons that a classic Ember app would merge with its own `app/` namespace.

**Comment by lolmaus** [comment]
Instead, in a PR addressing this issue, we want to change that list to something like this:

```js
import allAppFiles from './-embroider-app-files.js';

for (const name of Object.keys(allAppFiles)) {
  d(name, function () { return allAppFiles[name]}); // no importSync! 😙👌
}
```

**Comment by lolmaus** [comment]
`-embroider-app-files.js` is a virtual file that does not exist in an app's source. When Vite/Webpack stumbles upon this import, it would ask Embroider about the content of this file via a hook ([Vite](https://github.com/embroider-build/embroider/blob/main/packages/vite/src/resolver.ts#L14), [Webpack](https://github.com/embroider-build/embroider/blob/main/packages/webpack/src/webpack-resolver-plugin.ts#L54)).

**Comment by lolmaus** [comment]
The source of truth for the content of `-embroider-app-files.js` is here:
https://github.com/embroider-build/embroider/blob/b6c717f1f95994e9fd3d6909f20aa1ca187f5224/packages/compat/src/compat-app-builder.ts#L958

**Comment by mansona** [comment]
I'm considering this closed as we have now virtualised the entrypoint and we will open more issues that cover specific changes we need to do from here 👍
