### ISSUE TITLE
mirage/config.ts isn't found

### ISSUE THREAD

**Issue by raycohen** [embroider-build/embroider#1750]
ember-cli-mirage [funnels](https://github.com/miragejs/ember-cli-mirage/blob/cf8fd03a336ae4da0f93e081180397b64060c325/packages/ember-cli-mirage/index.js#L111) the dummy/mirage folder into the app tree when mirage is in use, so it can be [imported](https://github.com/miragejs/ember-cli-mirage/blob/cf8fd03a336ae4da0f93e081180397b64060c325/packages/ember-cli-mirage/app/initializers/ember-cli-mirage.js#L4) as if it were at `dummy/app/mirage/config`

With embroider, I'm seeing that import of `../mirage/config` works only when `config.js` is used, and not when `config.ts` is used. When it is typescript, I can see the `_app_/mirage/config.ts` file in the rewritten package, but webpack errors on not being able to find it. When it is javascript, `_app_/mirage/config.js` exists and webpack succeeds.

A classic ember build allows both typescript and javascript forms of the config file.

**Comment by NullVoxPopuli** [comment]
it does seem like a bug, but anything outside of the "entrypoint" folders is going to have a rough time with embroider.

easiest path forward is to move your mirage directory in to the app or tests folder.

and then set things config:
```
ENV['ember-cli-mirage'] = {
  directory: 'tests/mirage',
};
```


-----------

entrypoint folders:
- addon
- app
- addon-test-support
- tests (as <app>/tests)

**Comment by raycohen** [comment]
Thanks. Since I'm mostly running into this in dummy apps, that seems like a good enough solution.

**Comment by ef4** [comment]
I think this is a dup of https://github.com/embroider-build/embroider/issues/758

**Comment by raycohen** [comment]
oops, missed that!
