### ISSUE TITLE
docs: inconsistency between `addon-author-guide.md` and ember-welcome-page

### ISSUE THREAD

**Issue by BlueCutOfficial** [embroider-build/embroider#1754]
In the Addon Author Guide, the section [Support Level Embroider Native](https://github.com/embroider-build/embroider/blob/main/docs/addon-author-guide.md#support-level-embroider-native) gives [ember-welcome-page](https://github.com/ember-cli/ember-welcome-page) as an example of V2 addon not using a monorepo:

> it's also OK to keep your test app in a subdirectory of your addon. This is closer to how V1 addons work, where tests/dummy serves this purpose. See [ember-welcome-page](https://github.com/ember-cli/ember-welcome-page) for an example of not using a monorepo -- instead it has a test-app subdirectory and uses the addon-dev command from @embroider/addon-dev to manage linkage between the addon and the test-app and to manage combining of dependencies from both into a single top-level package.json

This example is from Nov 2, 2021 and it seems ember-welcome-page structure has changed since then. Is there any other V2 addon that could serve as an example?

**Comment by BlueCutOfficial** [comment]
Hey @void-mAlex , 

I am not looking for a way to keep the same structure with the test app under the addon. I was simply going through the docs about migrating V1 to V2 and I noticed that this specific part is out of date, because `ember-welcome-page` structure no longer matches what is described. 

I don't have an opinion about how to fix the doc: "is the described solution not recommended at all and should be removed from the docs" or " it's still valid but it should point out something other than `ember-welcome-page`". Also, I am not aware if other parts of this doc could be out of date as well?

**Comment by void-mAlex** [comment]
not sure what others think on this, but for my two cents, I think we should update the addon guide to recommend people use separate packages like the addons named in the doc do (including ember-welcome-page)
happy to take prs to that effect

**Comment by BlueCutOfficial** [comment]
@mansona do you think #1765 is good enough as a quick fix? (I am not aware of what else could be changed)
