### ISSUE TITLE
[Feature request] source map generation

### ISSUE THREAD

**Issue by vstefanovic97** [embroider-build/embroider#1764]
I would like to request for the [rollup-gjs-plugin](https://github.com/embroider-build/embroider/blob/main/packages/addon-dev/src/rollup-gjs-plugin.ts) to return `map` (sourceMaps) as we as the `code` field.

Example where this can be useful, when we are building a v2 addon with the standard v2 blueprint with rollup and let's say we want to use babel-plugin-istanbul to instrument our code, we would need the original source maps so that istanbul would know exactly how to map it's coverage to the original .gjs/.gts source files.

This is also related to https://github.com/embroider-build/content-tag/issues/61 which is needed in order for this to be implemented here

**Comment by NullVoxPopuli** [comment]
If we use `magic-string` in `content-tag` to generate a sourcemap, we could change the [rollup plugin](https://github.com/embroider-build/embroider/blob/main/packages/addon-dev/src/rollup-gjs-plugin.ts#L22) to something like this:

```js
let { code, sourceMap } = processor.process(input, { id, sourceMap: true });

return {
  code,
  map: sourceMap,
};
```
this could be a non-breaking change to content-tag (different return type based on type of the second arg to process)

**Comment by ef4** [comment]
The rust side of `content-tag` already supports source maps. The JS bindings [just don't use it yet](https://github.com/embroider-build/content-tag/blob/384c86b2b7ca1c6743fde45f51ac993ddb4b4b88/src/bindings.rs#L95).

**Comment by vstefanovic97** [comment]
Closing issue as completed in https://github.com/embroider-build/embroider/pull/1786
