### ISSUE TITLE
Addons as scoped packages?

### ISSUE THREAD

**Issue by lupestro** [embroider-build/embroider#18]
Because embroider will support node package resolution, does it follow that builds with embroider will support developing an add-on as a scoped package? Or are there other known issues with scoped packages in existing build tree steps that need to be addressed independently? (I'm trying to see what a checklist for add-ons as NPM scoped packages would look like.)

**Comment by ef4** [comment]
I think scoped packages as ember addons already work in ember-cli. Early on there were definitely bugs that needed squashing but I don’t know of any remaining blockers.

**Comment by lupestro** [comment]
Hmmm... Right now, I'm living with the name scoped in my package.json, but unscoped in index.js, yielding a warning and probably explaining a bunch of ec-addon-docs issues. If I try to scope the name in index.js, the wheels start coming off. I took some stabs at getting past it, but didn't get far, and then I found discussions from a while ago of it not working and I lived with the problem. With confirmation that it's *supposed* to work now, I'll dig further. It could just be I missed one of the places I need to rename an existing add-on after significant work has been done for all the build fragments to line up.

**Comment by ef4** [comment]
Maybe I'm wrong, I thought I had working counterexamples but now that I go looking I do not. And there are open issues like https://github.com/ember-cli/ember-cli/issues/4372

**Comment by lupestro** [comment]
I'm closing this issue - it was a learning process. I figured out what I had to do to make my scoped package, when defined consistently, build and run its dummy without warnings. The key things were to include the scope in all the references to /addon and /public content on the /app side of the addon and in the tsconfig.json file. Thanks, guys.
