### ISSUE TITLE
Consider: babel-plugin-adjust-imports supporting AMD

### ISSUE THREAD

**Issue by stefanpenner** [embroider-build/embroider#182]
Ember add-on unfortunately can export either named amd, or es6 modules. Libraries such as engines, have made this transition graceful (maybe to graceful) by supporting both.

Engines's dependency-funnel https://github.com/ember-engines/broccoli-dependency-funnel supports this via https://github.com/stefanpenner/mr-dep-walk. Relevant tests for that project are: https://github.com/stefanpenner/mr-dep-walk/blob/master/tests/deps-from-file-test.js#L11

**Comment by ef4** [comment]
Yes, I think we should do this. But only for auto-upgraded packages. Meaning that people publishing v2 packages must use ES modules only.

This does put a new requirement on stage3 packagers that they need to understand AMD, or at least the idiosyncratic way the classic build pipeline uses AMD. Webpack does.

**Comment by ef4** [comment]
The gist of it is that this code:

https://github.com/embroider-build/embroider/blob/dcb8927b2f8a35f45762189ea2451576c29c8000/packages/core/src/babel-plugin-adjust-imports.ts#L282-L292

should also be run for each of the dependencies mentioned in the arguments to `define`.

Test coverage could probably be added [here](https://github.com/embroider-build/embroider/blob/master/packages/compat/tests/renaming-tests.ts), or in a new module using that same pattern.

There is also already examples in the plugin for how to test for an auto-upgraded package (`pkg.meta['auto-upgraded']`). If we encounter AMD when that is not true, we should throw.

**Comment by stefanpenner** [comment]
@ef4 nice, will look into it!

**Comment by stefanpenner** [comment]
fixed by: https://github.com/embroider-build/embroider/pull/223 & https://github.com/embroider-build/embroider/pull/227
