### ISSUE TITLE
"Scenario embroider-optimized: FAIL" seen when using index components in tests

### ISSUE THREAD

**Issue by roomman** [embroider-build/embroider#1841]
I have some contextual components in my V1 add-on that have an index.hbs template. For example:
```
- addon
 - components
  - my-component
   - index.hbs
```
That component has a corresponding test file:
```
// tests/integration/components/my-component/index.test.js

import { render } from '@ember/test-helpers';
import { hbs } from 'ember-cli-htmlbars';
import { module, test } from 'qunit';
import { setupRenderingTest } from 'ember-qunit';

module('Integration | Component | my-compnent/index', (hooks) => {
  setupRenderingTest(hooks);

  test('it renders', async function (assert) {

    await render(hbs`<MyComponent />`);

    assert.dom('[data-test-foo]').exists();
  });
});
```
`ember-try` fails on the embroider-optimised scenario with the following error:

```
Build Error (PackagerRunner) in tests/integration/components/my-component/index-test.js

Module not found: Error: Can't resolve '#embroider_compat/components/my-component' in '.../tests/dummy' 
```

If I refactor the test to invoke `await render(hbs`<SollyListContainer::Index />`) the ember-try error goes away but now I am falling foul of ember-template-lint's [no-index-component-invocation](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-index-component-invocation.md).

What is the correct way of resolving this, please?

**Comment by mansona** [comment]
This seems a lot like https://github.com/embroider-build/embroider/issues/1835 🤔

**Comment by roomman** [comment]
> This seems a lot like #1835 🤔

It is, thanks. I will close this and watch that.
