### ISSUE TITLE
Build times out on CI only

### ISSUE THREAD

**Issue by mydea** [embroider-build/embroider#1893]
I am currently trying to set up a test app running embroider, but somehow the build is always timing out without an error on CI:

https://github.com/getsentry/sentry-javascript/actions/runs/8894430829/job/24423226859

Everything works when I run it locally, but on CI it keeps running - I tried extending the runtime to 20 mins, but the same. Locally it only needs <1 min to build, all normal. I don't see how the CI env should be different 🤔 Is there some way to get more logs, or somehow pin down what is causing this?

**Comment by simonihmig** [comment]
Have you tried adding `CI=1` environment variable when running locally? Like `CI=1 ember build`. Not saying that I think I have a lead here, it's just the first thing I tend to do when trying to reproduce CI problems locally.

**Comment by mydea** [comment]
yeah, I did try that, "sadly" it still worked locally 😅

**Comment by mydea** [comment]
Some time later, this now seems to work. No idea what changed (we bumped other stuff in the meanwhile), but I guess we can close this!
