### ISSUE TITLE
Missing app folder referred to in stage1 output

### ISSUE THREAD

**Issue by ef4** [embroider-build/embroider#19]
An app using https://github.com/rwjblue/ember-angle-bracket-invocation-polyfill in an ember version that doesn't need the polyfill ended up with `{ "app-js": "_app_" }` in package.json but that directory wasn't present in the build.

There should either be an empty directory in the stage1 build output, or we should not emit the `app-js` key.

**Comment by josemarluedke** [comment]
I can confirm this was solved in the last release.
