### ISSUE TITLE
Embroider don't works with HOC

### ISSUE THREAD

**Issue by villander** [embroider-build/embroider#192]
Embroider don't works with high order components

```js
import Component from '@ember/component';

export default Component.extend({
  tagName: 'nav',
  classNames: ['nav-bar'],

  /**
   * @property navComponent
   * @type {String}
   * @private
   */
  navComponent: 'x-nav',

  /**
   * @property userProfileComponent
   * @type {String}
   * @private
   */
  userProfileComponent: 'x-nav/user-profile'
});

```

![image](https://user-images.githubusercontent.com/10222774/58292696-a6e46e00-7d98-11e9-869f-6f6292c29608.png)

**Comment by ef4** [comment]
I assume you mean with `staticComponents: true`. Yes, you need to account for all your components to use that feature. If you don't, Embroider emits build warnings. 

Ultimately, we want to rapidly move ember to a place where it's practical to import and pass around components by value. The [RFC that would enable this](https://github.com/emberjs/rfcs/blob/co-location/text/0481-component-templates-co-location.md#4-lack-of-single-import) is already in final comment period.

That would allow us to change APIs like the above example from:

```js
export default Component.extend({
  navComponent: 'x-nav',
});
```

To

```js
import xNav from './x-nav';
export default Component.extend({
  navComponent: xNav
});
```

which makes the dependency clear. However, this is obviously a breaking change for users of that component, and we want to have a smooth compatibility path. So embroider offers `packageRules` that let you tell it about situations like this.

```js
return require("@embroider/compat").compatBuild(app, Webpack, {
    packageRules: [
      {
        // this can be your app, but it can also talk about any addon
        package: "your-app",

        // these are rules about app javascript modules. You can also say
        // `addonModules` when talking about an addon. (Addons have both
        // appModules and addonModules.)
        appModules: {

          // this says that our Javascript file depend on two components.
          // Embroider will synthesize appropriate imports for them, so that
          // whenever your-component.js is loaded, these two components will be
          // loaded too.
          "components/your-component.js": {
            dependsOnComponents: ["{{x-nav}}", "{{x-nav/user-profile}}"],
          },

        },
        components: {
          // This next rule serves two purposes. First, it makes
          //
          //   {{component this.navComponent}}
          //
          // stop emitting a warning in YourComponent's template, because we
          // have accounted for the source of this.navComponent.
          //
          // Second, it lets us know that usages like these
          //
          //   <YourComponent @navComponent="foo"/>
          //   <YourComponent @navComponent={{component "foo"}} />
          //
          // should create a dependency on the "foo" component. And it lets us
          // know that usages like this
          //
          //   <YourComponent @navComponent={{this.foo}} />
          //
          // should emit a warning until someone accounts for the source of
          // this.foo.
          "<YourComponent/>": {
            acceptsComponentArguments: ["navComponent", "userProfileComponent"],
          },
        },
      },
```

**Comment by villander** [comment]
does this need to be supported? given that the majority of the community uses HOC?

anyway thanks for the help.

**Comment by ef4** [comment]
It is fundamentally impossible to support in a fully automatic way. Like, we're up against the halting problem here.

We *do* support higher order components, but people need to take some action to explain to embroider what is going on.

The path forward is to first use `packageRules` to annotate these situations, which makes them work. 

And second, to do an Ember RFC creating new patterns that phase out this dynamic stringly component invocation.

I think perhaps the real immediate bug here is that the warnings we emitted were easy to ignore. I filed https://github.com/embroider-build/embroider/issues/193 about that. Your build should really have errored and told you explicitly that you need to do something to explain where these components are coming from.

**Comment by villander** [comment]
> We do support higher order components, but people need to take some action to explain to embroider what is going on.

yes I wanted to say that this is painful. so think it's so slowly to implement because if I have a big app with a bunch of components HOC like that.

> And second, to do an Ember RFC creating new patterns that phase out this dynamic stringly component invocation.

super agree with you

thanks @ef4
