### ISSUE TITLE
Remove the _babel_filter_ file and skipBabel option from Embroider options

### ISSUE THREAD

**Issue by mansona** [embroider-build/embroider#1963]
`skipBabel` is a build option. But in the new way of writing Ember apps, we don't want the build options to control Babel, we prefer the config file `babel.config.cjs` to be the source of truth. This PR removes `skipBabel` as a build option and removes the `_babel_filter_.js` whose content depends on that option.

Issue number #1962 introduces a more standard shape for `babel.config.cjs`. One piece of this issue is to rely on real babel config options to skip files to achieve what the build option `skipBabel` used to do. e.g. we could use the https://babeljs.io/docs/options#exclude option 👍 so we don't need to provide a custom escape hatch any more.

That's why the PR for the present issue should be merged only after #1962 is implemented and merged:
- First we provide a new way to use `babel.config.cjs` to skip files (#1962)
- Then we remove `skipBabel` option from Embroider (the present issue)

**Comment by mansona** [comment]
This is blocked on https://github.com/embroider-build/embroider/pull/2016

**Comment by BlueCutOfficial** [comment]
Fixed by #2102
