### ISSUE TITLE
Optional peer dependencies

### ISSUE THREAD

**Issue by ef4** [embroider-build/embroider#199]
To guarantee that a package is resolvable from your package, you need to list it as a `dependency` or `peerDependency`. If you don't, you *may* get lucky and find it's resolvable anyway because of NPM hoisting. But we really don't want to rely on this sloppy behavior, especially as better systems like Yarn PnP are becoming viable. Therefore, Embroider is strict and only allows a package to resolve its explicit `dependencies` and `peerDependencies`.

However, we have legitimate use cases for "optional peer dependencies", and that is not a thing NPM supports.

(This also relates to the `dependencySatisfies` macro. In general, you'd want to use it to test whether an optional package is present, so it's not helpful if it only works on your own direct `dependencies` and `peerDependencies`. It follows the same rules as our regular imports, and it's pretty important that it does.)

Yarn [does support optional peer deps](https://github.com/yarnpkg/rfcs/pull/105), in a way that degrades somewhat gracefully when used with NPM. I think we should probably choose to respect that standard.

**Comment by SergeAstapov** [comment]
@ef4 I assume this can be closed? There are examples of using this in the wild, notably https://github.com/miragejs/ember-cli-mirage/pull/2297
