### ISSUE TITLE
codify WebAssembly support

### ISSUE THREAD

**Issue by Turbo87** [embroider-build/embroider#2]
https://github.com/embroider-build/embroider/blob/master/SPEC.md#package-public-api-overview talks about several kinds of assets. WebAssembly will likely become much more relevant in the future, but is not mentioned in this list at all.

- Is support for that planned in any way?
- Do we need to think about this in advance or do you expect it to just fall into place?

**Comment by ef4** [comment]
Webassembly is already supported by ember-auto-import, so I'm quite confident this design will also support it.

(I actually implemented the first webassembly support in auto-import without realizing that I had -- it all Just Worked the first time somebody tried it.)

This does fall into an area that is worth standardizing before we pick a default final-stage packager for all ember-cli users. "Just do whatever webpack supports" is not a good standard that would lock us in, so I think we should make a clearer spec for behaviors like importing a wasm file.

**Comment by ef4** [comment]
I want to write WASM support into the spec so people can use `import()` with WASM files, but I think we need to wait until the [esm integration webassembly proposal](https://github.com/WebAssembly/esm-integration/tree/master/proposals/esm-integration) moves forward.

That said, there's nothing that precludes using WASM via the existing standardized `fetch` and `WebAssembly.instantiateStreaming` APIs, while including the actual WASM payload using the `public-assets` feature.
