### ISSUE TITLE
Figure out how to move the implementation of `updateAppJS` to the virtual files in compat-app-builder.ts

### ISSUE THREAD

**Issue by BlueCutOfficial** [embroider-build/embroider#2022]
The point of this task is that right now we need to define the engine config (that goes into the resolver.json) as part of stage 2. It would be better if stage 3 was more responsive about this and didn't rely on an engine's config that is generated early.

We definitely don't want to rely on any file crawling that happens in stage 2 (i.e. if the engine's config lists any files we should not rely on that in stage 3) but I think we might have solved this already 🤔

**Comment by ef4** [comment]
I think this is done.
