### ISSUE TITLE
find an alternative solution for resolverConfig depending on the files contents of appFiles

### ISSUE THREAD

**Issue by mansona** [embroider-build/embroider#2041]
Currently the resolver config generation in https://github.com/embroider-build/embroider/blob/main/packages/compat/src/compat-app-builder.ts#L185 relies on files discovered in the `updateAppJS()` function. ideally we don't want stage 1/2 to need to do a file tree traversal so if we can come up with an alternative solution that would be better

This is probably closely related to #2022

**Comment by ef4** [comment]
Done.
