### ISSUE TITLE
Projects on embroider don't see the "Non-colocated components" deprecation

### ISSUE THREAD

**Issue by kategengler** [embroider-build/embroider#2066]
A project on latest ember-source (v5.10.2) with many non-colocated component templates wasn't seeing any deprecations for those templates. After investigating, I realized `layoutFor` (the method with the deprecation in ember-source) was never called: The project is using embroider -- embroider is resolving the component's templates at build time. 

Embroider should add this deprecation. 

Relevant RFC advancement PR https://github.com/emberjs/rfcs/pull/1040

**Comment by mansona** [comment]
For stable embroider the relevant place is https://github.com/embroider-build/embroider/blob/stable/packages/core/src/module-resolver.ts#L482-L526

Essentially I think we would either need to check your ember-source version and throw the deprecation if your ember-version matches the deprecation, or we could just decide that when you're using embroider this is just deprecated anyway regardless of your ember-source version 🤔 

I'm going to add this to the agenda for next week to discuss 👍

**Comment by ef4** [comment]
We discussed this at tooling team weekly meeting and the tentative plan is to emit a deprecation inside the virtual pair component at runtime (https://github.com/embroider-build/embroider/blob/8e5763cbf19f400013932a4695c7c8b8ddcf3907/packages/core/src/virtual-content.ts#L67-L77) and also on Ember >= 6 do an actual build failure in the module-resolver where Chris linked above.

**Comment by kategengler** [comment]
Does this need to be backported? Users can easily upgrade ember-source without upgrading embroider.

**Comment by ef4** [comment]
Fixed in #2088.
