### ISSUE TITLE
Component not found in in-repo-addon

### ISSUE THREAD

**Issue by amk221** [embroider-build/embroider#2111]
Our app has a very simple in-repo-addon with just an app directory 

Here is a minimal reproduction:

https://github.com/amk221/-ember-in-repo-addon-gjs/commit/3e27edb3c1e56b82e2b8b1da1fccaf3b47f21873

When switching to Embroider, the components it provides are not available to the host app.

We get this error:

```
Build Error (PackagerRunner) in ../rewritten-packages/styleguide.06e1c7b9/node_modules/styleguide/_app_/templates/styleguide.hbs

Module not found: Error: Can't resolve '#embroider_compat/components/styleguide/layout' in '/Users/andrew/my-app/lib/styleguide'
Did you mean './#embroider_compat/components/styleguide/layout'?
Requests that should resolve in the current directory need to start with './'.
Requests that start with a name are treated as module requests and resolve within module directories (node_modules).
If changing the source code is not an option there is also a resolve options called 'preferRelative' which tries to resolve these kind of requests in the current directory too.
```

**Comment by bartocc** [comment]
@amk221 I was asking about just the same issue an hour ago in the dev-embroider discord… We face the same error, but only when we set the Embroider option `staticComponents: true`. Is that the same for you?

**Comment by mansona** [comment]
So the issue that you have is that there were a couple of non-standard things in your example:

- if you want an addon to be able to use gjs the template-imports addon needs to be in **dependencies** not in **devDependencies**
- I'm pretty sure that you can't get gjs to work in an addon without the re-export implementation

I have opened a PR to your reproduction and that PR works 👍 https://github.com/amk221/-ember-in-repo-addon-gjs/pull/1

**Comment by amk221** [comment]
@bartocc With no options passed to `compatBuild`, it works and I get a runtime error. With `staticComponents: true` I get a build time error.

@mansona Thank you. Buut, I don't want to have to re-export, I have hundreds of files. I'd prefer to utilise the auto-merging of the app directory. Also, the issue remains with `hbs`.

**Comment by mansona** [comment]
are we sure that this actually works with a standard classic addon? i.e. not an in-repo? and when you say the issue remains with `hbs` I assume you mean hbs **only** i.e. if you have a component with a backing class it works fine?

**Comment by amk221** [comment]
Don't worry, I can live with this.
