### ISSUE TITLE
Engines hosted by Embroider App cannot resolve Components from v2 addons

### ISSUE THREAD

**Issue by lfloyd117** [embroider-build/embroider#2113]
It seems that my engine hosted by my Embroider app is unable to resolve components from my local v2 addon. I get this error `Error: Attempted to resolve 'my-component', which was expected to be a component, but nothing was found.`, when that component very much exists from one of my local v2 addons and other apps can resolve it (the v2 addons are all built, and can see the component in the `dist`). My Embroider app can resolve any components on its own, my engine when hosted by a Broccoli app can resolve it, but my engine hosted by an Embroider app cannot.

I have a reproduction here with steps in the README: https://github.com/lfloyd117/embroiderengineaddonissue

It was pointed out on the Discord that my reproduction repo uses pod structure, but I can confirm the issue happens just the same with classic layout.

**Comment by lfloyd117** [comment]
@ef4  Hmm, let me take a look at updating the reproduction then because our real repo does all of this. 
The `index.js` missing the `engine-addon` extension & the keyword in the package.json are both preset in our real engine & our addons don't do template co-location and follow `src/components/my-test-title.{js,hbs}`.

Any yet we still see this issue.

**Comment by ef4** [comment]
In that commit you changed the engine to be a lazy engine. To use a lazy engine with embroider you need to replace the app's import of `@ember/routing/router` with `@embroider/router` (and install the `@embroider/router` package).

When I tested I left it as an eager engine, in which case you don't need `@embroider/router` to lazily load it.

**Comment by lfloyd117** [comment]
@ef4  Thank you! That did the trick!

**Comment by ef4** [comment]
If you're able to write down any of these findings for the next person who will try to do this it would be very appreciated. I don't know what the ideal spot is but anything is better than nothing. Perhaps a new markdown file in our /docs folder like `/docs/engine-support.md`.

**Comment by lfloyd117** [comment]
@ef4  Absolutely, was planning on it. I did end up finding the use of `@embroider/router` for lazy engines in the Embroider README, but a specific engines & Embroider doc would be helpful for sure.

**Comment by void-mAlex** [comment]
@lfloyd117 happy to take prs on the engines repo(s) as well. more places we have info easier it will be for people
