### ISSUE TITLE
@babel/plugin-proposal-class-properties issue

### ISSUE THREAD

**Issue by stefanpenner** [embroider-build/embroider#214]
An app that functions without embroider enabled, currently fails when embroider is enabled when `classProperties` are used.  

```js
Build Error (PackagerRunner) in app.js:7

/private/var/folders/4r/whc65vwj1xggvvky3yy1cp9m000mw4/T/embroider/2e1ac4/app.js: Support for the experimental syntax 'classProperties' isn't currently enabled (7:16):

   5 |
   6 | class App extends Application {
>  7 |   modulePrefix = config.modulePrefix;
     |                ^
   8 |   podModulePrefix = config.podModulePrefix;
   9 |   Resolver = Resolver;
  10 | }

Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.


Stack Trace and Error Report: /var/folders/4r/whc65vwj1xggvvky3yy1cp9m000mw4/T/error.dump.33e3fb7de16d52c299f3b39be89e429c.log
```

```js
Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.
        at PackagerRunner (@embroider/webpack)
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: app.js
    - line: 7
    - treeDir: [undefined]
  - message: app.js:7: /private/var/folders/4r/whc65vwj1xggvvky3yy1cp9m000mw4/T/embroider/2e1ac4/app.js: Support for the experimental syntax 'classProperties' isn't currently enabled (7:16):

   5 | 
   6 | class App extends Application {
>  7 |   modulePrefix = config.modulePrefix;
     |                ^
   8 |   podModulePrefix = config.podModulePrefix;
   9 |   Resolver = Resolver;
  10 | }
```
Interesting files:
* [Error Log](https://gist.github.com/stefanpenner/e6e8e0f71c2f03095178f6d8eb29f3fa)
* [_babel_config_.js](https://gist.github.com/stefanpenner/ec59bb84d455d24c1580875af88c2161)

**Comment by ef4** [comment]
How is the babel plugging getting added? Directly by the app, or an addon mutating the app's babel config?

**Comment by stefanpenner** [comment]
@ef4 investigating now.

**Comment by stefanpenner** [comment]
potentially via: https://github.com/babel/ember-cli-babel/blob/03324217d4ec9b783362d943a31916538ca36510/index.js#L329

**Comment by rwjblue** [comment]
ember-cli-Babel includes it by default

**Comment by rwjblue** [comment]
https://github.com/babel/ember-cli-babel/pull/274 added decorator and class properties support by default (as was proposed in https://github.com/emberjs/rfcs/pull/0408 and https://github.com/emberjs/rfcs/pull/440).

**Comment by stefanpenner** [comment]
Once we get to configuring webpack's babel [here](https://github.com/embroider-build/embroider/blob/dcb8927b2f8a35f45762189ea2451576c29c8000/packages/webpack/src/ember-webpack.ts#L247) we no longer have reference to the above mentioned plugin.

**Comment by stefanpenner** [comment]
The following re-implements part of ember-cli-babel https://github.com/embroider-build/embroider/blob/dcb8927b2f8a35f45762189ea2451576c29c8000/packages/compat/src/v1-app.ts#L186-L237 and  could be related, stepping in now.

**Comment by stefanpenner** [comment]
Ya that is the issue, mega haxor confirming: https://github.com/embroider-build/embroider/pull/215

**Comment by stefanpenner** [comment]
likely fixed by: https://github.com/embroider-build/embroider/pull/218
