### ISSUE TITLE
Wrong minimal version stated on docs

### ISSUE THREAD

**Issue by gabrielmaiaf** [embroider-build/embroider#2154]
While reviewing the docs, it says that the minimal Ember version is 3.28.11 but this version doesn't exists.
I saw this issue (https://github.com/embroider-build/embroider/issues/1457) pointing to this page (https://github.com/embroider-build/embroider/blob/main/docs/upgrade-guides.md?plain=1#L52) but the 3.28.11 is for ember-source, not ember-cli.
I think we can update to 3.28.6 in Ember but 3.28.11 for Ember-source

**Comment by void-mAlex** [comment]
Ember version always refers to ember-source not ember-cli
3.28.11 exists and here is the link to it
https://www.npmjs.com/package/ember-source/v/3.28.11
today the latest version would be 3.28.12 and that should be used instead of .11
