### ISSUE TITLE
Don't emit multiple shims for same module name

### ISSUE THREAD

**Issue by ef4** [embroider-build/embroider#22]
We emit shim modules to connect build-time resolved modules with runtime modules that we can't prove aren't needed. They will necessarily get flattened into the runtime AMD namespace, so we should definitely not emit multiple shims that target the same name.

For max compat, we should copy ember-cli's existing priority order here.

**Comment by NullVoxPopuli** [comment]
did we do this? :sweat_smile:

**Comment by ef4** [comment]
Yes.
