### ISSUE TITLE
addon test support rewriter bug

### ISSUE THREAD

**Issue by ef4** [embroider-build/embroider#25]
The addon test support rewriter can error when an addon emits `my-name.js` and doesn't have a `my-name` directory.

ember-cli-qunit 4.4.0 reproduces this behavior.

**Comment by josemarluedke** [comment]
I just run into this error when trying out embroider. 

[Here is a repro](https://github.com/josemarluedke/my-embroider-test), it fails because of `ember-qunit`.


```
Building into /private/tmp/embroider-workspace
Build Error (WaitForTrees)

ENOENT: no such file or directory, lstat '/private/tmp/embroider-workspace/node_modules/ember-qunit/_app_'


Stack Trace and Error Report: /var/folders/67/6jb5flcd6d30lkgvj0_92c_m0000gn/T/error.dump.bbd64d94aaea202c2c2c4ed7e836185b.log

```

**Comment by ef4** [comment]
I suspect what you hit is https://github.com/embroider-build/embroider/issues/19
