### ISSUE TITLE
allow sourceMap options to be configurable

### ISSUE THREAD

**Issue by stefanpenner** [embroider-build/embroider#258]
We should do something similar to ember-auto-imports `forbidEval`

> forbidEval: boolean, defaults to false. We use eval in development by default (because that is the fastest way to provide sourcemaps). If you need to comply with a strict Content Security Policy (CSP), you can set forbidEval: true. You will still get sourcemaps, they will just use a slower implementation.

**Comment by stefanpenner** [comment]
https://github.com/embroider-build/embroider/blob/master/packages/core/src/options.ts#L1

**Comment by stefanpenner** [comment]
around https://github.com/embroider-build/embroider/blob/master/packages/webpack/src/ember-webpack.ts#L232 we should use `devtools:` option, and if `forbidEval`is `true` we should make `devtools` false.

**Comment by thoov** [comment]
In `ember-cli-build.js` you can do the following which will disable evals:

``` 
if (process.env.EMBROIDER) {
    const Webpack = require('@embroider/webpack').Webpack;
    return require('@embroider/compat').compatBuild(app, Webpack, {
      compatAdapters: new Map([['ember-decorators', null]]),
      packagerOptions: {
        webpackConfig: {
          devtool: false
        }
      }
    });
  }
```

**Comment by rwwagner90** [comment]
I tried this suggestion of `devtool: false` but I am still getting eval errors. It doesn't seem like it works the same as `forbidEval`.
