### ISSUE TITLE
Need to build engines config/environment

### ISSUE THREAD

**Issue by ef4** [embroider-build/embroider#26]
Addons that are engines have a config/environment that needs the same handling we already give to app's config/environment.

**Comment by villander** [comment]
@ef4 where are you dealing with the config/environment here on the embroider? I want to do work for the addos that are engines.

**Comment by ef4** [comment]
Here is where we emit a broccoli tree that contains config/environment.js:

https://github.com/embroider-build/embroider/blob/728bbe28a2f407acc0db657ba435ba6d9b0a82a6/packages/compat/src/v1-app.ts#L473

You'll want to call something similar in the `build` method in v1-addon.js when the addon is an engine.

**Comment by lennyburdette** [comment]
I just hit this in my app. I hand-wrote the config/environment modules for my engines just to test things and also discovered that index.html still has `<meta name="application/config/asset-manifest" content="%GENERATED_ASSET_MANIFEST%">`. 

ember-asset-loader replaces that placeholder string in a postprocessTree hook: https://github.com/ember-engines/ember-asset-loader/blob/ae615df700b20fd619be76ecb94e7699d96d0cba/lib/manifest-generator.js#L30.

Should I open a separate ticket for this? Or are you planning to rethink engine assets generation now that you have route-based code-splitting in embroider?

**Comment by ef4** [comment]
This was fixed back in https://github.com/embroider-build/embroider/pull/283
