### ISSUE TITLE
Can't resolve '../tests/test-helper'

### ISSUE THREAD

**Issue by josemarluedke** [embroider-build/embroider#261]
This only happens if my test-helper file is in Typescript.

`tests/test-helper.ts` instead of `tests/test-helper.js`. 

I use TS file to be able to import `qunit-dom`, if I let it be in JS, then Embroider complains about not finding it: `Can't resolve 'qunit-dom'`.

Used v0.4.3 of Embroider.

**Comment by ef4** [comment]
I think the issue with typescript was fixed in 0.5.0.

**Comment by makepanic** [comment]
I'm also seeing this issue on 0.6 in a `tests/test-helper.js` file.

Removing `import 'qunit-dom';` seems to fix the issue but that'll break our tests

**Comment by ef4** [comment]
@makepanic it sounds like you have encountered a new bug, please file a separate issue. This issue only occurred in a file named `tests/test-helper.ts`, it didn't occur in `tests/test-helper.js`.
