### ISSUE TITLE
Can't resolve '../helpers/my-mock' using fastboot-testing

### ISSUE THREAD

**Issue by josemarluedke** [embroider-build/embroider#262]
I'm using ember-cli-fastboot-testing to write fastboot tests in my app. I have a folder called fastboot under tests for these tests.

Here is the file:

```js
// tests/fastboot/home-page-test.js

import { module, test } from 'qunit';
import {
  setup,
  visit
} from 'ember-cli-fastboot-testing/test-support';
import { mockData } from 'my-app/tests/helpers/my-mock';
```

Note the import above for `my-mock`. If I change the import to be relative, the problem still happens.

```
Build Error (PackagerRunner)

Module not found: Error: Can't resolve '../helpers/my-mock' in '/private/var/folders/67/6jb5flcd6d30lkgvj0_92c_m0000gn/T/embroider/0b9275/tests/fastboot'

Stack Trace and Error Report: /var/folders/67/6jb5flcd6d30lkgvj0_92c_m0000gn/T/error.dump.c24761dff1714e918b662c564762041a.log
```

Used v0.4.3 of Embroider.

**Comment by knownasilya** [comment]
Having a similar issue, although not in tests, but the import is similar.

```
Module not found: Error: Can't resolve '../../crashkit/authenticators/crash' in '/private/var/folders/hq/m0d3mb8s5gd1wdbn_gsk55000000gn/T/embroider/432507/web/assets/@crashco'
```

where the import is `export { default } from '@crashco/crashkit/authenticators/crash';`

**Comment by tschoartschi** [comment]
I'm experiencing a similar problem 🤔 we are using `ember-cli-mirage` and we have a `mirage` folder with `scenarios`. 

Therefore we have a file at `mirage/scenarios/catalog-page-scenario.js`. Inside this file we do the following: 

```typescript
import { setupTenantAndUser } from 'roomle-pdc/tests/helpers/data';
```

Now we get the following error:

```
ERROR in ./mirage/scenarios/catalog-page-scenario.js 2:0-62
Module not found: Error: Can't resolve '../../tests/helpers/data' in '$TMPDIR/embroider/c8289c/mirage/scenarios'
 @ ./assets/roomle-pdc.js 128:13-68
```

When I have a look at `$TMPDIR/embroider/c8289c/` the only content of the `tests` folder is `tests/helpers/ember-power-select.js`.

Does someone knows a workaround or how to debug this issue?

**Comment by tschoartschi** [comment]
I found a temporary solution so that at least the dev-build works. This is what I do:

```typescript
    const funnel = require('broccoli-funnel');
    const tests = funnel('./', {
        srcDir: '/tests/',
        destDir: '/tests/',
    });

    return require('@embroider/compat').compatBuild(app, Webpack, {
        extraPublicTrees: [
            tests
        ],
    });
```

Not sure if this is really a solution but at least I can now continue to try out Embroider 🙂
