### ISSUE TITLE
`Duplicate plugin/preset detected.` while building with 0.5.1

### ISSUE THREAD

**Issue by lstrzebinczyk** [embroider-build/embroider#274]
Hello

I wanted to try building my app with ebroider 0.5.1 to see if it resolves my earlier issue, and I received this error while building:

```
Build Error (PackagerRunner)

Module build failed (from /home/killa/workspace/SBweb/node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
Duplicate plugin/preset detected.
If you'd like to use two separate instances of a plugin,
they need separate names, e.g.

  plugins: [
    ['some-plugin', {}],
    ['some-plugin', {}, 'some unique name'],
  ]

    at assertNoDuplicates (/home/killa/workspace/SBweb/node_modules/@babel/core/lib/config/config-descriptors.js:205:13)
    at createDescriptors (/home/killa/workspace/SBweb/node_modules/@babel/core/lib/config/config-descriptors.js:114:3)
    at createPluginDescriptors (/home/killa/workspace/SBweb/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
    at alias (/home/killa/workspace/SBweb/node_modules/@babel/core/lib/config/config-descriptors.js:63:49)
    at cachedFunction (/home/killa/workspace/SBweb/node_modules/@babel/core/lib/config/caching.js:33:19)
    at plugins.plugins (/home/killa/workspace/SBweb/node_modules/@babel/core/lib/config/config-descriptors.js:28:77)
    at mergeChainOpts (/home/killa/workspace/SBweb/node_modules/@babel/core/lib/config/config-chain.js:319:26)
    at /home/killa/workspace/SBweb/node_modules/@babel/core/lib/config/config-chain.js:283:7
    at buildRootChain (/home/killa/workspace/SBweb/node_modules/@babel/core/lib/config/config-chain.js:68:29)
    at loadPrivatePartialConfig (/home/killa/workspace/SBweb/node_modules/@babel/core/lib/config/partial.js:85:55)


Stack Trace and Error Report: /tmp/error.dump.1255fbe0311d73a7e380da092b925705.log
```

Te full stack trace contains no more useful information, to my eye. Also, I'm fairly sure that the `thread-loader` is only used by "@embroider/webpack".

I am certainly not doing anything with babel myself, so possibly one of my dependencies?
If there is anything more I can provide to help resolve this issue, please let me know.

**Comment by ef4** [comment]
Thanks for testing and reporting. This is most likely introduced by https://github.com/embroider-build/embroider/pull/270

We probably need to do some deduplicating when we merge the app's plugins and the ember-cli-babel default plugins. We should do the same thing ember-cli does normally.

You can probably figure out which plugin got duplicated by looking at `_babel_config_.js` in the build directory (the path that prints as "Building into..."). If you aren't adding any plugins directly in the app, it's probably one of your addons pushing plugins into the app's config.

**Comment by lstrzebinczyk** [comment]
Yeah, I see that `@babel/plugin-proposal-class-properties` is duplicated, but there could be more, the file is ~450 lines long. Is solving this problem equal to writing a function that accepts such plugins config json and returns deduplicated json? Is this already solved in "regular" ember cli?

**Comment by NullVoxPopuli** [comment]
emberclear has this issue as well :)

**Comment by josemarluedke** [comment]
I have seen this as well but only when using ember-cli-typescript. 

I know that using master of ember-cli-typescript solved this issue for me. 

@NullVoxPopuli emberclear uses typescript, so could you try master of ember-cli-typescript to check if that solves for you?

**Comment by NullVoxPopuli** [comment]
I got a different error:
```
Build Error (PackagerRunner)

Module not found: Error: Can't resolve '../styles/components/notification-container' in '/tmp/embroider/25570d/node_modules/ember-cli-notifications/components'


Stack Trace and Error Report: /tmp/error.dump.1b760d5a2c1485ad3d01e779e94f249e.log
```
stylesheet that's trying to be included from an addon

**Comment by rwjblue** [comment]
FWIW, the original error reported here is pretty horrible. I just had to deep dive another scenario where babel threw the error, and I figured I'd mention it here in  case folks find it relevant:

https://github.com/hjdivad/ember-m3/pull/386

**Comment by ef4** [comment]
Ah, thanks for that clue.

**Comment by lstrzebinczyk** [comment]
Embroider 0.7 is throwing a different error now for my build, I'm closing this issue since it's probably no longer relevant.
