### ISSUE TITLE
Can't resolve 'crypto' – or could not find module `webcrypto-jwt`

### ISSUE THREAD

**Issue by balinterdi** [embroider-build/embroider#280]
I'm presented with the following error in my app:

```
Build Error (PackagerRunner)

Module not found: Error: Can't resolve 'crypto' in '/Users/balint/code/balinterdi/emberjs/rarwe-book/rarwe-3/node_modules/jwa'

Stack Trace and Error Report: /var/folders/qb/zkbx5mt13qggl5zc8h19fy4h0000gn/T/error.dump.cad65a77bb2e14de5d99d4f53c7eb549.log
```

The dependency path of crypto is `jsonwebtoken` (a top-level dep) => `jws` => `jwa` => `crypto`.

I'm using node v10.15.3 in which `crypto` is part of the standard library but it's also provided by the `webpack => node-libs-browser => crypto-browserify` dependency path.

The build is successful without Embroider and I also tried to re-yarn the whole package after nuking the node_modules folder.

**Comment by balinterdi** [comment]
Based on a suggestion on Discord, I replaced `jsonwebtoken` with a library that uses `webcrypto` (and thus doesn't use the node `crypto` library): https://github.com/pose/webcrypto-jwt/ .

Indeed, this way Embroider did build my app but when I loaded it up, I received a very similar error:

```
Uncaught Error: Could not find module `webcrypto-jwt` imported from `(require)`
    at missingModule (loader.js:247)
    at findModule (loader.js:258)
    at requireModule (loader.js:24)
    at eval (webcrypto-jwt.js:1)
    at Object.../../../externals/webcrypto-jwt.js (chunk.72b976eb422dbef8668b.js:76)
    at __webpack_require__ (chunk.2adee8e440eade0493ab.js:79)
    at eval (config.js:5)
    at Module../mirage/config.js (chunk.72b976eb422dbef8668b.js:1272)
    at __webpack_require__ (chunk.2adee8e440eade0493ab.js:79)
    at eval (ember-cli-mirage.js:4)
```

In the incriminated file, I use the import as follows:

```js
// config/mirage.js
import Response from 'ember-cli-mirage/response';
import ENV from 'rarwe/config/environment';
import jwt from 'webcrypto-jwt';
import { assert } from '@ember/debug';
(...)
```

**Comment by ef4** [comment]
When you say  "The build is successful without Embroider", do you mean using ember-auto-import? If so, it would be a bug if embroider and ember-auto-import are doing things differently.

We don't automatically polyfill node libraries for the browser. But that should be equally true on the latest ember-auto-import and under embroider.

Even under embroider, you need to depend on ember-auto-import if you want your app to import from NPM. We use that dependency as the opt-in for that behavior (and it ensures your code is valid under both embroider and classic ember-cli).

The error message referring to `externals/webcrypto-jwt.js` means embroider thinks that isn't a resolvable dependency. It needs to be in your app's `dependencies` or `devDependencies` in `package.json` and you need to also depend on ember-auto-import.

**Comment by balinterdi** [comment]
> When you say "The build is successful without Embroider", do you mean using ember-auto-import? If so, it would be a bug if embroider and ember-auto-import are doing things differently.

Yes.

> Even under embroider, you need to depend on ember-auto-import if you want your app to import from NPM. We use that dependency as the opt-in for that behavior (and it ensures your code is valid under both embroider and classic ember-cli).

> The error message referring to externals/webcrypto-jwt.js means embroider thinks that isn't a resolvable dependency. It needs to be in your app's dependencies or devDependencies in package.json and you need to also depend on ember-auto-import.

Makes sense. I have both ember-auto-import (1.2.19) and webcrypto-jwt (0.2.2) in the project's devDependencies.

**Comment by ef4** [comment]
> ember-auto-import (1.2.19) 

Ah, so if you upgrade to the latest ember-auto-import it will break there too, and we will at least be consistent. 😁 Sorry, it was unintentional that we automatically included polyfills, that behavior has been removed.

I just tested auto-importing webcrypto-jwt under both classic ember-cli and embroider and I couldn't reproduce the problem. I'm testing with ember-auto-import 1.5.2 and embroider master.

**Comment by balinterdi** [comment]
I still get the same error after upgrading to ember-auto-import 1.5.2  😕

You added a line that said `import jwt from 'webcrypto-jwt'` and that didn't throw an error?

I added you to the repository if you have time to take a quick look. (It's the `embroider` branch).

**Comment by balinterdi** [comment]
I just tried this again on my "embroider sandbox", a minimal application (3.9) that only has embroider (and ember-font-awesome) added to make sure it's not another dependency that causes the failing import.

I tried to import jwt from the application route and received the same error message as above.

**Comment by balinterdi** [comment]
So this is interesting.

If I import jwt from the application route, it works fine. However, if I import it from `mirage/config.js`, it throws the "Could not find module `webcrypto-jwt` imported from `(require)`" error, as seen above in detail.

Is there any difference between the import paths available in `mirage/config.js` and `app/routes/application.js`?

**Comment by ef4** [comment]
> Is there any difference between the import paths available in mirage/config.js and app/routes/application.js?

There's not supposed to be, but a bug like that is possible.

But I'm unable to reproduce the problem you're describing. I made a new app at ember-cli 3.9, added ember-cli-mirage, ember-auto-import, and ember-font-awesome, and tested it both under the regular build and adding embroider (both embroider master and the 0.5.1 release). None of the scenarios failed.

**Comment by balinterdi** [comment]
Can you check the embroider branch of the R&R app just to see if it also works for you? (I added you recently as a collaborator.)

**Comment by balinterdi** [comment]
I have another question, though :)

Should the following import be allowed in Embroider?

```js
// mirage/config.js

import ENV from 'rarwe/config/environment';

(...)
const { jwtSigningKey, signingAlgorithm: algo } = ENV.APP;
```

It doesn't throw an error, but `ENV.APP` (more precisely, the module transpiled by Webpack) has the following content instead of the expected configuration options:

```
> _var_folders_qb_zkbx5mt13qggl5zc8h19fy4h0000gn_T_embroider_externals_rarwe_config_environment__WEBPACK_IMPORTED_MODULE_1___default.a.APP
< { name: "rarwe", version: "0.0.0+a5e78c6d" }
```

**Comment by ef4** [comment]
Yes, that import should be allowed. If you have a reproduction of it working differently between embroider and the stock build please file an issue for that.

**Comment by balinterdi** [comment]
Sorry, you're right. The real issue seems to be #287.
