### ISSUE TITLE
Tests fail to run with Mirage

### ISSUE THREAD

**Issue by balinterdi** [embroider-build/embroider#287]
Versions:

* Embroider: current master (418af5a7fe53e8947a9a0454fdc01649be6fb22b)
* ember-cli-mirage: 1.1.0
* ember-auto-import: 1.5.2

When an application has Mirage installed, test runs give an early failure, when checking if Mirage should be used:

```
TypeError: Cannot destructure property `getContext` of 'undefined' or 'null'.
    at getRfc232TestContext (webpack:///./node_modules/ember-cli-mirage/get-rfc232-test-context.js?:18:9)
    at _shouldUseMirage (webpack:///./initializers/ember-cli-mirage.js?:57:109)
    at Object.initialize (webpack:///./initializers/ember-cli-mirage.js?:38:9)
    at http://localhost:7357/assets/vendor.js:46464:21
```

https://github.com/samselikoff/ember-cli-mirage/blob/0e0740a6c7844cbeb159a340924590554d1232ee/addon/get-rfc232-test-context.js#L9-L17

I suspect it might be because those lines in Mirage use `require` to check if `@ember/test-helpers` is a project dependency.

I have a reproduction of this on the mirage branch of my Embroider sandbox, here:
https://github.com/balinterdi/go-embroider-go/tree/mirage

(The test passes on the master branch, before adding Mirage)

**Comment by ef4** [comment]
Thanks for sharing the reproduction. I have been looking at this and I think I see the problem. This case used to work, but then got broken again by other changes in Embroider.

`@ember/test-helpers` stresses our module renaming capabilities to the limit, because it renames itself from its true NPM name (`@ember/test-helpers`) to its classic name (`ember-test-helpers`) but then it *also* emits a bunch of files under the `@ember/test-helpers` name. That all actually works! But only when consumed at build time via `import`. Mirage's runtime `require` doesn't work, but we can fix that.

(Also, even after I fix this, it won't work with Embroider's `staticAddonTestSupportTrees: true`, because that will cause `require.has('@ember/test-helpers')` to return false. There are workarounds for that too, until we can change mirage to use the macro system.)

**Comment by balinterdi** [comment]
Thank you. It's [@embroider/macros](https://github.com/embroider-build/embroider/blob/master/packages/macros/README.md) you refer to, right?

**Comment by ef4** [comment]
Yes, that would be the solution for how to fix this upstream in mirage. Though you should probably hold off until `@embroider/macros` is updated to match the current RFC.

The more temporary workaround is to use a compatAdapter to force `@ember/test-selectors` to be included as an `implicit-test-module`.

**Comment by ef4** [comment]
^ As of that change, your reproduction can run tests without the bug. It still fails to load webcrypto-jwt, but that's only because webcrypto-jwt isn't in package.json.

**Comment by balinterdi** [comment]
Thanks, Ed, it indeed works now.

**Comment by balinterdi** [comment]
Oh, I might have spoken too soon.

I think the error I hit is another one, though also related to Mirage and the static* options, so I'll write it up here (let me know if I should open another issue, though).

When I enabled `staticAddonTrees`, the auto-generation of Mirage models from ED models ceases to work. I have a User model in ED and when I run the tests, they fail with the following error:

> You called server.create('user') but no model or factory was found. Make sure you're passing in the singularized version of the model or factory name.

Interestingly, enabling `staticAddonTestSupportTrees` doesn't break Mirage in that way.

Manually generating a User model in Mirage (`ember g mirage-model user`) makes the test work again.

The reproduction is available at https://github.com/balinterdi/go-embroider-go/tree/mirage

**Comment by ef4** [comment]
Probably has something to do with:

https://github.com/samselikoff/ember-cli-mirage/blob/dcef77adced352d43d314ab484e47075018addb7/addon/utils/read-modules.js#L18-L25

or 

https://github.com/samselikoff/ember-cli-mirage/blob/dcef77adced352d43d314ab484e47075018addb7/addon/utils/ember-data.js#L5

The most static options are enabled, the fewer things will reliably appear in `requirejs.entries`.

**Comment by balinterdi** [comment]
How should these be handled?

In the first case, should the modules be added so that they are loaded explicitly in `read-modules`? Extending [the already existing `ember-cli-mirage` compat adapter](https://github.com/embroider-build/embroider/blob/master/packages/compat/src/compat-adapters/ember-cli-mirage.ts)?

In the second case, can we just say ember-cli-mirage (softly?) depends on ember-data? (though I think I've already seen some code that states this).

**Comment by balinterdi** [comment]
@ef4 I'd be willing to help with this but I need some guidance as to where to start and maybe prior examples I could use if there's any (see my previous questions). Thank you.

**Comment by ef4** [comment]
We need to extend the compat adapter for ember-cli-mirage. For each of the files that need to get discovered dynamically inside `requirejs.entries`, the compat adapter should add that file to  `implicit-modules`. There's a helper function called `forceIncludeModule` that does this, see https://github.com/embroider-build/embroider/blob/3755542b18fb9bf33cafd7f042d4e9415625da58/packages/compat/src/compat-adapters/ember-test-selectors.ts

This will work for the `./mirage/*` files inside the app as well as `ember-data` itself, which you can force include to satisfy the check in `_hasEmberData`.
