### ISSUE TITLE
Is there a way to fingerprint vendor.js?

### ISSUE THREAD

**Issue by kandhavivekraj** [embroider-build/embroider#289]
Is there a way to fingerprint vendor.js and other assets like images and css?

**Comment by ef4** [comment]
There should be but it's just not implemented yet. It will need to happen in stage3.

**Comment by lifeart** [comment]
I have crypto fingerprinting implementation in
https://github.com/lifeart/ember-cli-fallback-builds/blob/master/lib/utils/crypto.js#L4
and

@ef4 is any correct place to read final style/js output for hashing?

// is it possible (in current path) patch html output after hashing?

**Comment by ef4** [comment]
@lifeart it would go here:

https://github.com/embroider-build/embroider/blob/7b7be78744150e79de101ea3189898da9ee29688/packages/core/src/app.ts#L525-L551
