### ISSUE TITLE
Compiled CSS not updating in app

### ISSUE THREAD

**Issue by josemarluedke** [embroider-build/embroider#309]
In a nearly created Ember App using Ember CLI 3.13 beta and adding Embroider (v0.6.0), changing styles in the app.css file does not reflect in the running application.

In the reproduction below, changing the app.css will trigger a rebuild of the app, but the content of the compiled CSS file does not change. If I restart the app (kill ember s and re-run), it will have the changes applied.

Initially, I thought this was only for sass, but while creating the reproduction, I saw it was for plain CSS as well.

Reproduction: https://github.com/josemarluedke/--embroider-css-bug

**Comment by josemarluedke** [comment]
I have tried to figure out what's happening, but I wasn't able to find anything concrete.

I didn't find any code related to updating assets when files changes. 

There is this line for updating assets: 
https://github.com/embroider-build/embroider/blob/7071eeee02af0c48f56186c94094d41e7a41885a/packages/core/src/app.ts#L611
but the `appFiles ` passed in are coming from 
https://github.com/embroider-build/embroider/blob/7071eeee02af0c48f56186c94094d41e7a41885a/packages/core/src/app.ts#L607
which seems to filter just JS files.

Enabling logs I can see that the app differ didn't find any changes:

```embroider:debug app-differ operations count: 0 +20s```.

Anyway, would love some help to fix this issue.

**Comment by imkathir** [comment]
I've encountered this issue in my app as well

**Comment by josemarluedke** [comment]
This has been fixed in the recent PR #342.
