### ISSUE TITLE
Support Component Templates Co-location RFC

### ISSUE THREAD

**Issue by josemarluedke** [embroider-build/embroider#310]
The Ember [RFC #0481](https://emberjs.github.io/rfcs/0481-component-templates-co-location.html) has been accepted and it has been pretty much implemented in Ember already. 

Embroider should add support for it.

**Comment by knownasilya** [comment]
No movement on this?

**Comment by ef4** [comment]
This was closed in https://github.com/embroider-build/embroider/pull/379

**Comment by knownasilya** [comment]
Cc @gavinjoyce

**Comment by GavinJoyce** [comment]
Is it expected that code splitting should work with co-located templates (or components in general)? I tried here with static everything and embroider `0.19.0` and it seems that the component is included in the main bundle, not the route bundle as expected:

https://github.com/GavinJoyce/embroider-spike/pull/1
