### ISSUE TITLE
[Perf] loadGlimmerSyntax may be invoked many times

### ISSUE THREAD

**Issue by stefanpenner** [embroider-build/embroider#331]
I believe we may have noticed a perf issue:

If an app has many addons, and each of those addons have a templateCompiler, we may end up running loadGlimmerSyntax for each of them. In large apps, with engines, in-repo addons and external addons this can add up very quickly (tens of minutes).

Since `loadGlimmerSyntax` reads and transforms all of ember, this can be quite the costly endeavor.

One quick solution would be to memoize the `loadGlimmerSyntax` function, so that we only incur this cost once per templateCompilerPath. Since in general, there exists only 1 templateCompiler per build, this may dramatically cut down on build time.

pairing with @thoov / @tmquinn

**Comment by ef4** [comment]
This was not an accident. The template compiler is stateful, and we need separate configs for each addon.

But I do recall that @rwjblue mentioned there is an incantation that lets you reuse it without reloading it.

**Comment by stefanpenner** [comment]
@ef4 re-parsing/compiling the code though is in error, and also the problem. We can re-use the transformed source.
