### ISSUE TITLE
Cannot find module '...node_modules/broccoli-ember-hbs-template-compiler'

### ISSUE THREAD

**Issue by danwenzel** [embroider-build/embroider#347]
Got this error trying to `yarn start` with embroider:

```
Cannot find module '.../node_modules/broccoli-ember-hbs-template-compiler'
```

After some digging, it turned out to be the presence of [`ember-cli-stripejs`](https://github.com/layervault/ember-cli-stripejs), which uses very old versions of ember-cli dependencies. `broccoli-ember-hbs-template-compiler` itself is listed as a `devDependency` of that addon.

Pull this branch to see the issue: https://github.com/danwenzel/embroider-issues/tree/ember-cli-stripejs

I realize embroider probably doesn't support addons with ember cli dependencies this old, but do you think there could be a way to catch a better error for this?

**Comment by ef4** [comment]
Thanks for sharing a working reproduction.

**Comment by ef4** [comment]
This is now fixed on master.
