### ISSUE TITLE
Failing acceptance test in browser after adding Embroider (Ember 3.13.1)

### ISSUE THREAD

**Issue by skarger** [embroider-build/embroider#348]
### Summary
Acceptance tests fail in-browser after adding Embroider. A possible cause is that in the [`setup`](https://github.com/emberjs/ember.js/blob/master/packages/@ember/-internals/views/lib/system/event_dispatcher.js#L150) function in Ember's `event_dispatcher.js`, with a pre-Embroider app, `rootElement` is `div#ember-testing`. With Embroider, `rootElement` becomes `body`.

A demo Ember app that reproduces the problem is here: https://github.com/skarger/embroider-test

### Details
I set up an initial app as follows:
```
$ ember -v
ember-cli: 3.13.1
node: 12.11.1
os: darwin x64

$ ember new embroider-test --yarn

$ cd embroider-test

$ ember generate acceptance-test root

$ ember server
```

When visiting http://localhost:4200/tests in a browser, everything passes.

Then I added Embroider:
```
$ yarn add --dev @embroider/core @embroider/compat @embroider/webpack
```

Next I edited `ember-cli-build.js` as described on the Embroider README, and restarted the server.

When browsing again to http://localhost:4200/tests the acceptance tests fail.

Errors:

1. Promise rejected before "visiting /": Assertion Failed: You cannot make a new Ember.Application using a root element that is a descendent of an existing Ember.Application
2. Promise rejected during "visiting /": Cannot call `visit` without having first called `setupApplicationContext`.
3. Promise rejected after "visiting /": Cannot use 'in' operator to search for 'destroy' in undefined

**Note**: the reproduction above only works when testing in-browser. Running `ember test` at the command line will still all pass.

The first error above is thrown from the `setup` function in `event_dispatcher.js`:
https://github.com/emberjs/ember.js/blob/master/packages/@ember/-internals/views/lib/system/event_dispatcher.js#L150

With the pre-Embroider app, in the `setup` function `rootElement` is `div#ember-testing`.
With Embroider, `rootElement` becomes `body`.

Since that difference may well explain the errors above, my first question is whether it's intentional that the Embroider build changes the `rootElement`.

**Comment by ef4** [comment]
I think this is a duplicate of #113

It has always been someone convenient but accidental that you can run tests with `ember s` instead of `ember test`, and in fact it has some subtle problems (like you don't actually get a test build, you get a dev build).

**Comment by skarger** [comment]
@ef4 yes, looks the same as #113, closing.
