### ISSUE TITLE
ember-classic-decorator unintentionally detects problems in addons

### ISSUE THREAD

**Issue by maxwondercorn** [embroider-build/embroider#375]
First try using embroider and have run into a specific error with ember-bootstrap.

```shell
Uncaught Error: You attempted to use the .reopen() method on the Config class, but it's not a classic class! Redefining classes after they have been defined is generally considered an antipattern. If you were reopening this class to add static class fields or methods, you can now define those with the 'static' keyword instead.
```
The app is on ember v3.12 and has been converted to native classes. There a some classes that still require the @classic decorator.  ember-bootstrap is on 3.15 and has generally been converted to native classes.

The app builds without issue using the normal ember build.

The ember-bootstrap class that is causing the error is  [here](https://github.com/kaliber5/ember-bootstrap/blob/8bd7c203e57698d1a2b5a980050784d900fcb6dc/addon/config.js#L5)

**Comment by ef4** [comment]
I think this is not an issue with ember-bootstrap, it's an issue with ember-classic-decorator.

It seems that ember-classic-decorator uses a babel plugin to mark files as part of your app, because it only wants to emit warnings about your files and not your addon's files. 

Under embroider, that plugin also sees the addons files and so they can now generate the error.

**Comment by ef4** [comment]
Filed https://github.com/emberjs/ember-classic-decorator/issues/37 to ask about this.

**Comment by maxwondercorn** [comment]
I had other errors in addition to the bootstrap issue that might have been generated for the same reason. I can't verify the exact error message at the moment but they were about other addons.  

They were different from the bootstrap error  and when I get a chance I'll test again for those errors

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. 

How about closing this as *won't fix* and link to https://github.com/emberjs/ember-classic-decorator/issues/37#issuecomment-649776606?

**Comment by maxwondercorn** [comment]
I forget about this issue as I worked around it in my app. It can be closed and linked to decorator issue.

**Comment by sandstrom** [comment]
@maxwondercorn Feel free to close it (I can't, I'm not a maintainer).

**Comment by ef4** [comment]
This got solved in https://github.com/emberjs/ember-classic-decorator/pull/50
