### ISSUE TITLE
Issue with ember-collapsible-panel

### ISSUE THREAD

**Issue by thoov** [embroider-build/embroider#384]
Steps to repo:

1. Create a fresh ember app (`ember new embroider-test-app --yarn`)
2. Install embroider (via commands on embroider's README)
3. Install ember-collapsible-panel (`yarn add ember-collapsible-panel`)
4. Paste this code into application.hbs:

```hbs
<CpPanel @open={{true}} as |cp|>
  <cp.toggle>
      <p>Click me!</p>
  </cp.toggle>

  <cp.body>
    <div>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo repellendus nisi asperiores esse aperiam aliquid nulla ad dolor autem neque, nihil inventore temporibus delectus earum facere corporis, quam ipsum maxime.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus neque magnam, hic quis beatae repellendus harum modi pariatur minus quidem alias! Eius incidunt impedit eaque, est, illo officiis expedita molestiae.</p>
    </div>
  </cp.body>
</CpPanel>
```
5. Run ember serve

You will see the following error:

```
index.js:4964 Uncaught (in promise) TypeError: template$$1.asWrappedLayout is not a function
    at CurlyComponentManager.getDynamicLayout (index.js:4964)
    at Object.evaluate (runtime.js:1691)
    at AppendOpcodes.evaluate (runtime.js:73)
    at LowLevelVM.evaluateSyscall (runtime.js:3295)
    at LowLevelVM.evaluateInner (runtime.js:3241)
    at LowLevelVM.evaluateOuter (runtime.js:3233)
    at VM.next (runtime.js:5299)
    at TemplateIteratorImpl.next (runtime.js:5335)
    at RootState.render (index.js:5550)
    at runInAutotrackingTransaction (index.js:1039)
```

When running this app without embroider there is no error and the addon renders correctly.

**Comment by ef4** [comment]
Embroider now has support for template colocation, and according to that RFC `addon/components/cp-panel/template.hbs` means a template-only component named `<CpPanel::Template/>`. So when `addon/components/cp-panel/component.js` tries to import `./template`, it probably gets a full-blown component and not "just a template".

I'm curious how the normal non-embroider build resolves this ambiguity.

**Comment by ef4** [comment]
According to @rwjblue

> we specifically skip templates named template.hbs (due to "pods" conventions)

It is only "quote pods unquote" because addons can't actually rely on pods but they sometimes like the emulate the layout, like ember-collapsible-panel is doing here.
