### ISSUE TITLE
ModuleNotFoundError: Module not found: Error: Can't resolve 'qunit-dom'

### ISSUE THREAD

**Issue by raido** [embroider-build/embroider#386]
Just tried to follow instructions in README for one of my apps and addon. Both failed with qunit-dom error.

Addon is built with ember-cli-typescript, app just javascript.

**Comment by makepanic** [comment]
which version of qunit-dom are you using?

This might be a duplicate of https://github.com/embroider-build/embroider/issues/356 which was fixed in qunit-dom

**Comment by raido** [comment]
Yes, that is probably the case. Qunit-dom is definetly pre v1.0.
