### ISSUE TITLE
Imports not on default object with embroider

### ISSUE THREAD

**Issue by knownasilya** [embroider-build/embroider#391]
pre embroider this works:
```js
import git from 'isomorphic-git';

git.plugins.set('fs', fs);
```
But with it enabled I get:

<img width="631" alt="Screen Shot 2020-02-17 at 4 04 59 PM" src="https://user-images.githubusercontent.com/34726/74686355-45bebf00-519f-11ea-8e9e-2ac87cad66b8.png">

```
router.js:1214 Error while processing route: index Cannot read property 'plugins' of undefined TypeError: Cannot read property 'plugins' of undefined
```

Seems like I'd have to change to `import { plugins } from 'isomorphic-git';`

**Comment by ef4** [comment]
This is a case where ember-cli violates the ES module spec. It's supposed to be an error when someone confuses default and named exports, but ember-cli allows the ambiguity.

You can fix like this:

```diff
-import git from 'isomorphic-git';
+import * as git from 'isomorphic-git';
```

As this never takes more than four characters to fix the correct way, I'm not planning to make embroider support the broken ember-cli behavior.

**Comment by knownasilya** [comment]
Glad it's not a bug on this end
