### ISSUE TITLE
could not find app javascript in index.html

### ISSUE THREAD

**Issue by mschorsch** [embroider-build/embroider#395]
We have a use case where we don't want to specify the `rootUrl` in the files `environment.js` and `index.html`.

If `rootURL` is not defined (or empty) in file `environment.js` and/or `{{rootURL}}` is removed from the file `index.html`, we get the following build error:

```bash
$ ember build
Environment: development
⠸ building... [OneShot > Babel: ember-fetch > applyPatches]Building into /tmp/embroider/7f0a48
cleaning up...
Build Error (WaitForTrees)

could not find app javascript in index.html

Stack Trace and Error Report: /tmp/error.dump.c0bea05fb50d1d36f2cdd64a7659f68f.log
```

Do you have any idea how we can work around this problem?

**Comment by ef4** [comment]
Can you say more about why you don't want to specify `rootURL`? There always *is* one anyway, even if you don't say it here.

In general, using rootURL in index.html protects you from an otherwise easy-to-make mistake, which is that if you use non-root-relative URLs in index.html they appear at first to be working fine, but then when a user enters the app via a deep link the whole app is broken for them.

To get a more complete picture of what's happening in your build you can try adding breakpoints or console.log around here:

https://github.com/embroider-build/embroider/blob/0762082d6a94411aff2f931b9a6ac83d4a064f64/packages/compat/src/v1-app.ts#L672-L674

**Comment by mschorsch** [comment]
Hi @ef4 ,

thanks for your quick reply.

> Can you say more about why you don't want to specify rootURL?

Sure, our customer wants different version of our app under different URLs to compare this versions over time, but we have no (incomplete) control over the domain. Due to this restriction, we cannot create subdomains. Each version is therefore provided according to the schema `https://www.example.com/v[version]` (see example below). To make it working we removed the entry `rootURL` in `environment.js` and `{{rootURL}}` in `index.html`. 

__Example__
* https://www.example.com/v1.0.0
* https://www.example.com/v1.2.0
* https://www.example.com/v2.0.1
* ...

> There always is one anyway, even if you don't say it here.

> In general, using rootURL in index.html protects you from an otherwise easy-to-make mistake, which is that if you use non-root-relative URLs in index.html they appear at first to be working fine, but then when a user enters the app via a deep link the whole app is broken for them.

Can you elaborate more more on this? We are using this for a long time now and never encountered any problems. But we are eager to fix it.

**Comment by mschorsch** [comment]
`ember-cli` allows you to remove the `rootURL`, in such a case the url path will be normalized to an empty string (see https://github.com/ember-cli/ember-cli/blob/b05d47e3d9fd60d075cdfcc5afdb57a03421f3e4/lib/utilities/ember-app-utils.js#L16).

I think `embroider` should behave the same as `ember-cli`, right?

**Comment by nightire** [comment]
> in such a case the url path will be normalized to an empty string

I don't follow, `rootURL` is an empty string by default, why not just leave it here as it is?

**Comment by mschorsch** [comment]
> > in such a case the url path will be normalized to an empty string
> 
> I don't follow, `rootURL` is an empty string by default, why not just leave it here as it is?

You're right. I solved it by defining an empty rootURL and by fixing some additional bugs in our app.

So i think there ist no todo left for embroider.
