### ISSUE TITLE
Debug. vs. Prod builds

### ISSUE THREAD

**Issue by Turbo87** [embroider-build/embroider#4]
https://github.com/simplabs/ember-test-selectors is an example of an addon that does two entirely different things based on whether it is running in debug or in production mode. It is unclear to me at this point how an addon like that could be implemented using the proposed format.

**Comment by ef4** [comment]
I think everything ember-test-selectors does can be handled by build-time-config with dead branch elimination, in both JS and HBS.

The idea is to have a single, general-purpose babel plugin (and corresponding AST transform plugin) that addons can assume will always run during the final app build to strip unused branches, based on values emitting from the addon's own Node-side code (so they can decide when to flip the flags based on arbitrary logic).

**Comment by ef4** [comment]
I think the macro system as implemented can now handle all the use cases in ember-test-selectors. 

For example, this:

```hbs
<div data-test-foo=1 />
```

can be compiled by ember-test-selectors' own AST transform into:

```hbs
<div {{macroMaybeAttr (macroGetConfig "ember-test-selectors" "enabled") data-test-foo=1 />
```

We can open more specific issues if we find gaps.
