### ISSUE TITLE
Transpiling Stage 3 Features

### ISSUE THREAD

**Issue by alexlafroscia** [embroider-build/embroider#405]
We're currently using the [nullish coalescing](https://2ality.com/2019/08/nullish-coalescing.html) feature through `@babel/preset-env`. We don't have this explicitly provided anywhere -- it just works "automatically".

Unfortunately, when swapping in Embroider, the build chokes on that syntax

```
Build Error (PackagerRunner) in components/email-preview/user-sampling/component.js:116

Module parse failed: Unexpected token (116:31)
You may need an appropriate loader to handle this file type.
|     this._super(...arguments);
|
>     this.sample = this.sample ?? [];
|     this.setPreviewID();
|     this.getBehaviorURL();
```

**Comment by ef4** [comment]
I think this is just a question of making sure we have a new enough `@babel/parser`. It's probably already fixed on master due to bd613567870ead54797f124d89dff747819031ca.

**Comment by alexlafroscia** [comment]
Oh okay, awesome! I'll keep my eyes peeled for the next release of Embroider then.

**Comment by ef4** [comment]
Oops, that PR isn't merged yet: https://github.com/embroider-build/embroider/pull/400

But yes, I think that will fix this.

**Comment by kturney** [comment]
FWIW, I am still seeing errors using nullish coalescing using v0.15.0, which, from my understanding, is supposed to have the babel fix.
