### ISSUE TITLE
Always provide the `runningTests` variable

### ISSUE THREAD

**Issue by ef4** [embroider-build/embroider#408]
For compatibility with classic builds, the global variable `runningTests` should always be defined (even when it's defined but false). 

This is easy to fix in embroider, we already have a block of code we inject to replace the classic vendor prefix, it just goes in there.

We can also leverage #407 to make it actually reflect the true state of testings vs not-tests in a way that ember-cli doesn't.

**Comment by Turbo87** [comment]
@ef4 is this a bug in a newer release? I'm currently trying to make an app work with v0.13 and on app startup it complains that `runningTests` is not defined 🤔

**Comment by ef4** [comment]
This is still a current bug. Most apps don't notice unless they try to use ember-cli-fastboot, which substitutes its own boot logic that tries to read this variable. Probably there are other addons also that try to read this variable and fail.

If you want to help with a fix, it can go [here](https://github.com/embroider-build/embroider/blob/ff31a8ad06953de43237d22b015aad79c2120961/packages/core/src/app.ts#L309-L313). The same way we're appending an in-memory asset that just contains a string of ember environment stuff, we can append an in-memory asset that just contains the string `runningTests=false;`.

**Comment by Turbo87** [comment]
```js
      result.unshift({
        kind: 'in-memory',
        relativePath: '_testing_prefix_.js',
        source: `runningTests=false;`,
      });
```

like that? unconditionally, or should it be guarded by anything?

**Comment by ef4** [comment]
It can go within the same condition as the _ember_env_ one.

When tests are actually running, they will overwrite the variable, I’m
pretty sure they come later. That’s how this works in the traditional
build.

**Comment by Turbo87** [comment]
is there a somewhat straight forward way to write a regression test for this?
