### ISSUE TITLE
Tracking issue for fastboot manifest handling

### ISSUE THREAD

**Issue by ef4** [embroider-build/embroider#409]
When our stage3 bundler optimizes and rewrites the app, it's free to split and rename javascript bundles so long as it preserves standards-compliant behavior. We deliberately do not constraint the bundling strategy, so that even future tools with different optimizations are a drop-in possibility. 

This all works great because all the HTML, JS, and CSS we pass to stage3 follows public web standards.

But the fastboot manifest is not a standard and no tool understands how to rewrite it. This breaks fastboot.

The solution I'm implementing here is to make fastboot no longer need a non-web-standards manifest at all. The HTML contains all the same information, and in a standards-defined way. Where we need fastboot-only scripts, they can be guarded by the macro system rather than special-cased within the stage3 bundler.

There is [open work in ember-cli-fastboot](https://github.com/ember-fastboot/ember-cli-fastboot/pull/753) to implement that strategy, but it still relies on mangling the build output after stage3 runs, which is fragile and puts constraints on our architecture. Instead I want to move that work into the `fastboot` package itself, so no build mangling is needed. It would function the same -- when reading the app's manifest, fastboot would read it from HTML instead of package.json.

**Comment by simonihmig** [comment]
I believe this can be closed?
