### ISSUE TITLE
Error: Could not find module `json5` imported from `(require)`

### ISSUE THREAD

**Issue by sdhull** [embroider-build/embroider#413]
Hi! 👋 thanks for all your work on embroider, it's -vv cool

I apologize in advance, my knowledge of build systems is limited. I've been playing with a new app and using embroider, so far everything's been going smoothly.

Then I tried to add [json5](https://github.com/json5/json5) to the project, and it won't import. I get the following error in console:
```
Error: Could not find module `json5` imported from `(require)`
```
At first I wasn't sure if the problem was `ember-auto-import` or embroider, but after cmd-f'ing through all the `chunk.js` files & `vendor.js`, I've determined that the `json5` is nowhere in the package, so must be embroider, right? (Actually I did find `eval("const m = window.require(\"json5\")...` in one but it seems like this is added for any package that can't be found?)

I'm confident that there's some option I can use to fix this but I'm not sure how to go about figuring out what that option is. [The option docs](https://github.com/embroider-build/embroider/blob/master/packages/compat/src/options.ts) are kind of opaque and seem aimed specifically at ember-addons, but I bet there's something there that could help me, I'm just not sure what.

I would very much appreciate if someone could help point me in the right direction. 🙏

**Comment by ef4** [comment]
First, double-check that you definitely have both ember-auto-import and json5 in your app's `devDependencies`. Under embroider, ember-auto-import is still required as your opt-in to enable importing from NPM, even though the actual implementation is that embroider itself handles that.

Second, I would suggest trying a non-embroider build and seeing if just ember-auto-import by itself can bring in that dependency. Switching from embroider back to a standard build should be as simple as returning `app.toTree()` from your ember-cli-build.js file. If it works without embroider, that will narrow down the problem.

**Comment by sdhull** [comment]
Hi @ef4! Thanks for your response! It does indeed work by going back to the standard build with `app.toTree()`

**Comment by sdhull** [comment]
Is there some way to simply white list the module so it gets included in its entirety?

**Comment by ef4** [comment]
I just tried adding json5 to a newly generated app under both embroider and auto-import and it worked in both cases. What embroider release are you using? Where in your app's code did you try to import json5?

**Comment by sdhull** [comment]
I seem to have both `@embroider/core@0.4.3` and `@embroider/core@0.13.0` in my yarn.lock file... 🤔

```
yarn why @embroider/core
yarn why v1.22.4
[1/4] 🤔  Why do we have the module "@embroider/core"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@embroider/core@0.13.0"
info Has been hoisted to "@embroider/core"
info Reasons this module exists
   - Specified in "devDependencies"
   - Hoisted from "@embroider#macros#@embroider#core"
info Disk size without dependencies: "3.76MB"
info Disk size with unique dependencies: "28.85MB"
info Disk size with transitive dependencies: "78.41MB"
info Number of shared dependencies: 130
=> Found "ember-auto-import#@embroider/core@0.4.3"
info Reasons this module exists
   - "ember-auto-import" depends on it
   - Hoisted from "ember-auto-import#@embroider#core#@embroider#macros#@embroider#core"
```

I'm on Ember 3.15 but will be upgrading to 3.17 tonight probably.

**Comment by sdhull** [comment]
Oh and I'm importing `json5` in a glimmer component

**Comment by ef4** [comment]
(The extra copy of `@embroider/core` is there just because ember-auto-import has a dependency on it in order to share some utilities.)

I can't reproduce this problem, I'm able to import and use json5 from a glimmer component using ember-source 3.15, ember-cli 3.15, and embroider/* 0.13.0.
