### ISSUE TITLE
Support in-repo addons inside addons

### ISSUE THREAD

**Issue by ef4** [embroider-build/embroider#428]
Right now they're supported inside the app, but not inside addons.

This came up first in the context of engines, which are addons that are more likely to use in-repo addons. But I think they're technically allowed inside *any* addon, not just an engine.

**Comment by mehulkar** [comment]
Some related conversation here that seems worth cross linking https://github.com/ember-cli/ember-cli/issues/9016

**Comment by ef4** [comment]
Sketch of where to fix: https://github.com/embroider-build/embroider/tree/in-repo-addon-in-addon

**Comment by thoov** [comment]
I am working on this
