### ISSUE TITLE
v1-legacy needs treeFor caching

### ISSUE THREAD

**Issue by stefanpenner** [embroider-build/embroider#43]
invokeOriginalTreeFor

https://github.com/ember-cli/ember-cli/blob/3697ad826efa4312fc30bec27cc4d8ff97c53b5c/lib/models/addon.js#L635
https://github.com/ember-cli/calculate-cache-key-for-tree

This is a placeholder issue, that I need to flesh out yet. (don't want us to forget)

**Comment by ef4** [comment]
This was implemented in #105
