### ISSUE TITLE
Include tests from engines in the main app's test suite

### ISSUE THREAD

**Issue by thoov** [embroider-build/embroider#430]
Investigate the testing behavior of engines

**Comment by thoov** [comment]
@ef4:

I'm not sure this is needed as the default behavior is to not include tests with the parent. From ember-engines documentation (https://ember-engines.com/docs/testing-intro):

> Just like other addons, engines must be tested differently depending upon whether they are 
> "in-repo" or "standalone":
>
> To test an in-repo engine, co-locate the engine's tests with the host app's tests, just like any 
> other in-repo addon.
>
> To test a standalone engine, use the dummy app, just like any other standalone addon project.

Additionally, the `includeTestsInHost` property that you mentioned is coming from this addon: https://github.com/sangm/ember-add-in-repo-tests. Which isn't directly related to engines but in-repo addons.

**Comment by ef4** [comment]
Ok, thanks for investigating. I think we can close this then.
