### ISSUE TITLE
production build tries to include unimported file?

### ISSUE THREAD

**Issue by NullVoxPopuli** [embroider-build/embroider#438]
I've been co-locating page objects with components.
Why would it want to include this in the build?

here is my current embroider config:
```ts
    return compatBuild(app, Webpack, {
      extraPublicTrees: additionalTrees,
      // staticAddonTestSupportTrees: true,
      // staticAddonTrees: true,
      // staticHelpers: true,
      // staticComponents: true,
      // splitAtRoutes: true,
      // skipBabel: [],
    });
```

![image](https://user-images.githubusercontent.com/199018/80534775-cc490700-896d-11ea-9cfe-79199ef0059b.png)

**Comment by ef4** [comment]
You have `staticComponents: true` commented out, so you have `staticComponents: false`, so embroider will import and define every component in your app, and `app/components/modal/-page.ts` is a valid path for a component.

**Comment by NullVoxPopuli** [comment]
oh neat. thanks!
