### ISSUE TITLE
Can't find component when staticComponents is true and component is normal AngleBracket invocation?

### ISSUE THREAD

**Issue by NullVoxPopuli** [embroider-build/embroider#439]
Error in the bottom right, not sure how it can't find the component?
Is it maybe something weird with the `App` prefix? idk

![image](https://user-images.githubusercontent.com/199018/80541529-4632bd80-8979-11ea-9ea2-b98e06801261.png)

**Comment by ef4** [comment]
I think the problem here is that we don't support the convention of naming the component index.js. I think it is a small fix in the compat resolver.

**Comment by NullVoxPopuli** [comment]
Confirmed resolved by: https://github.com/embroider-build/embroider/pull/441
(my build actually completed after this change) o.o

**Comment by ef4** [comment]
Closed by #441.
