### ISSUE TITLE
Should Embroider passthrough script attributes?

### ISSUE THREAD

**Issue by bobisjan** [embroider-build/embroider#456]
Hi,

should Embroider passthrough the HTML attributes like `defer` on scripts from `app/index.html` into `dist/index.html` for `ember build --environment=production`?

```html
<!-- app/index.html -->
<script src="{{rootURL}}assets/vendor.js" defer></script>
<script src="{{rootURL}}assets/embroider-playground.js" defer></script>

<!-- dist/index.html -->
<script src="/assets/vendor.js"></script>
<script src="/assets/chunk.c1fdfc6b793b9d023c96.js"></script>
<script src="/assets/chunk.4aecffffbd029f26d4de.js"></script>
```

Thanks ☺️

---

Just for curiosity why the `assets/embroider-playground.js` is split into two chunks by default?

**Comment by ef4** [comment]
In general, yes, we should leave attributes like `defer` alone.

However, I don't think that actually works reliably in Ember apps in general, with or without embroider. `vendor.js` *must* execute before the app, and if you defer both there is a chance that the app will lose the race.

> Just for curiosity why the assets/embroider-playground.js is split into two chunks by default?

Webpack's default settings put things from `node_modules` in a separate chunk from your own project. It's the same reason Ember traditionally splits things into vendor.js and app.js -- the third-party deps are theoretically more slowly changing and can get better cacheability.

Under embroider, we will have some legacy things in vendor.js, but much of what was in there has moved into the node_modules chunk.

**Comment by bobisjan** [comment]
@ef4, thanks for the explanation 👍

> However, I don't think that actually works reliably in Ember apps in general, with or without embroider. vendor.js must execute before the app, and if you defer both there is a chance that the app will lose the race.

This makes me worried 🙈, where does this come from? I live with the following statement

> Scripts with the defer attribute will execute in the order in which they appear in the document.

from https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script.

**Comment by ef4** [comment]
Oops, never mind me, I was mixed up with `async`.

**Comment by rahulk94** [comment]
Hey team any updates on this? I'm trying to set `type="module"` attributes on our application scripts so we can avoid loading them on IE but they're not propagating through. At this point I'm having difficulty figuring out whether this is an embroider issue or ember-auto-import.

**Comment by lifeart** [comment]
Hi @rahulk94! I think only tests is missing in original PR to move it forward
