### ISSUE TITLE
Lazy asset chunk loading fails with CDN'd assets

### ISSUE THREAD

**Issue by thoov** [embroider-build/embroider#467]
When using lazy engines (and presumably other lazy forms) and a CDN services that rewrites the name of these assets, webpack will fail to load the chunks as they don't exist.

The error is:

```
ChunkLoadError: Loading chunk 2 failed. (error: https://www.example.com/app_name/assets/chunk.bd98137b74ee200829c3.js)
```

Where that actual asset could be something like: 

```
https://www.cdn.com/hash/abc.js
```

**Comment by ef4** [comment]
Right, we can't let assets get rewritten arbitrary outside the build. Instead we should work on a way for you to get the assets named correctly within the stage3 packager.

For webpack, [output.chunkFilename](https://webpack.js.org/configuration/output/#outputchunkfilename) and [output.filename](https://webpack.js.org/configuration/output/#outputfilename) both accept arbitrary functions, which can hopefully see enough information to do the right naming.

**Comment by thoov** [comment]
@ef4 Would that give us access to the content of the underlining asset? Meaning that the name of the asset is going to be `<some_constant_prefix>/<custom_hash_of_the_contents_of_the_file>`

**Comment by ef4** [comment]
I went to check on this and it seems that for lazy chunks (`output.chunkFileName`) they don't actually support a function. It only works for entry chunks (`output.filename`). I think the reason is that for lazy chunks the paths actually get evaluated at runtime.

You may need to patch webpack with a custom hashing function, so you can set the name to `[hash].js` and get the one you wanted.

**Comment by ef4** [comment]
It seems there are examples of webpack plugins that customize the hash: https://github.com/erm0l0v/webpack-md5-hash/blob/master/plugin/webpack_md5_hash.js

**Comment by ef4** [comment]
The original work that triggered this issue was resolve quite a while back.
