### ISSUE TITLE
Components don't seem to be split into route bundles

### ISSUE THREAD

**Issue by GavinJoyce** [embroider-build/embroider#470]
I'm trying out embroider at https://github.com/GavinJoyce/embroider-spike (things are going pretty well, I'm very excited).

Perhaps I'm missing something, but I can't seem to get components to split into their appropriate route bundles. Helpers seem to be splitting just fine.

Here's a [PR where I enable `splitAtRoutes`](https://github.com/GavinJoyce/embroider-spike/pull/1). The `player` helper splits correctly, but the `<Player />` component does not.

Here's my config:

[`ember-cli-build.js`](https://github.com/GavinJoyce/embroider-spike/blob/6841433183b89e8b4178cb9640625281eb5f9cae/ember-cli-build.js):

```js
return require("@embroider/compat").compatBuild(app, Webpack, {
  staticAddonTestSupportTrees: true,
  staticAddonTrees: true,
  staticHelpers: true,
  staticComponents: true,
  packagerOptions: {
    webpackConfig: {},
  },
  splitAtRoutes: ["teams", "players", "table"],
});
```

Here's a gif showing that the `<Player>` component is present in the main app bundle:

![embroider-loading](https://user-images.githubusercontent.com/2526/84034285-0c9a9c80-a992-11ea-8e3f-b05406df4977.gif)

**Comment by ef4** [comment]
I think this is fixed by #594.

**Comment by GavinJoyce** [comment]
I'm trying to verify your fix, but I still seem to be seeing the same behaviour:

https://github.com/GavinJoyce/embroider-spike/pull/31

**Comment by ef4** [comment]
As I commented on that issue, I think this is working correctly, but the presence of translations in the main bundle was making it look like it wasn't.

**Comment by GavinJoyce** [comment]
Ah, thanks - I missed that detail. I'll take a second look now and verify that everything is working as expected
