### ISSUE TITLE
How to use macros to exclude files/folders from build

### ISSUE THREAD

**Issue by mydea** [embroider-build/embroider#474]
I have been going through our application/addons, trying to play around with @embroider/macros.
I read through the [RFC](https://github.com/emberjs/rfcs/blob/master/text/0507-embroider-v2-package-format.md) and the comments there, and searched through the issues/code here a bit, and stumbled over this:

> v1 packages can run arbitrary Node code that completely alters their runtime code. This makes them impossible to analyze. v2 packages are not allowed to do this. There are no "treeFor*" hooks. Instead, they can influence their runtime code only through the macro system.

Now concretely, I have an addon where I allow to configure if read and/or writing of analytics data should be enabled. I want to avoid including all the files used for reading the data in builds that only support writing it. The addon's index.js looks like this (slightly simplified):

```js
module.exports = {
  name: require('./package').name,

  included() {
    let env = process.env.EMBER_ENV;

    let config = this.project.config(env).analytics || {};

    this.includeRead = config.includeRead !== false;
    this.includeWrite = config.includeWrite !== false;

    this._super.included.apply(this, arguments);
  },

  treeFor() {
    let tree = this._super.treeFor.apply(this, arguments);

    let { includeRead, includeWrite } = this;

    let exclude = [];

    if (!includeRead) {
      exclude.push('**/analytics-read.js');
      exclude.push('**/gql/queries/**');
    }

    if (!includeWrite) {
      exclude.push('**/analytics-write.js');
      exclude.push('**/gql/mutations/**');
    }

    return funnel(tree, {
      exclude,
    });
  }
}
```

How would something like this work with the macros? I am not sure where I would use `macroCondition` to actually exclude certain files from the build? Or is this simply not possible (yet) with macros only?

**Comment by ef4** [comment]
The only reason "excluding files from the build" is even a thing in the traditional build is that the build doesn't respect module imports.

A v2-formatted addon "excludes" things simply by not importing them, and then they won't be included. So you could use the macro system to `setOwnConfig` with `{ includeRead: true, includeWrite: false }` from the node side, and then in your code:

```js
import { macroCondition, getOwnConfig, importSync } from '@embroider/macros';
let reader, writer;
if (macroCondition(getOwnConfig().includeRead)) {
  reader = importSync('./the-reading-code');
}
if (macroCondition(getOwnConfig().includeWrite)) {
  writer = importSync('./the-writing-code');
}
export { reader, writer };
```

At the moment I am working on the tooling that will make it possible to ship a v2 addon that works in a stock, non-embroider ember-cli. Practically, that's what you need to take advantage of this pattern in an existing addon.

Depending on how people consume your addon, there may be an even simpler way to include only the reading or writing feature: if those features are directly importable by the app, then you wouldn't need to do anything special with the macro system at all. The app will either import the feature (so it will be included) or it won't (so it won't).

**Comment by mydea** [comment]
OK, got it - so _for now_ this is not possible to do with macros only, but eventually it will. Thanks for the clarification! I will close this :+1:
