### ISSUE TITLE
when using ember-decorators ember-data becomes mandetory

### ISSUE THREAD

**Issue by stefanpenner** [embroider-build/embroider#48]
I realize this was done intentionally:
https://github.com/embroider-build/embroider/blob/master/packages/compat/src/compat-adapters/ember-decorators.ts#L8

But, I believe ember-decorators ember-data stuff is currently pay-as-you-go, but with embroider it becomes mandetory. Likely a path forward for ember-decorators that does not enforce ember-data is required.

(this was fun to debug, i couldn't figure out how ember-data was becoming a peerDependency)

**Comment by stefanpenner** [comment]
What lead me here was the following error:

```
Build Error (OneShot)

Build Canceled: Broccoli Builder ran into an error with `RewritePackageJSON` plugin. 💥
Cannot find module 'ember-data/package.json' from '/Users/spenner/l/pemberly-example-web_trunk/node_modules/ember-decorators'
```

**Comment by ef4** [comment]
Yeah, sorry about that, some of these adapters are very blunt and date to when I was just trying to get the first end-to-end builds to succeed.

I think the latest versions of ember-decorators may have addressed this upstream anyway. The ember-data decorators are in their own `@ember-decorators/data` addon, which can be added and removed independently of the others.

Also, even if this kind of compat adapter is still needed we could do it better now using the macro system, by wrapping the offending module in `macroIf(dependencySatisfies('ember-data', '*'), ...)`.

I think this problem also solves itself when the `staticAddonTrees` optimization is enabled. With that flag, we won't traverse into the modules in ember-decorators that depend on ember-data unless your app explicitly depends on them. It makes everything necessarily paygo.

As a workaround, you can disable the built-in compat adapter by setting

```js
require('@embroider/compat').compatBuild(app, Webpack, {
  compatAdapters: new Map([['ember-decorators', null]])
});
```

**Comment by stefanpenner** [comment]
> Yeah, sorry about that, some of these adapters are very blunt and date to when I was just trying to get the first end-to-end builds to succeed.

It was a fun debugging, thanks for leaving me the treasure hunt ;)

**Comment by stefanpenner** [comment]
> As a workaround, you can disable the built-in compat adapter by setting

Awesome thanks, I was just commenting out the code in embroider, but this will be more sustainable.

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? If it isn't, maybe we can close this issue?

By closing some old issues we reduce the list of open issues to a more manageable set.

Since ember-decorators was an exploratory package, and most of it was upstreamed into Ember, maybe this isn't as relevant today.
