### ISSUE TITLE
Sample ember app with embroider

### ISSUE THREAD

**Issue by abhilashlr** [embroider-build/embroider#488]
I followed a step by step guide to enable embroider on a new app created using `ember new sample-app`. And proceeded with a step by step addition of Embroider. For a dev build, I see the sample welcome page work! and great work @ef4 - I'm super excited 👍 

While I ran the same server with a `--prod` flag, I receive an error on the console 
```
Missing component WelcomePage in .../templates/application.hbs
```
This happens only when I enable the --prod flag. Here's the `ember-cli-build.js` config

```js
  return require('@embroider/compat').compatBuild(app, Webpack, {
    staticAddonTestSupportTrees: true,
    staticAddonTrees: true,
    staticHelpers: true,
    staticComponents: true, // Disabling this also didn't seem to work.
  });
```

**Comment by nightire** [comment]
If you look over the `index.js` of https://github.com/ember-cli/ember-welcome-page:

https://github.com/ember-cli/ember-welcome-page/blob/master/index.js

you will know that ember-welcome-page strips itself in the production environment, so it's expected behavior and has nothing to do with embroider in my opinion.

**Comment by abhilashlr** [comment]
> If you look over the `index.js` of https://github.com/ember-cli/ember-welcome-page:
> 
> https://github.com/ember-cli/ember-welcome-page/blob/master/index.js
> 
> you will know that ember-welcome-page strips itself in the production environment, so it's expected behavior and has nothing to do with embroider in my opinion.

Ah! Didn't realise! Thanks 👍
