### ISSUE TITLE
How to support tests with dynamic component registration?

### ISSUE THREAD

**Issue by simonihmig** [embroider-build/embroider#522]
As suggested in the [Addon Guides](https://github.com/embroider-build/embroider/blob/master/ADDON-AUTHOR-GUIDE.md) addons should run its test suite with embroider, and if possible with optimized settings (i.e. `staticComponents: true`).

There is one problem though, when tests dynamically register components/helpers, like `this.owner.register('component:test-component', TestComponent);`. This is a quite common pattern in more advanced tests, which is even present in this repo in various places (e.g. [here](https://github.com/embroider-build/embroider/blob/d4eb675f9a35efc75217e2426035763e7afde1b3/test-packages/macro-sample-addon/tests/integration/helpers/reflect-updated-config-test.js)). With optimized settings this causes a build error: `Missing component or helper test-component`.

Any suggestion how this could be solved? 

As the dynamically registered components/helpers are present in the test module anyway, tree-shaking does not really apply. So the build-time assertions seems a bit too cautious, as AFAICT without that assertion the test should still work just fine, right?

Can we somehow declare components to be excluded from that check? Or should Embroider get smarter, in that it does not apply that check for components used in test files? Or even be super-smart by understanding what effect `this.owner.register()` has? 🤔

**Comment by simonihmig** [comment]
> Can we somehow declare components to be excluded from that check?

Ok, we can. Just learned a bit about these package rules, which allow this:

```
packageRules: [
  {
    package: 'dummy',
    components: {
      '{{test-component}}': {
        safeToIgnore: true,
      },
    },
  },
],
```

If that's the suggested (interim?) solution for now, we should at least add some better documentation, as this was not really obvious!

**Comment by ef4** [comment]
I think that's an OK interim solution.

This is an area where the correct solution is needed in Ember itself, not Embroider. I want you to be able to say:

```js
test('invoke a component', async function(assert) {
  this.set('myComponent', class extends Component {});
  await render(hbs`<this.myComponent />`)
});
```

That doesn't work today because component definitions and component classes are different things. This necessarily needs to get fixed to make strict mode templates work, and people are already working on it.

The tracking issue for this kind of thing in embroider is https://github.com/embroider-build/embroider/issues/487.

**Comment by esbanarango** [comment]
is there any official/suggested solution for this? 🙏

**Comment by NullVoxPopuli** [comment]
@esbanarango does `this.setProperties({ MyComponent })` work for you? as in this comment: https://github.com/embroider-build/embroider/issues/522#issuecomment-794253469

**Comment by esbanarango** [comment]
@NullVoxPopuli  no, I have a slightly different need for `this.owner.register('component:test-component', TestComponent);`. I basically need to stub some properties or methods from the _Component_ class.

Example:

```ts
// This is no longer a valid/normal Class as Embroider has made it "statically analyzable"
import MyComponent from 'my-app/components/my-component';

module('Integration | Component | my-component', function (hooks) {
  setupRenderingTest(hooks);

  test('...', async function (assert) {
    this.owner.register(
      'component:my-component',
      class extends MyComponent {
        // Propertier and methods I want to override
      }
    );

    await render(hbs`<MyComponent />`);
  });
});
```
When exporting: `import MyComponent from 'my-app/components/my-component';`, `MyComponent` is no longer a Class, but a different "object", so we can't not "extend" it anymore.

Error:

```
stack: >
    TypeError: Class extends value owner => {
          if (parsedBlock === undefined) {
            parsedBlock = JSON.parse(block);
          }
          if (ow...<omitted>... } is not a constructor or null
        at Object.eval (webpack:
```

**Comment by ef4** [comment]
That seems like a bug. It should still be a class if it was one before.

**Comment by esbanarango** [comment]
https://github.com/embroider-build/embroider/issues/1341

**Comment by esbanarango** [comment]
Separated issue created: https://github.com/embroider-build/embroider/issues/1341

**Comment by ef4** [comment]
Closing this because `render` from `@ember/test-helpers` accepts components and has for quite a while.
