### ISSUE TITLE
Support for disabled in-repo addons

### ISSUE THREAD

**Issue by mehulkar** [embroider-build/embroider#568]
If you ave an in-repo addon that sets `isEnabled() { return false }`, Embroider fails on a somewhat innocuous line of code:

https://github.com/embroider-build/embroider/blob/c4b20e5a0ee16f1c23b7f0c3baf5eaf42780214f/packages/compat/src/compat-addons.ts#L172

Debugging a bit, it looks like the addon is made available in the tmp directory, but its `package.json` file has an empty json object in it `{}`, causing the `path.join` to fail with:

```js
Build Error (WaitForTrees)

The "path" argument must be of type string. Received type undefined
```

**Comment by mehulkar** [comment]
Haven't tried if this also reproduces for external addons.

**Comment by iamareebjamal** [comment]
Receiving the same error which I think is same as #302

**Comment by mehulkar** [comment]
Looks very similar, thanks! The only difference is that #302 is repro'ing with the `blacklist` feature of Ember CLI, whereas this is with the `isEnabled()` hook. 

Which makes me thing the fix is actually for ember-cli or even broccoli to exclude folders of addons that aren't going to get built. @rwjblue @stefanpenner do you have any immediate thoughts? Or can you confirm my understanding?
