### ISSUE TITLE
Support direct `this._super` calls in treeFor

### ISSUE THREAD

**Issue by ef4** [embroider-build/embroider#569]
We try to infer whether `treeFor` is passing out the value returned by its super method unchanged, but right now we only support `this._super.treeFor()` and not `this._super()`, when apparently core-object supports both.

See https://github.com/embroider-build/embroider/pull/566#discussion_r504863610

While doing this, we should probably wrap the entire invocation of the custom `treeFor` in a catch block, because the whole thing is very "best-effort". In the most general case we can't make these methods see exactly what they would have seen in a classic build, we're really just looking for the most common two special cases (returning null or returning the super implementation unchanged).

**Comment by ef4** [comment]
The core-object implementation is here https://github.com/ember-cli/core-object/blob/480c831a19935860b0786307a94edba48adf3044/lib/assign-properties.js#L15-L35

**Comment by rwjblue** [comment]
> apparently core-object supports both

😭
