### ISSUE TITLE
Tree Shaking test cases

### ISSUE THREAD

**Issue by stefanpenner** [embroider-build/embroider#58]
@eldeffo on twitter raised some good examples: https://twitter.com/eldeffo/status/1105989202653728769

The current plan of record should handle the use-cases he described, but I wanted to open an issue so we can ensure we explicitly test these scenarios.

- [ ] https://github.com/kaliber5/ember-bootstrap (for example all the components/helpers etc https://github.com/kaliber5/ember-bootstrap/tree/master/addon/components/base)
- [ ] https://github.com/shipshapecode/ember-math-helpers (only pull in helpers we use)
- [ ] https://github.com/miguelcobain/ember-paper (for example the addon/components/*)
- [ ] more...

**Comment by ef4** [comment]
People who are interested should check out the options that are already implemented. In particular, if you turn on `staticAddonTrees`, `staticHelpers`, and `staticComponents`, all unused helpers and components from both the app and all addons shake out.

Turning "on" these features is really just turning *off* our extra compatibility code that simulates `import` of all the things that ember-cli would normally include. "Tree shaking" is not really a feature you can find in the code, it's just what emerges naturally from the architecture.

**Comment by villander** [comment]
@ef4 we need to document this, do you have any action plan to start documenting the stable things of embroider?

**Comment by Turbo87** [comment]
@villander there are no "stable things" yet. embroider is an experiment that looks quite promising, but it is not "stable" yet. I agree that these things should be documented properly though.

**Comment by villander** [comment]
Yes, I am aware that it is not stable. And the willingness to help document and develop. I look forward to seeing this stable; )

**Comment by ef4** [comment]
We have a lot of test coverage of this feature now. As for documenting, all the options that control it have extension comments. See https://github.com/embroider-build/embroider/blob/master/packages/core/src/options.ts and https://github.com/embroider-build/embroider/blob/master/packages/compat/src/options.ts

**Comment by villander** [comment]
sure, I’ll document this, thanks @ef4
