### ISSUE TITLE
issues using ember-cli-inline-content

### ISSUE THREAD

**Issue by stefanpenner** [embroider-build/embroider#59]
speaking to @turbo87, he mentioned issues using this add-on: ember-cli-inline-content. So I am posting it here, so we don't forget to identify/fix the issue

**Comment by ef4** [comment]
Maybe not exactly the same bug, but that addon does a thing here:

https://github.com/gpoitch/ember-cli-inline-content/blob/64d60961d0192b9826b980f3d0645249809cc6ca/index.js#L24

that is problematic. It's overwriting its own `this.options` with the *app's* options. So then when we go to do things like alter its babel config, we're actually altering the app's babel config.

**Comment by Turbo87** [comment]
I assume this has been fixed by #66. If I hit this again I'll reopen the issue.
