### ISSUE TITLE
Multiple versions of `@embroider/macros` may conflict at runtime in classic builds

### ISSUE THREAD

**Issue by rwjblue** [embroider-build/embroider#592]
When multiple versions of `@embrodier/macros` co-exist at runtime (in non-Embroider builds) the `@embroider/macros/runtime` module will **not** be guaranteed to be the one that the babel plugin (which injects the import statement) expects. Specifically, this is because the ember-cli build pipeline merges multiple versions of addons down in such a way that it is quite confusing to reason about which one "wins", but it is very likely to be the "wrong one" for at least one consumer.

Specifically, if this code runs:

https://github.com/embroider-build/embroider/blob/45f2a7c590b5b725aa4535a1a3f2c3e718491199/packages/macros/src/babel/macros-babel-plugin.ts#L222-L233

It will always default to `@embroider/macros/runtime`:

https://github.com/embroider-build/embroider/blob/45f2a7c590b5b725aa4535a1a3f2c3e718491199/packages/macros/src/babel/state.ts#L53-L55

Which is absolutely not guaranteed to have matching implementations between the babel plugin that emits the import and the actual runtime function that will be found and ran.

---

My suggestion: update `pathToRuntime` and the `packages/macros/src/ember-addon-main.ts` to "scope" the `addon` folder contents under a versioned path (e.g. `@embroider/macros/1/runtime`) such that the import that is injected is guaranteed to match implementations between babel plugin side of things and the runtime side. I don't anticipate that the version would explicitly match the `package.json` version (I'd bet _most_ of the time we release a new version of `@embroider/macros` we don't break the contract between babel plugins and runtime macros) but having a revision to bump when the coupling between the two sides (build time + runtime) will ensure that the two versions of `@embroider/macros` can co-exist together.

**Comment by rwjblue** [comment]
FWIW, I am fairly sure that this is **not** an issue in Embroider builds since we'd fall into this branch:

https://github.com/embroider-build/embroider/blob/45f2a7c590b5b725aa4535a1a3f2c3e718491199/packages/macros/src/babel/state.ts#L48-L51

And the import path would be relative to the "includer" (and therefore duplicate as needed).

**Comment by ef4** [comment]
In embroider builds, even that wouldn't come up, because there's only ever one version of `@embroider/macros` really doing all the work. We [actively disable](https://github.com/embroider-build/embroider/blob/45f2a7c590b5b725aa4535a1a3f2c3e718491199/packages/compat/src/v1-addon.ts#L932-L937) the plugins from any versions that addons brought with them.

**Comment by rwjblue** [comment]
Gotcha, perfect.

So this definitely will only affect ember-cli build pipeline. I do think it needs to be resolved before broadly suggesting addons migrate to `@embroider/macros` though.

**Comment by simonihmig** [comment]
> I do think it needs to be resolved before broadly suggesting addons migrate to @embroider/macros though.

I did that though, and yes, there were some rough edges. Loosely related: https://github.com/embroider-build/embroider/issues/509 (and still not *quite* resolved as apps using `ember-auto-import` < 1.7.0 will still likely be affected by this)

**Comment by ef4** [comment]
I agree that we could solve this by versioning the runtime as @rwjblue describes.

But I also think we could solve this the way ember-auto-import does, by choosing one copy to rule them all and letting it do all the real world, in both babel and runtime. And the reason I'd favor that strategy if practical is that it's closer to how the macros work under embroider.

**Comment by ef4** [comment]
So having reviewed the code and thought about it, I think going with runtime versioning is fine. Because of the constraints of running in the classic mode, it's actually better to let each copy of macros do its own babel on its own consumers.

**Comment by ef4** [comment]
As far as I can tell, we haven't yet shipped any incompatible releases. The first release that had the runtime code in `treeForAddon` was 0.20.0, and it hasn't changed since then. So I think this is only a theoretical future problem and not a current one.

I can add documentation to the runtime module to warn against that eventuality, but I don't think any actual code changes are needed right now.

**Comment by boris-petrov** [comment]
@ef4 - I'm not sure you're talking about the same thing, but @rwjblue opened this issue exactly because there was a case with [conflicting versions](https://github.com/emberjs/ember-classic-decorator/issues/55). Just wanted to mention that if you haven't seen it.

**Comment by ef4** [comment]
Those versions don’t actually conflict, because only one of them contains addon/runtime.js. 

It looks like ember-cli-addon-guard will complain even if we use @rwjblue’s suggested solution here. It doesn’t know whether an addon is being careful to tolerate multiple versions.

**Comment by boris-petrov** [comment]
@ef4, @rwjblue - I hit this issue yet again with `ember-exam` and `ember-element-helper`:

```
ATTENTION: ember-cli-addon-guard has prevented your application from building!

Please correct the following errors:

Your application is dependent on multiple versions of the following run-time addon:

@embroider/macros
----------------------------------------
frontend
├─┬ ember-classic-decorator
│ └── @embroider/macros@0.36.0 (cacheKey: 62be3924854e06eb5a93d04a03730070, runtime: true)
├─┬ ember-element-helper
│ └─┬ @embroider/util
│   └── @embroider/macros@0.39.1 (cacheKey: e2aaad4047836faa30eba1d9f4252edb, runtime: true)
└─┬ ember-exam
  └── @embroider/macros@0.36.0 (cacheKey: 62be3924854e06eb5a93d04a03730070, runtime: true)
```

And that's even when I'm using [my own branch](https://github.com/boris-petrov/ember-classic-decorator/tree/update-embroider-macros) of `ember-classic-decorator` as otherwise there is even a third different version of `@embroider/macros`.

What am I to do with all this? If every single addon uses their own version of `@embroider/macros` how is this going to scale?

**Comment by ef4** [comment]
Addon guard is wrong, there is no problem with your setup. There is no correctness problem (because all versions of macros have compatible runtimes), and there is no wasted bytes problems (because ember-cli will collapse the runtimes together into a single copy).

> If every single addon uses their own version of @embroider/macros how is this going to scale?

First, in the app it scales just fine for the reasons above.

Second, addons having a dependency on `@embroider/macros` is only a compatibility bridge. V2-formatted addons *can't* bring their own copy of the macros, and that is what we're moving the ecosystem toward.

**Comment by rwjblue** [comment]
We should update ember-cli-addon-guard to make it aware that this package is safe, but you can add `@embroider/macros` to your addon guard config's `ignoreAddons` for now.

**Comment by boris-petrov** [comment]
Ah, OK, thank you both, I didn't know the `ignoreAddons` config option. That works for me, thanks!

@rwjblue - if you open an issue or something in `ember-cli-addon-guard`, please ping me so I can subscribe. Thanks!

**Comment by tehhowch** [comment]
I ran into an issue with `@embroider/macros` in an ember-cli build (ember 3.24 w/edition=octane) once adding ember-classic-decorator into the mix
```
Build Error (broccoli-persistent-filter:Babel > [Babel: @embroider/macros]) in @embroider/macros/runtime.js
[BABEL]: Module did not self-register: '/path/to/monorepo/node_modules/canvas/build/Release/canvas.node'. (While processing: /path/to/monorepo/packages/my-app/node_modules/@embroider/macros/src/babel/macros-babel-plugin.js)
```
the versions that yarn installed were 0.29.0 (via ember-classic-decorator v2.0.1), 0.33.0 (ember-auto-import v1.10.1), and 0.41.0 (ember-basic-dropdown via ember-power-select v4.1.6)

pinning `@embroider/macros` to 0.41.0 resolved the build issue (for now at least).

**Comment by ef4** [comment]
@tehhowch I don't think that's the same as the above issue, please file a new one if you have a reproducible problem.

**Comment by jking6884** [comment]
Would this potentially be related to this issue?  I'm seeing this after installing certain addons.

<img width="1230" alt="image" src="https://user-images.githubusercontent.com/4825257/154822399-70879e0c-ef95-4822-afff-93956ae0877a.png">

**Comment by ef4** [comment]
Yes, that looks like this bug.

**Comment by lifeart** [comment]
Related issue: https://github.com/cibernox/ember-basic-dropdown/issues/656

**Comment by lifeart** [comment]
https://github.com/embroider-build/embroider/issues/1077
