### ISSUE TITLE
ember-addon.main vs. ember-addon.build

### ISSUE THREAD

**Issue by Turbo87** [embroider-build/embroider#6]
When reading https://github.com/embroider-build/embroider/blob/master/SPEC.md#package-hooks I thought: `ember-addon.build` is basically the same as `ember-addon.main`, just with ES6 code instead. Later the spec mentions a possible shim layer which would explain the difference between the two. A crosslink here might be useful to avoid unnecessary questions.

**Comment by ef4** [comment]
Closing because the text has changed since this was written and I'm not sure how to apply it.
