### ISSUE TITLE
Add `staticModifiers` flag (to support shaking unused modifiers and route splitting)

### ISSUE THREAD

**Issue by simonihmig** [embroider-build/embroider#603]
`AppFiles` does not handle modifiers, they are all put under `otherAppFiles`. I believe they should be treated similar to helpers, so they get split into route bundles, right?

**Comment by ef4** [comment]
Yes, and not just for route splitting. This also enables tree-shaking of unused modifiers.

To make this work, we need to add a `staticModifiers` flag that works like `staticHelpers`. The flag must do two jobs: 

1. It stops us from importing all the modifiers directly from the engine entrypoint (typically `assets/your-app.js`). It would work like staticHelpers does [here](https://github.com/embroider-build/embroider/blob/c175cc089debd38ebeec985088b94336881fbe27/packages/core/src/app.ts#L1008-L1010). This depends also, as you already guessed, on changing `AppFiles` so it keeps modifiers in their own list, separate from `otherAppFiles`.

2. It causes us to do build-time resolution of all modifiers that appear in templates. This would be implemented in [the resolver transform](https://github.com/embroider-build/embroider/blob/c175cc089debd38ebeec985088b94336881fbe27/packages/compat/src/resolver-transform.ts) and probably add to the `CompatResolver` like [here](https://github.com/embroider-build/embroider/blob/c175cc089debd38ebeec985088b94336881fbe27/packages/compat/src/resolver.ts#L365). 

The tests for this feature would go in [resolver tests](https://github.com/embroider-build/embroider/blob/c175cc089debd38ebeec985088b94336881fbe27/packages/compat/tests/resolver.test.ts). You'd be testing to make sure that we find the modifier as a dependency of any template that uses it. And also that we throw a good error if you try to use a modifier we can't find (when `staticModifiers` is enabled).
