### ISSUE TITLE
Infinite rebuilding for `ember s` in this repo's addon packages

### ISSUE THREAD

**Issue by simonihmig** [embroider-build/embroider#626]
When running `ember s` in one of this repos addon packages (e.g. `@embroider/router`), changes in `/dist` seem to trigger a rebuild, leading to an infinite loop:

![image](https://user-images.githubusercontent.com/1325249/99988881-4e899480-2db2-11eb-9858-414aa449cade.png)

I haven't yet observed this for other (3rd party) addons 🤔

**Comment by ef4** [comment]
I saw this too. Fixing it is on my short term plan for this week. It involves working around one of broccoli's fundamental limitations (it can't watch files in a directory without watching all the subdirectories too).

**Comment by ef4** [comment]
This will be fixed by https://github.com/ember-cli/ember-cli/pull/9402 which in turn depends on https://github.com/broccolijs/broccoli/pull/474

**Comment by ef4** [comment]
Also, this issue is bigger than just our test suite. Native v2 addons will hit this right away, if they contain their own test suite.
