### ISSUE TITLE
Embroider does not play well with ember-holy-futuristic-template-namespacing-batman addon

### ISSUE THREAD

**Issue by charlespierce** [embroider-build/embroider#679]
The addon [`ember-holy-futuristic-template-namespacing-batman`](https://github.com/rwjblue/ember-holy-futuristic-template-namespacing-batman) combined with an in-repo addon causes Embroider's build to fail during the Webpack stage. I created a simple reproduction case here: https://github.com/charlespierce/embroider-hftnb

From chatting with @rwjblue, it seems like that addon inserts an AST plugin that converts the syntax to a different one during the build. In a normal ember build, that is fine because it is then read later on without needing to be parsed again. However, in an embroider build, that transformation happens during Stage 1 and is written to disk. Then the parsing of that transformed template fails because `my-addon@other-component` is (correctly!) detected as invalid syntax.

I've tried a bit with local development to patch Embroider to remove the template AST transform during Stage 1, since we only want it to apply later in the process, however no matter how many different places I checked, I wasn't able to stop the template from being altered.

**Comment by ef4** [comment]
It's quite central to the design of embroider that addons can only contain valid HBS and don't get to bring their own preprocessors into the app's build.

On the other hand, app authors aren't as constrained as addon authors, and they do have the ability to register whatever kind of code transformations they want. This would take the form of (for example) a custom webpack loader that compiles all hbs files to JS in a custom way. To really make the hftnb templates work with embroider, you would need such a custom transformation anyway, because embroider's static component analysis isn't going to understand how to resolve those component names to their implementations, even if we could parse the syntax.

If you have an existing codebase using this syntax, it's probably worth going down the custom loader route to get compatibility. If you are making choices for new code, I'd advise against using an incompatible dialect like this.

**Comment by ef4** [comment]
Oh, one other option is that I *do* think there's a syntax embroider would tolerate that you could target with the AST transform such that is would re-serialize to valid HBS:

```hbs
<AddonName$ComponentName />
```

would become

```hbs
{{#let (component "addon-name@component-name") as |C|}}
  <C />
{{/let}}
```

That might give you an out.

**Comment by rwjblue** [comment]
Ya, that sounds like a good path forward for components, but unsure how that would work for helper invocations (since there is no `(helper` yet)...

**Comment by charlespierce** [comment]
@ef4 Thanks for the response! A couple of follow-up questions:

* Where (both conceptually in the process and in the code) does the static component analysis happen? Presumably to support the existing code base with those invocations littered all over it, we'll need to make sure it's compiled out by that time.
* Is there an existing webpack loader that we would need to extend to add support for the new syntax?
* Is there a mechanism to replace that loader with a custom one from the App side?
* Is there a way to tell embroider to strip out the HFTNB addon & it's associated transformation, so that we can keep it around for compatibility with classic builds (since those older builds won't be able to use a webpack loader to process the syntax)?

@rwjblue Is there something in HFTNB addon that "closes the loop" after the AST transform? That is, the transformation replaces the names with something else, but then how does Ember resolve those `addon@component` names into the appropriate components?

Apologies for the potentially basic questions, I'm still getting up to speed on the embroider codebase so I haven't fully wrapped my head around everything it does.

**Comment by rwjblue** [comment]
> @rwjblue Is there something in HFTNB addon that "closes the loop" after the AST transform? That is, the transformation replaces the names with something else, but then how does Ember resolve those addon@component names into the appropriate components?

The ember-resolver knows how to resolve the `@` separator (there are tests over there for this).

**Comment by rwjblue** [comment]
> Is there a way to tell embroider to strip out the HFTNB addon & it's associated transformation, so that we can keep it around for compatibility with classic builds (since those older builds won't be able to use a webpack loader to process the syntax)?

I think this (or a variant) is going to be the best initial path forward (at least for safe mode, not sure RE: optimizations just yet). 

Basically, we update the HFTNB addon to noop when running in an addon within an Embroider build (double checking that the host application has the HFTNB addon installed also). This *should* allow things to work just fine avoiding the `addon-name$component` -> `addon-name@component` transformation during earlier stages of addon compilation under Embroider, but allowing that compilation to happen when the final templates are compiled from hbs to wire format.

**Comment by charlespierce** [comment]
Created https://github.com/rwjblue/ember-holy-futuristic-template-namespacing-batman/pull/418 to add a configuration setting to HFTNB that allows us to disable it for nested addons in the embroider case.

**Comment by rwjblue** [comment]
Closing here for now, apps need to leverage the changes in https://github.com/rwjblue/ember-holy-futuristic-template-namespacing-batman/pull/418.
