### ISSUE TITLE
macroMaybeModifier needed?

### ISSUE THREAD

**Issue by simonihmig** [embroider-build/embroider#680]
I just came across a use case where I wanted to use `@embroider/macros` to conditionally apply a modifier. As we are in element space, we cannot simply use `{{#if}}` here. 

The same applied for setting attributes conditionally, but this is explicitly covered by `macroMaybeAttrs`. Do we eventually need an equivalent for this, `macroMaybeModifier`?

**Comment by ef4** [comment]
This seems reasonable.

**Comment by rwjblue** [comment]
> As we are in element space, we cannot simply use {{#if}} here. 

In Ember 3.25 and higher, you should be able to do:

```hbs
<div {{(if something on) 'click' this.foo}}></div>
```

**Comment by ef4** [comment]
That's good! But that doesn't replace the need for the macro.

For example, if you're trying to run a modifier only in development, the macro would let you compile the modifier entirely out of the build in production.

**Comment by ef4** [comment]
Oh, but I should add: maybe instead the solution is to make sure macroCondition works inside this position. Then we don't need special maybeMacroAttrs and maybeModifier.

**Comment by simonihmig** [comment]
> maybe instead the solution is to make sure macroCondition works inside this position

Yeah, I was thinking the same when I saw this. 

Is any Ember version (or at least the minimum that `@embroider/macros` has to support) able to correctly parse this, for our AST transform?

> Then we don't need special maybeMacroAttrs and maybeModifier.

How would that work for `macroMaybeAttrs`? Is there in any similar way a valid syntax (in Ember's runtime) that would allow conditional attributes?

**Comment by simonihmig** [comment]
> Oh, but I should add: maybe instead the solution is to make sure macroCondition works inside this position. 

PR: #712
