### ISSUE TITLE
ReferenceError: emberAutoImportDynamic is not defined

### ISSUE THREAD

**Issue by bobisjan** [embroider-build/embroider#683]
Hi,

when using dynamic import via `ember-auto-import` under Embroider the application throws error:

```
Error while processing route: marketplace.primary.index emberAutoImportDynamic is not defined ReferenceError: emberAutoImportDynamic is not defined
    at IntlService.polyfills (webpack:///./services/intl.js?:204:103)
    at IntlService.setupLocale (webpack:///./services/intl.js?:173:190)
    at ApplicationRoute.afterModel (webpack:///./application/route.js?:97:21)
```

The issue can be resolved by removing `ember-auto-import/babel-plugin` from `ember-cli-build.js` (https://github.com/ef4/ember-auto-import#dynamic-import).

Is it _correct_ way and thus https://github.com/embroider-build/embroider#how-to-try-it may be enhanced?

**Comment by simonihmig** [comment]
> The issue can be resolved by removing ember-auto-import/babel-plugin from ember-cli-build.js (https://github.com/ef4/ember-auto-import#dynamic-import).

FWIW, I have been successfully using `import()` in Embroider, and have never added that babel plugin. So yes, it seems it is at least unnecessary in an Embroider world, and if it breaks things in your case, apparently it is also harmful.

**Comment by ef4** [comment]
This is a bug, people should not need to manually remove that plugin.

Everything in ember-auto-import is supposed to get automatically disabled when you're using embroider, because everything it provides becomes built-in. I know we have code to automatically disable the plugin, but there must be a case we're missing.

**Comment by bobisjan** [comment]
Thanks for clarification, I'll poke around later today.

**Comment by bobisjan** [comment]
It looks that detection fails at https://github.com/embroider-build/embroider/blob/936367159b370492b0bff4b67373d1da29d49fd3/packages/compat/src/detect-ember-auto-import.ts#L10

The item is a function, this is what I see when using console `console.log('isEmberAutoImportDynamic', item);`

```
isEmberAutoImportDynamic function emberAutoImport() {
    return {
        inherits: babel_plugin_syntax_dynamic_import_1.default,
        visitor: {
            Import(path) {
                let call = path.parentPath;
                let arg = call.node.arguments[0];
                if (arg.type === 'StringLiteral') {
                    let cat = package_1.default.categorize(arg.value);
                    if (cat === 'dep') {
                        call.replaceWith(types_1.callExpression(types_1.identifier('emberAutoImportDynamic'), [arg]));
                    }
                }
                else if (arg.type === 'TemplateLiteral') {
                    let cat = package_1.default.categorize(arg.quasis[0].value.cooked, true);
                    if (cat === 'dep') {
                        call.replaceWith(types_1.callExpression(types_1.identifier('emberAutoImportDynamic'), [
                            types_1.stringLiteral(arg.quasis.map(q => q.value.cooked).join('${e}')),
                            ...arg.expressions,
                        ]));
                    }
                }
            },
        },
    };
}
```

**Comment by ef4** [comment]
How you are registering the plugin in your app? If you do `require('ember-auto-import/babel-plugin')` it will indeed not be able to be detected, as well as not being able to be serialized.

The docs show `require.resolve('ember-auto-import/babel-plugin')` instead, which avoids those problems.

**Comment by bobisjan** [comment]
Thanks, I've missed that change 🙈, using `require('ember-auto-import/babel-plugin')` comes from previous version of the docs.

**Comment by ef4** [comment]
Yeah, my bad, the docs showed the wrong pattern for a long time.
