### ISSUE TITLE
importSync in classic build + ember-auto-import

### ISSUE THREAD

**Issue by simonihmig** [embroider-build/embroider#684]
Given that `@embroider/macros` are usable both in an Embroider as well as a classic build, I was assuming that e.g. `importSync('lodash-es')` would just work in a classic build with `ember-auto-import`. 

But it seems `ember-auto-import` is not "seeing" this as a module dependency that it needs to pull into the bundle. The imported module is not part of the bundle, and thus the transformed `require()` call is failing with `loader.js:247 Uncaught Error: Could not find module `lodash-es` imported from `(require)`.

Isn't it supposed to work, or am I missing something?

I have a reproduction at hand, that I can push if it helps, but it is really as simple as trying to `importSync()` any dependency that is not already (statically) imported elsewhere.

**Comment by ef4** [comment]
Yes, this is a good point. I think we should make ember-auto-import aware of importSync and treat it like any other import. 

The actual fix would go in ember-auto-import’s analyzer.

**Comment by simonihmig** [comment]
> The actual fix would go in ember-auto-import’s analyzer.

Hm, haven't touched e-a-i before, but looking at the analyzer, is it as simple as it seems looking at [this part](https://github.com/ef4/ember-auto-import/blob/c799048a5cc969a7c4ec7ca9d72f677dd16cc119/packages/ember-auto-import/ts/analyzer.ts#L193), to add detection there for `importSync()`? 

Or what else would I need to be aware of? Does the analyzer run *before* the macros, so it sees `importSync()` rather than `require()`?

**Comment by ef4** [comment]
Yes, that is where I meant. You would use babel's `referencesImport` like [this](https://github.com/embroider-build/embroider/blob/936367159b370492b0bff4b67373d1da29d49fd3/packages/macros/src/babel/macros-babel-plugin.ts#L91) to identify the `importSync` reliably.

We don't want to make auto-import handle `require`, so we would really want to run before the macros babel plugin. I'm not sure off hand what order they would happen right now.
