### ISSUE TITLE
Should Embroider link hoisted transitive dependencies?

### ISSUE THREAD

**Issue by charlespierce** [embroider-build/embroider#689]
For non-addon dependencies, Embroider links them into the `embroider` temp directory using [`linkNonCopiedDeps`](https://github.com/embroider-build/embroider/blob/master/packages/compat/src/compat-addons.ts#L223). However, this function only links the _direct_ dependencies of a given package. Both Yarn and npm will attempt to hoist transitive dependencies as much as possible, to avoid duplication, so they often are not children of the direct dependencies on disk.

In the case that a package relies on a transitive dep, linking only the direct dependencies can cause that package to not be found, even though it is correct and on disk. One example of this is an app that has a dependency on `@babel/preset-env` but then references one of the plugins provided by that package by name. The plugin gets hoisted and then not included in the final build directory.

In situations like this, should Embroider handle bringing over the nested dependencies as well? Or should it be clearly documented that anything you explicitly depend on needs to be included in your direct dependencies and you can't rely on transitive relationships?

**Comment by ef4** [comment]
Relying on transitive deps is deliberately not supported.

The problem with that pattern is that it locks us forever into the implementation detail of node_modules, whereas there are multiple better systems (pnpm, yarn plug-n-play) already coming into use that are dramatically more reliable and performant.

I'm pretty sure `@babel/preset-env` doesn't consider its internal list of plugins to be public API, so they can refactor in a minor release and break your app. It's just never safe to rely on hoisting for correctness.

When it's important that two levels in the dependency graph share the same copy of a package, they should declare peerDependencies, and then we will correctly setup the links for them.

**Comment by charlespierce** [comment]
Makes sense, thanks for clarifying @ef4!
