### ISSUE TITLE
typescript within addon /tests folder seems not working

### ISSUE THREAD

**Issue by ro0gr** [embroider-build/embroider#691]
Hey 👋 Thanks for this software, I'm looking forward to see it in action!

I'm currently trying to check the path forward for ember-cli-page-object + embroider. The first stopper I've noticed is typescript files within the "/tests" folder. Seems it tries to be processed as a regular JS, and fails on TS syntax.

Here I've prepared a small reproduction https://github.com/ro0gr/embroider-addon-ts-test

interestingly, the code inside the "tests/dummy" is handled as it should, which is ensured i the commit before the last one. Also it might worth to mention, it does fail the same way despite the ember-cli-typescript installed or not.

For convenience, here is a link to the build failure: https://travis-ci.com/github/ro0gr/embroider-addon-ts-test/jobs/482820357#L293

I'm not familiar with the codebase here, but if I get some starting point references, I can try to help to solve this issue. Thanks!

**Comment by ro0gr** [comment]
oh.. somehow I've missed that a really old version of ec-typescript is the reason. It works on the latest(at least v4) version of the the ec-typescript. Sorry for confusion!

**Comment by NullVoxPopuli** [comment]
I'm experiencing this on a 3.27 addon with 0.42.x embroider
