### ISSUE TITLE
Link attributes are wiped in index.html

### ISSUE THREAD

**Issue by johanrd** [embroider-build/embroider#698]
1. Add some attributes to a link tag in `index.html`:
```diff
-<link integrity="" rel="stylesheet" href="{{rootURL}}assets/app.css">
+<link integrity="" rel="stylesheet" href="{{rootURL}}assets/app.css" media="none" onload="if(media!='all')media='all'">
``` 
2. Build with embroider, and experience that the attributes are wiped in `dist/index.html`:
```
<link integrity="" rel="stylesheet" href="/assets/app.css">
```

This may not be very important in itself, but posting here since this is the third time (https://github.com/embroider-build/embroider/issues/562, https://github.com/embroider-build/embroider/issues/654) I have struggled with the developer ergonomics of how `index.html` is generated with embroider. Do we know of any workaround for now? Thanks!

**Comment by ef4** [comment]
There is also an open PR: https://github.com/embroider-build/embroider/issues/698

It has been marked "draft" so hasn't been reviewed. I think it has more in it than necessary, but the fix is in there.

**Comment by johanrd** [comment]
Ah, ok, thanks:thumbsup:
