### ISSUE TITLE
`@ember/component` import

### ISSUE THREAD

**Issue by Turbo87** [embroider-build/embroider#7]
The spec says:
> @ember/component really comes from ember-cli-shims/vendor/ember-cli-shims/app-shims, which uses globals to find the real code in ember-source.

but that's actually not quite true. The `@ember/component` import at the moment is transpiled away by `ember-cli-babel` and convert into an `Ember` global access. `ember-cli-shims` has been removed from the default blueprints.

**Comment by ef4** [comment]
You're correct, my info was out of date when I wrote that (but the current code _does_ account for that difference and does the right thing in both cases).
