### ISSUE TITLE
Macros fail with latest ember-cli-htmlbars

### ISSUE THREAD

**Issue by simonihmig** [embroider-build/embroider#701]
Template macros that should be perfectly valid and worked for a long time [like this](https://github.com/kaliber5/ember-bootstrap/blob/master/addon/components/bs-accordion.hbs#L2) are now failing the build with [`argument to macroCondition must be statically analyzable`](https://github.com/kaliber5/ember-bootstrap/runs/1988767150?check_suite_focus=true#step:5:84), but only with floating dependencies.

I tracked this down to the fact that [`makeFirstTransform`](https://github.com/embroider-build/embroider/blob/master/packages/macros/src/glimmer/ast-transform.ts#L8) and [makeSecondTransform](https://github.com/embroider-build/embroider/blob/master/packages/macros/src/glimmer/ast-transform.ts#L97) are now called in reverse order. Which means that the use of `(macroGetOwnConfig ...)` is not compiled away to a static value (in the first transform), before the second transform handling `(macroCondition ...)` checks for that.

It seems related to the latest version 5.6.x of `ember-cli-htmlbars`: when downgrading it to 5.5.0 the order is again as expected, and things work again. /cc @rwjblue

**Comment by rwjblue** [comment]
@simonihmig - would you mind testing against #700?

**Comment by rwjblue** [comment]
I'll try to repro over in ember-cli-htmlbars with some AST ordering tests.

**Comment by simonihmig** [comment]
Will do, hopefully tomorrow, but not today anymore (it's quite late over here 😴). Thanks for the quick feedback!

**Comment by rwjblue** [comment]
I released https://github.com/ember-cli/ember-cli-htmlbars/releases/tag/v5.6.2 to try to accommodate this, needs testing.

**Comment by simonihmig** [comment]
Fixed by 5.6.2, closing this! :tada:
