### ISSUE TITLE
Module not found: Can't resolve '../../../../file'  Any option to include in-repo addons of an app ?

### ISSUE THREAD

**Issue by siva-sundar** [embroider-build/embroider#722]
I am testing embroider in one of our ember apps. We have a few in-repo-addons in the app which is shared across multiple in-repo addons and internal/external engines.

Getting the following error while `ember s`.

```Build Error (PackagerRunner) in lib/engine-one/components/settings/preferences/contact/component-one.js

Module not found: Error: Can't resolve '../../../../../settings-common/components/settings/preferences/contact/component-one' in 
'$TMPDIR/embroider/dc28f8/lib/settings/components/settings/preferences/contact' 
```

Currently using:

```json
"ember-cli": "~3.8.3",
"ember-source": "~3.8.0"
"@embroider/compat": "^0.37.0",
"@embroider/core": "^0.37.0",
"@embroider/webpack": "^0.37.0",
```

Some help around here would be really appreciated, thanks!

**Comment by rwjblue** [comment]
In general, this should work (we have a few apps with what sounds like a similar setup). Can you make a demo reproduction repository that shows the issue with your setup?

**Comment by siva-sundar** [comment]
@rwjblue Here is the reproduction of the [issue](https://github.com/siva-sundar/embroider-cannot-find-module-error/blob/master/README.md). Hope this helps, let me know if you have any further clarifications.

**Comment by siva-sundar** [comment]
@rwjblue Could you please check this when you are free ? Kinda stuck with this for more than a week. Couldn't find the actual cause. Any help would be really useful. Thanks!

**Comment by sandydoo** [comment]
Well, here’s your cause.

```js
return EmbroiderCompat.compatBuild(app, Webpack, {
  packagerOptions: {
    webpackConfig: {
      resolve: {
        alias: {
          'embroider-cannot-find-module-error': path.resolve(__dirname, './app'), // app
          settings: path.resolve(__dirname, './lib/settings/'), // addon
          'common-utilities': path.resolve(__dirname, './lib/common-utilities/'), // engine
        }
      }
    }
  }
});
```

Replace all that with:
```js
return EmbroiderCompat.compatBuild(app, Webpack);
```
and your app works just fine.

**Comment by siva-sundar** [comment]
This worked, thanks for the info.

Closing the issue.
