### ISSUE TITLE
Regression: Build Error: Don't know how to insertURL for sourcemaps

### ISSUE THREAD

**Issue by johanrd** [embroider-build/embroider#725]
After 99a3202:
 
 1. Run `ember build` with sourcemaps:

``` 
webpackConfig: {
  devtool: 'source-map',
}
```
2. Experience Build Error:
```console
Build Error (PackagerRunner)
don't know how to insertURL /assets/chunk.9487b3713b2712e9dae6.js.map
```

Build does not break before 99a320288ac0b91ea9c8b962c73dace004f31fae. Probably caused by fallthrough condition `url.endsWith('.js')` for `js.map`. See https://github.com/embroider-build/embroider/commit/99a320288ac0b91ea9c8b962c73dace004f31fae#diff-f6871a419b7638a206e71923afc7910d1a3252cdfa5c563a5fb7e455063146b0L44-L54:

**Comment by ef4** [comment]
Thanks for reporting. We should ignore these instead of erroring, because they're not supposed to be inserted into the HTML.

**Comment by johanrd** [comment]
Ok, thanks, yes, that makes sense. 

That would also close #654 I guess.

**Comment by naiyt** [comment]
I threw up a quick PR with a potential fix: https://github.com/embroider-build/embroider/pull/734

**Comment by johanrd** [comment]
@naiyt Thanks. The fix is quite specific, but it does the job.

@ef4 If you don't see any obvious shortcomings to #734, it would be great to have it merged in, as now any project with sourcemaps is stranded on `v <=  35.1`.

**Comment by johanrd** [comment]
Closing, as source maps does not seem to be referenced in `index.html` anymore when building with `v0.43`. 

Which means that #734 can be closed too I guess, @naiyt, I you experience the same as me.
