### ISSUE TITLE
Actionable warning for Your build is slower because some babel plugins are non-serializable?

### ISSUE THREAD

**Issue by johanrd** [embroider-build/embroider#727]
Hi. When building a fresh app with [ember-test-selectors](https://github.com/simplabs/ember-test-selectors) installed, I get the following warning:

```console
[ConfigLoader]WARNING: Your build is slower because some babel plugins are non-serializable
```

I could have created an issue over at `ember-test-selectors` to see if this is easily fixable from there. However, I am not completely sure how useful this message itself would be for them.

Would it make sense to provide some actionable best-practices we could link to for ember-addons to be non-"non-serializable"?

**Comment by rwjblue** [comment]
Part of the issue is due to a misalignment between how broccoli-babel-transpiler handles the parallelization vs how ember-cli-htmlbars handles it. The parallelization system that exists within Embroider assumes the two systems are compatible, but unfortunately they are not (which is 100% my fault, but here we are... 😞 ). 

The good news is that we are actively working on aligning the two systems, and fixing this issue for the majority of folks that see it only under Embroider builds. Unfortunately, I'm not sure exactly how long that will be (hopefully "soon", but still a bit TBD).

---

To alleviate the issue for your builds right now you can use `pluginHints` to help avoid the message:

https://github.com/embroider-build/embroider/blob/bdea4008868de26bc9afad0c5229b2ecf34979f5/packages/core/src/options.ts#L60-L71

**Comment by ef4** [comment]
One challenge here is that the reason a plugin is non-serializable is that we have no idea where it came from. So it's hard to tell in the error message who's responsible.

But you're right, we could at least include a URL in this message explaining more what it means and how to address it.

**Comment by ef4** [comment]
Specifically for ember-test-selectors, you can manually tell Embroider where to find its plugins like this:

```js
return compatBuild(app, Webpack, {
    pluginHints: [
      {
        resolve: [
          'ember-test-selectors/transform-test-selector-params-to-hash-pairs',
        ],
      },
      {
        resolve: ['ember-test-selectors/strip-test-selectors'],
      },
    ],
  });
```

**Comment by alexlafroscia** [comment]
I'm running into something similar that's a bit confusing. Embroider is reporting this warning for the transformation from `ember-element-helper`, but the addon that it seems to be processing doesn't support on that dependency.

Here, `ember-fetch` seems to be the thing being processed when the warning is shown. The plugin that gets printed after that is the one for `ember-element-helper`

<img width="1350" alt="CleanShot 2021-04-02 at 15 02 37@2x" src="https://user-images.githubusercontent.com/1645881/113445939-c00eca80-93c4-11eb-88f1-dd3320fd0be9.png">

Would the "solve" here to do something like

```js
{
  pluginHints: [
    {
      resolve: [
        'ember-fetch', 'ember-element-helper/whatever/path/to/transform.js'
      ]
    }
  }
}
```

Even though `ember-fetch` shouldn't be triggering that transform?

**Comment by alexlafroscia** [comment]
> One challenge here is that the reason a plugin is non-serializable is that we have no idea where it came from.

@ef4 is there something that addons could be doing to make it so that Embroider _does_ know where the transforms are coming from? I'd love to make PRs against the plugins generating this warning to fix it on their end, if there's something they can do.

**Comment by ef4** [comment]
> I'm running into something similar that's a bit confusing. Embroider is reporting this warning for the transformation from ember-element-helper, but the addon that it seems to be processing doesn't support on that dependency.

I think you're being mislead by the ordering of the output. I don't think there's any guarantee that you can tell which addon's broccoli tree caused the warning. If you know the problematic plugin is from ember-element-helper, use `yarn why ember-element-helper` or `npm explain ember-element-helper` to see how they're getting into your app.

**Comment by ef4** [comment]
> is there something that addons could be doing to make it so that Embroider does know where the transforms are coming from?

The addons were already doing what ember-cli-htmlbars supports, but embroider didn't understand that. This should fix it: https://github.com/embroider-build/embroider/pull/754

**Comment by acorncom** [comment]
Should this issue be closed?
