### ISSUE TITLE
`ember serve` does not quit after hitting an initial build error

### ISSUE THREAD

**Issue by Turbo87** [embroider-build/embroider#75]
after hitting #73 I was expecting `ember serve` to quit, but it kept running without any other feedback. is that intended behavior?

**Comment by ef4** [comment]
Does `ember s` normally (without embroider) exit when encountering a syntax error in a javascript module? I don't think it does.

**Comment by Turbo87** [comment]
yeah, I guess you're right. still seemed confusing that there was no feedback of the build still running and waiting for file changes
