### ISSUE TITLE
Webpack is using the Ember global in compiled templates

### ISSUE THREAD

**Issue by sandydoo** [embroider-build/embroider#781]
### Summary

I _think_ Webpack is turning imports of `createTemplateFactory` into a reference to `Ember.HTMLBars.template`, which throws deprecation notices in apps running `3.27+`.

### In more detail

As of `v3.27`, accessing the Ember global throws a deprecation notice.

[`ember-cli-htmlbars` was recently updated](https://github.com/ember-cli/ember-cli-htmlbars/pull/683) to replace `Ember.HTMLBars.template` with module imports.

Now, templates should be compiled with:

```js
import { createTemplateFactory } from '@ember/template-factory';
export default createTemplateFactory(${precompiled});
```

But in apps built with Embroider specifically, what we see is the following:

```js
const createTemplateFactory = Ember.HTMLBars.template;
...
```

My hunch is that Webpack is doing this, _but I have no proof_ 🤣.
Any ideas? Am I completely wrong here?

### Steps to reproduce

Run `ember new` with `ember-cli@3.27-beta.x`.
Inspect the console logs. You should see a warning coming from `application.hbs`.

### Versions used for testing
```
@embroider/*: 0.39.1 && 0.40.0
ember-source: 3.27.0-beta.4
ember-cli-htmlbars: 5.7.1
```

**Comment by ef4** [comment]
This is supposed to be handled [here](https://github.com/embroider-build/embroider/blob/8137a35cb254ddd6be1e1c3cd6b5614328d881ee/packages/compat/src/compat-app.ts#L368), could you poke around and see what's happening in that spot?

**Comment by sandydoo** [comment]
Never mind! I was totally wrong. It was this:

https://github.com/embroider-build/embroider/blob/d36a0458a329fdc218c1ac6cfb074f331ff96f87/packages/core/src/mini-modules-polyfill.ts#L28-L35

This polyfill is being run in apps on the `3.27.0-beta.x` range because this semver check resolves to `true` for these versions. It’s a bit annoying, but it will resolve itself when `3.27.0` is released.

https://github.com/embroider-build/embroider/blob/8137a35cb254ddd6be1e1c3cd6b5614328d881ee/packages/compat/src/compat-app.ts#L368

**Comment by sandydoo** [comment]
> This is supposed to be handled [here](https://github.com/embroider-build/embroider/blob/8137a35cb254ddd6be1e1c3cd6b5614328d881ee/packages/compat/src/compat-app.ts#L368), could you poke around and see what's happening in that spot?

Just as I’m about to close the issue 😅 Great timing!

**Comment by ef4** [comment]
We should probably still change that condition so it allows the beta series. I think `semver.satisfies(emberSource.version, '<3.27.0-beta.0', { includePrerelease: true })` would do it and be more correct.
