### ISSUE TITLE
cannot resolve @glimmer/tracking with embroider 0.40.0 and ember-source 3.27-beta

### ISSUE THREAD

**Issue by NullVoxPopuli** [embroider-build/embroider#794]
reproduction: https://github.com/NullVoxPopuli/embroider-ember-3-27-beta-repro-missing-glimmer/commit/8d5fd9819eb8887e4087df54f778b640ccd717bc

**Comment by sandydoo** [comment]
Should be fixed by https://github.com/embroider-build/embroider/pull/785.
