### ISSUE TITLE
Build error: "don't know how to insertURL /assets/undefined"

### ISSUE THREAD

**Issue by simonihmig** [embroider-build/embroider#798]
After re-enabling embroider test scenarios in `ember-bootstrap`, I am getting this error in [CI](https://github.com/kaliber5/ember-bootstrap/runs/2477511224?check_suite_focus=true#step:5:141), also when adding the embroider dependencies locally to this [PR](https://github.com/kaliber5/ember-bootstrap/pull/1341) (which could serve as a reproduction).

It has worked before, so this seems like a regression.

I debugged this a bit in node:

1. the error is thrown in `@embroider/webpack` [here ](https://github.com/embroider-build/embroider/blob/master/packages/webpack/src/html-placeholder.ts#L50)

2. in the previous step of the call stack, the `match` for `assets/dummy.js` seems pretty broken:
![Bildschirmfoto 2021-04-30 um 19 28 58](https://user-images.githubusercontent.com/1325249/116733399-5b0eba80-a9ec-11eb-95e8-c58c09649785.png)

3. Same when looking at `stats.entrypoints` map for `assets/dummy.js` (same for `assets/tests.js`):
![Bildschirmfoto 2021-04-30 um 19 32 03](https://user-images.githubusercontent.com/1325249/116733487-7083e480-a9ec-11eb-91b3-e99105eb0ef5.png)

Haven't investigated any further. Any idea?

**Comment by NullVoxPopuli** [comment]
confirm: I got this error yesterday in an addon and made it go away by manually adding webpack @v5 to my package.json

**Comment by simonihmig** [comment]
> Those are fixed on master but not yet released, I need to do a patch release soon.

I could refer to the master branch of test-setup as an interim solution, but wonder if there is anything left blocking that release? (other than your personal time of course) Anything I/we can do?

**Comment by mehulkar** [comment]
Ran into the same thing with `@embroider/test-setup` (0.40.0)! Turns out that `webpack@4` is coming from ember-auto-import, btw.

**Comment by rwwagner90** [comment]
I'm experiencing this issue as well. I tried `yarn add webpack -D` and now my tests seem to just hang and throw errors like `not ok 1 Chrome 90.0 - [undefined ms] - Global error: Uncaught ReferenceError: Ember is not defined at http://localhost:7357/assets/vendor.js, line 1027`

**Comment by ef4** [comment]
The main thing blocking release is that changes in (I think) ember-cli-babel have left a large swath of embroider's test suite falling.

**Comment by knownasilya** [comment]
Seeing the same issue with ember-page-title. Tried with auto-import v2 and get the same result as well.

**Comment by simonihmig** [comment]
Confirm. Fixed in 0.41.0!

**Comment by rwwagner90** [comment]
Anyone know why tests would be hanging for embroider with errors like this?

```
not ok 1 Chrome 90.0 - [undefined ms] - Global error: Uncaught ReferenceError: Ember is not defined at http://localhost:7357/assets/vendor.js, line 1027
    ---
        browser log: |
            {"type":"error","text":"Uncaught ReferenceError: Ember is not defined at http://localhost:7357/assets/vendor.js, line 1027\n","testContext":{}}
    ...
not ok 2 Chrome 90.0 - [undefined ms] - Global error: Uncaught Error: Could not find module `velocity` imported from `(require)` at http://localhost:7357/assets/vendor.js, line 256
```

They run for hours and never time out, so I cancel them, and then I see these types of errors. See this PR https://github.com/shipshapecode/ember-shepherd/pull/779

**Comment by knownasilya** [comment]
@rwwagner90 sounds like you need to use skipBabel setting for velocity maybe?

**Comment by rwwagner90** [comment]
@knownasilya I tried that in https://github.com/shipshapecode/ember-shepherd/pull/779 and it still seems to hang with the same error. @ef4 any ideas here?
