### ISSUE TITLE
Refactor test runner

### ISSUE THREAD

**Issue by Turbo87** [embroider-build/embroider#80]
Our test runner seems somewhat special and also does not run on Windows at all. From my first glance this is the current situation:

- `yarn node-test` is running QUnit and the unit tests in the `packages` folders
- `yarn test` is running `parallel` which runs `yarn test` (`ember test`) for most of the folders in `test-packages` in parallel

I'm wondering if instead of using `parallel` we should use a proper test runner that runs tests in parallel by default, e.g. Jest.

Refactoring the TS unit tests to Jest seems quite straight forward and running `ember test` on the `test-packages` should also be feasible using something like https://github.com/sindresorhus/execa/

@stefanpenner @ef4 I'd be happy to look into that if you're okay with the direction.

**Comment by ef4** [comment]
Yes, that sounds good. My main concern would be to keep the output from each suite nicely grouped and labeled as it is now, rather than interleaved.
