### ISSUE TITLE
Update test-setup instructions due to 0.40.0 breaking change

### ISSUE THREAD

**Issue by cah-briangantzler** [embroider-build/embroider#806]
I had to update the ember try scenario from 
```
embroiderSafe()
``` 
to 
```
embroiderSafe({
        npm: {
          devDependencies: {
            "webpack": '^5.0.0',
          },
        },
      }),
```

We either need to change the instruction page or change the embroiderSafe generated scenario to include the webpack peer dependancy

**Comment by ef4** [comment]
I think this is already fixed here https://github.com/embroider-build/embroider/pull/792 and will be in the next release.
