### ISSUE TITLE
Runtime error in production build using ember-concurrency with staticAddonTrees

### ISSUE THREAD

**Issue by bendemboski** [embroider-build/embroider#811]
## Repro & error

Using [this](https://github.com/bendemboski/embroider-e-c-bug) app, if you run `ember serve -e production` and then visit `localhost:4200`, the app will fail to start and you'll see in the console:

```
Uncaught ReferenceError: yieldableSymbol is not defined
    at Object.4843 (chunk.aab8374d30dbb2c7514f.js:1)
    at n (chunk.1168a4158e9c3f27793c.js:1)
    at Object.8048 (chunk.1168a4158e9c3f27793c.js:1)
    at n (chunk.1168a4158e9c3f27793c.js:1)
    at o.callback (chunk.1168a4158e9c3f27793c.js:1)
    at o.exports (vendor.d97211c717a208971e188d96d417508f.js:1)
    at requireModule (vendor.d97211c717a208971e188d96d417508f.js:1)
    at e._extractDefaultExport (chunk.aab8374d30dbb2c7514f.js:1)
    at e.resolveOther (chunk.aab8374d30dbb2c7514f.js:1)
    at e.resolve (chunk.aab8374d30dbb2c7514f.js:1)
```

Building for development works fine, and building without `staticAddonTrees` works fine, but if both of those factors are present, this error occurs. It's also notable that I removed the conditional inclusion of IE11 in the targets from `config/targets.js`, so IE11 is never included (and the targets are the same for dev vs. prod).

## Further investigation

I built with `devtool: 'eval'` and extracted and formatted the code [here](https://github.com/bendemboski/embroider-e-c-bug/blob/main/vendor/chunk.js). The proximate cause is that `yieldableSymbol` is referenced in a few places like [here](https://github.com/bendemboski/embroider-e-c-bug/blob/16856659501ff5dbb486e69a39b763d747def577/vendor/chunk.js#L271) but it's not defined.

In original source it's exported from [/-private/external/yieldables.js](https://github.com/machty/ember-concurrency/blob/6e14c9c6fbbc78d2758e3619aea7e56b229729ed/addon/-private/external/yieldables.js#L2) and imported into several modules. The export gets transpiled to `yieldables_yieldableSymbol` ([here](https://github.com/bendemboski/embroider-e-c-bug/blob/16856659501ff5dbb486e69a39b763d747def577/vendor/chunk.js#L54)).

All of the modules that also live in `/-private/external/` that import it have their references transpiled correctly -- the other references in the same module that exports it, but also some others, e.g. [/-private/external/task-instance/executor.js](https://github.com/bendemboski/embroider-e-c-bug/blob/16856659501ff5dbb486e69a39b763d747def577/vendor/chunk.js#L948) plus a couple of others.

However, all of the modules that live in `/-private/` (_not_ `/external/`) end up with references to `yieldableSymbol` instead of `yieldables_yieldableSymbol`, e.g. [/-private/utils.js](https://github.com/bendemboski/embroider-e-c-bug/blob/16856659501ff5dbb486e69a39b763d747def577/vendor/chunk.js#L271) and [/-private/wait-for.js](https://github.com/bendemboski/embroider-e-c-bug/blob/16856659501ff5dbb486e69a39b763d747def577/vendor/chunk.js#L3689).

## My wild guess

My current best guess is it has something to do with tree-shaking -- I _think_ all of the classes inside `/-private/external/` that reference that symbol end up being referenced/un-tree-shakeable, while all the ones in `/-private/` are not referenced and are tree-shakeable. So maybe webpack is skipping some processing of them because they are un-referenced, but then for some reason they aren't actually being stripped from the bundle?

**Comment by bendemboski** [comment]
If anyone's looking for an ugly workaround, this appear to work (with `string-replace-loader` installed):

```js
packagerOptions: {
  webpackConfig: {
    module: {
      rules: [
        {
          test: /\/ember-concurrency\//,
          loader: 'string-replace-loader',
          options: {
            multiple: [
              {
                search: '\\[yieldableSymbol\\]',
                flags: 'g',
                replace: '["__ec_yieldable__"]',
              },
              {
                search: '\\[cancelableSymbol\\]',
                flags: 'g',
                replace: '["__ec_cancel__"]',
              },
            ],
          },
        },
      ],
    },
  },
},
```

**Comment by maxymczech** [comment]
Thank you, you are literally a lifesaver! A small ocmment, your `test` string didn't work for me, so I had to remove leadning and trailing slashes:

```
test: /ember-concurrency/,
```

Also I found it useful to disable `webpack` minification to see what exactly is going on in there:

```
    packagerOptions: {
      webpackConfig: {
        optimization:{
          minimize: false
        }
      }
    }

```

**Comment by bendemboski** [comment]
This no longer reproduces with embroider v3 (it may have been fixed well before v3, I haven't tested intermediate versions)
