### ISSUE TITLE
Document EMBROIDER_REBUILD_ADDONS

### ISSUE THREAD

**Issue by mehulkar** [embroider-build/embroider#814]
Just learned about this env variable and don't see any documentation about it

**Comment by mehulkar** [comment]
some code references: https://github.com/embroider-build/embroider/search?q=EMBROIDER_REBUILD_ADDONS and this comment: https://github.com/embroider-build/embroider/issues/532#issuecomment-695089503

**Comment by bertdeblock** [comment]
This was added in the last update to the SPEC: https://github.com/embroider-build/embroider/commit/fe30c4c5a942e608c81082433940b530bfd6a7b2.

**Comment by void-mAlex** [comment]
if the above is not enough we can reopen
