### ISSUE TITLE
`{{component "link-to"}}` + staticComponents error

### ISSUE THREAD

**Issue by Windvis** [embroider-build/embroider#815]
While trying out Embroider (v0.40.0) and enabling the staticComponents compat flag, I noticed the following error:

`Missing component: link-to in node_modules/@appuniversum/ember-appuniversum/components/au-link.hbs`

Which points to this file: https://github.com/appuniversum/ember-appuniversum/blob/52566adf81dc1225bf2573eaa9a1aa5b2dd9b641/addon/components/au-link.hbs#L2

According to the [replacing the component helper docs](https://github.com/embroider-build/embroider/blob/master/REPLACING-COMPONENT-HELPER.md) this should work since it's a static string. From the Discord I understood that `link-to` is not _actually_ a component which is probably the reason for this error message.

I know there are workarounds to get it to work, but I just wanted to know if using `link-to` with the component helper like that _is supposed to_ work under Embroider and that this should be considered a bug.

Relevant discord discussion: https://discord.com/channels/480462759797063690/568935504288940056/841617811105120276

**Comment by ef4** [comment]
Thanks for reporting, this is a legitimate bug as long as it works in classic and doesn't work in embroider.
