### ISSUE TITLE
`@types/loader-utils` results in type issues

### ISSUE THREAD

**Issue by mydea** [embroider-build/embroider#819]
When trying to set this up for our typescript app, using latest versions of embroider, I get this error:

```
node_modules/@types/loader-utils/index.d.ts:12:10 - error TS2305: Module '"webpack"' has no exported member 'loader'.

12 import { loader } from 'webpack';
```

Which I guess is related to this:
https://github.com/webpack/loader-utils/issues/179

Is it possible to drop `@types/loader-utils`?

**Comment by nightire** [comment]
Seeing this error after upgrade `embroider@0.42` with `ember-cli-typescript@4.2.0`:

![image](https://user-images.githubusercontent.com/1104018/122304176-5f108080-cf37-11eb-8e3a-00ba83920bf8.png)

**Comment by NullVoxPopuli** [comment]
this is the work-around I use: https://github.com/NullVoxPopuli/limber/blob/main/package.json#L24

in package.json#scripts: `"postinstall": "rm -rf node_modules/@types/loader-utils"`

**Comment by NullVoxPopuli** [comment]
Confirmed fixed in: https://github.com/NullVoxPopuli/limber/pull/219
