### ISSUE TITLE
Scenario-tester ergonomic issue

### ISSUE THREAD

**Issue by stefanpenner** [embroider-build/embroider#867]
I like the new scenario-tester tool, unfortunately when debugging the associated tests it can be a little tricky to figure out two things:

1) What command to run, to create the specific scenarios source-files
2) what command to run to replicate the execution failure in the (1)'s source-files

This adds extra development friction, where previously there was none.

For example:
When running:
```sh
yarn test --filter release-static-app
```

the output we see is:
```sh
yarn run v1.22.5
$ qunit --require ts-node/register *-test.ts --filter release-static-app
TAP version 13
not ok 1 release-static-app > yarn test: production
  ---
  message: |
    $ npm-run-all lint test:*
    $ npm-run-all --aggregate-output --continue-on-error --parallel "lint:!(fix)"
    $ ember-template-lint .
    $ eslint . --cache
    $ ember test
    WARNING: [DEPRECATION] [DEPRECATION] Usage of the Ember Global is deprecated. You should import the Ember module or the specific API instead.
<snip ...../>
```

Now it is possible to carefully place debuggers in the tests, and in the test support tooling to figure out (1) and (2), but it would be quite nice to infer this a little quicker. As it would simplify active maintainers workflows, and also be more welcoming to drive-by contributions.

---
To discover (1) today,  one needs to know how to translate:

```sh
$ qunit --require ts-node/register *-test.ts --filter release-static-app
```

into:

```sh
yarn scenario-tester output --require ts-node/register --scenario release --files static-app-test.ts
```

AND

to discovery (2) I believe someone still needs to do a much deeper dive.
(edit: I will often put a debugger here: https://github.com/ef4/scenario-tester/blob/main/index.ts#L168, cd into the intended dir, and run the command myself in-order to debug)

---

I believe a good solution would result in test failures becoming obvious to re-run from the test output for users comfortable with the project, ideally without a contributors.md addition. For folks less familiar, a contributors.md addition may be appropriate.

---

One idea would be test output that contained something like  the following prior to the failure:

```sh
not ok <scenario name>

yarn scenario-tester release-static-app --output=./output
./output/ > ember s

<failure>
```

**Comment by stefanpenner** [comment]
One additional idea:

The scenario-tester output directory's node_module currently does not link the executables expected in `./node_module/.bin/`  if it is practical to do so then running `yarn ember` etc would "just work", removing a little more friction.

Today one needs to know to run:

` ../node_modules/.bin/ember`

**Comment by stefanpenner** [comment]
One additional note:

Some of these tests take a bit, a spinner hinting at what is going on might help. I suspect in most cases the printing the `command` from `app.execute(command)` would be sufficient at hinting.

**Comment by ef4** [comment]
We do have scripts in package.json that are supposed to help with listing and outputting scenarios:

```sh
cd tests/scenarios
yarn test:list # to discover $THE_NAME of the scenario you want
yarn test:output --scenario $THE_NAME
```

This gives you a complete app sitting in `output` ready to be run, tested, or debugged in the normal way, with the exception of the problem you pointed out:

> The scenario-tester output directory's node_module currently does not link the executables

**Comment by stefanpenner** [comment]
for symmetry  `yarn test --filter release-engines`  may be bettered suited as `yarn test --scenario release-engines`

**Comment by ef4** [comment]
Yeah, with the current setup its tricky. scenario-tester doesn't have any opinion about what test framework you're using.  

`yarn test --filter` is invoking qunit with a qunit-specific argument.

`yarn test:output --scenario` is invoking scenario-tester's CLI directly.

We can't rename `--filter` in qunit. We could rename `--scenario` to `--filter`, but it really wouldn't make sense because unlike the qunit case you're not filtering a list and getting potentially many matches, you're selecting a single scenario to output.

**Comment by void-mAlex** [comment]
we now have this documented somewhat over here https://github.com/embroider-build/embroider/blob/main/CONTRIBUTING.md#working-with-tests-scenarios
having tweaked a couple of scenarios myself have found that amount of info sufficient to get on with the tests, but if there are further ideas to refine QoL happy to reopen/revisit
