### ISSUE TITLE
$TMPDIR/embroider/externals discussion

### ISSUE THREAD

**Issue by stefanpenner** [embroider-build/embroider#871]
Today, different versions of embroider share `$TMPDIR/embroider/externals` should we version this, or embed this within `$TMPDIR/embroider/<app-hash>` to prevent future upgrade hazards?

**Comment by ef4** [comment]
If we change the contents in the future, we can pick a new path to put them in.

**Comment by stefanpenner** [comment]
@ef4 yup that works.
