### ISSUE TITLE
Bug: No TypeScript support (without ember-cli-typescript)

### ISSUE THREAD

**Issue by NullVoxPopuli** [embroider-build/embroider#889]
My situation:
 - ember 3.27
 - embroider 0.42.x
 - no ember-cli-typescript

The closest issue I found was this closed one: https://github.com/embroider-build/embroider/issues/691

What I'm observing:
 When I make the app, router, or test-helper files TS, embroider can no longer locate them (ModuleNotFound errors).

With my tests files in TS, they are not detected at all, and my embroider part of CI passes with only having run the Ember.onerror check and nothing else.

Using ember-cli-typescript in this case is not an option, because: https://github.com/typed-ember/ember-cli-typescript/issues/1439
But, on work projects we also don't use ember-cli-typescript, because we use composite TS projects, and I experienced the same behavior in an app. So, this TS support issue is not isolated to just add-ons.

**Comment by ef4** [comment]
You don't explain here how you're setting up typescript. If you're using a standalone typescript compiler, that should work fine because everything would be JS before embroider does anything.

If you're configuring typescript support directly in webpack, then yes, probably `@embroider/compat` doesn't know to keep typescript files around as its rewriting everything to get it ready for webpack. See https://github.com/embroider-build/embroider/blob/81ca52f837bd6ff9e80bc3ac406677f05da524a4/packages/compat/src/compat-app.ts#L240

Can you try patching that place so it always unshifts `.ts` and see if that fixes your problem?

Also, you can probably workaround by creating an in-repo-addon that does nothing but is named `ember-cli-typescript`.

**Comment by NullVoxPopuli** [comment]
> You don't explain here how you're setting up typescript.

I thought the ember-cli-babel config would have been sufficient. If not, then I guess these problems make sense.

I'll try your suggestions soon

**Comment by NullVoxPopuli** [comment]
- adding an in-repo-addon to my addon called `ember-cli-typescript`
  - detects TS files
  - but maybe doesn't transpile them? 
```
    $TMPDIR/embroider/80e0e8/tests/dummy/tests/helpers/await.ts/await.ts: Unexpected reserved word 'interface'. (7:0)

   5 | import { hbs } from 'ember-cli-htmlbars';
   6 |
>  7 | interface Args {
     | ^
```
  https://github.com/NullVoxPopuli/ember-repl/pull/27/checks?check_run_id=2990856820#step:5:385
  
  
  - always unshifting `.ts` in compat-app:
     - same as above
     
For clarification, the way I've set up Typescript transpilation via ember-cli-babel is the following:
 - addon's `./index.js`
   ```js
     options: {
      'ember-cli-babel': {
        enableTypeScriptTransform: true,
      },
   ```
 - dummy app's `./ember-cli-build.js`
     ```js
     let app = new EmberAddon(defaults, {
      'ember-cli-babel': {
        enableTypeScriptTransform: true,
      },
    });
    ```

**Comment by ef4** [comment]
Using the fake in-repo ember-cli-typescript strategy, you'd need to make sure it's a dependency of both your addon and your dummy app. The error you showed is the dummy app failing to transpile, not the addon.

Using the "always unshift .ts" strategy, I remembered there's a second place you'd need to patch:

https://github.com/embroider-build/embroider/blob/81ca52f837bd6ff9e80bc3ac406677f05da524a4/packages/compat/src/v1-addon.ts#L248

You can patch in a `this.name === 'my-addon'` condition to check there.

**Comment by NullVoxPopuli** [comment]
Ah ok, so,
 - adding my fake ember-cli-typescript to my addon's dependencies made the tests correctly transpile, run, and pass 🎉 
 - using additional patched location, I'm still seeing the same behavior, which I don't quite get, because searching the `@embroider` directory in my `node_modules` only shows the two places you've linked
 
![image](https://user-images.githubusercontent.com/199018/124488410-ce7ed080-dd7d-11eb-83ba-066282990e33.png)

**Comment by ef4** [comment]
Maybe you needed another `tsc` in embroider to make your patch really run?

**Comment by NullVoxPopuli** [comment]
another tsc? how do you mean? I haven't been using tsc for anything other than type checking?

**Comment by ef4** [comment]
I mean if you're patching embroider's typescript, you need to recompile it.

**Comment by NullVoxPopuli** [comment]
ah, gotchya -- I was editing node_modules (js) directly

**Comment by NullVoxPopuli** [comment]
In this commit: https://github.com/embroider-build/embroider/pull/895/commits/8cbae5e9a64ddafa41630edaed5367f6517ac312
the build fails (`yarn test:ember`), with the same interface issue as in my real addon

**Comment by NullVoxPopuli** [comment]
here is a lil stand-alone repro: https://github.com/NullVoxPopuli/ember-demo-typescript-without-ec-ts

**Comment by NullVoxPopuli** [comment]
oo, I think I have a fix -- and it's totalyl the same thing we talked about a year ago -- so now I don't know what I was doing wrong back then :upside_down_face:
