### ISSUE TITLE
RegExp are incorrectly parsed/evaluated when using `getOwnConfig` from `@embroider/macros` 

### ISSUE THREAD

**Issue by GabrielCousin** [embroider-build/embroider#898]
Hello!

I'm taking the liberty to open an issue and try to get some feedback on something I'm struggling with. We are using the official [Ember add-on for Sentry](https://github.com/getsentry/sentry-javascript/tree/master/packages/ember) which is using `embroider/macros` under the hood.

Its documentation is telling to pass options as shown in the below example:
```
// environment.js
const ENV = {
  // ...
    '@sentry/ember': {
      sentry: {
        autoSessionTracking: false,
        ignoreErrors: [
          'ResizeObserver loop limit exceeded',
        ],
        denyUrls: [
          /:\/\/*subwayblaze.com/,
          /extensions\//i,
          /^chrome:\/\//i,
          /^(chrome|safari)-extension:\/\//i,
        ],
      }
   };
   ```

and are "registered" the Embroider way here https://github.com/getsentry/sentry-javascript/blob/master/packages/ember/index.js#L21

However, when getting own config with `getOwnConfig`, the output is the following - RegExps are replaced with empty objects.
```
{
  autoSessionTracking: false,
  ignoreErrors: [
    'ResizeObserver loop limit exceeded',
  ],
  denyUrls: [{}, {}, {}, {}]
}
```

My two cent is that it's more a Babel issue but I would appreciate your feedback on this.
Let me know if I can help in any way,

Thank you!

**Comment by ef4** [comment]
I think this should be changed in `@ember/sentry`. `setOwnConfig` only supports json-serializable things, so if they see RegExp they should convert to a string before passing to `setOwnConfig`, and then convert back to RegExp at runtime.

**Comment by GabrielCousin** [comment]
Thanks a lot for the answer!
