### ISSUE TITLE
CI Failing

### ISSUE THREAD

**Issue by stefanpenner** [embroider-build/embroider#901]
Currently CI is failing, I am investigating and will hopefully resolve. Currently the issue appears to be that ember canary has removed a deprecated module and our `@ember/test-helpers` via `ember-qunit` is out-of-date. 

My currently plan is to update `ember-qunit` to address...

**Comment by stefanpenner** [comment]
https://github.com/embroider-build/embroider/pull/903

**Comment by ef4** [comment]
Fixed in #911.
