### ISSUE TITLE
Can't find stylesheet to import

### ISSUE THREAD

**Issue by LowBP** [embroider-build/embroider#916]
Getting stylesheet import error when i run my addons with embroider-safe mode

```
Sass Syntax Error (SassCompiler) in /var/folders/cg/812tw80x5j381_pz5vnwvcyh0000gp/T/addon/_reset.scss:1:9
Error: Can't find stylesheet to import.
  ╷
1 │ @import "./_private/common/variables.scss";
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  /var/folders/cg/812tw80x5j381_pz5vnwvcyh0000gp/T/addon/_reset.scss 1:9                                     @import
  /var/folders/cg/812tw80x5j381_pz5vnwvcyh0000gp/T/broccoli-41934QkCQW8qbBFLO/out-026-funnel/addon.scss 3:9  root stylesheet
  
  ```
  
  I am trying  to import  style files from  `addon`, `addon/components/` and `addon/components/button/_button.scss`  to  `addon/styles/addon.scss`
  
  ```
  "ember-cli-sass": "^10.0.1",
  "sass": "^1.23.7",
  "ember-source": "~3.27.5",
   ```

**Comment by ef4** [comment]
If you want scss support, you'll need to configure that yourself by passing additional webpack config. The built-in config only includes CSS.

**Comment by void-mAlex** [comment]
closing as duplicate in favor of #1033 
a workaround was also provided
