### ISSUE TITLE
How to replace `treeForPublic`

### ISSUE THREAD

**Issue by mydea** [embroider-build/embroider#931]
Thinking about a (near?) future where the `treeForXXX` hooks are not available anymore, I was trying to rebuild a tiny in-repo addon in our app that looks like this:

```js
let writeFile = require('broccoli-file-creator');

module.exports = {
  name: 'version-file',

  included() {
    let env = process.env.EMBER_ENV;
    let config = this.project.config(env);

    this._version = config.version;
    this._super.included.apply(this, arguments);
  },

  treeForPublic() {
    let version = this._version;
    let json = { version };

    return writeFile('version.json', JSON.stringify(json));
  },
};
```

What I want to achieve is have a file `version.json` that contains `{ version: '1.0.0' }`, to be consumed by external services - so I can't do this in JS-land, but it has to be a valid JSON file. 

Here: https://github.com/embroider-build/embroider/blob/master/SPEC.md#package-hooks it says that the `treeForXXX` hooks should be replaced with build time conditionals, which generally makes sense to me, but I struggle to see how that would work for `treeForPublic`, when I do not want to generate any JS files. 

Is there any recommendation on how to handle things like this? I guess it could be re-written to use `postBuild` and manually `fs.writeFileSync` the file into the dist folder, but not sure if that would be a good solution here?

**Comment by ef4** [comment]
Apps still have full control over putting things into their own public tree. Look for "passing optional extra broccoli trees" in the main embroider readme. If a v2 addon wants to offer that kind of functionality, it needs to do so by providing a function to the app author that the app author will invoke and pass as an extra broccoli tree.

Alternatively, apps can use existing tooling that goes with their packager of choice. For example, with webpack you can use CopyWebpackPlugin's `transform` option to write arbitrary data into a json file.

**Comment by mydea** [comment]
Thanks for the insights! I think passing extra broccoli trees manually is probably the way to go for me then - I'll look into it!
