### ISSUE TITLE
Component templates missing from compat build output

### ISSUE THREAD

**Issue by vlascik** [embroider-build/embroider#956]
Trying embroider on a fairly small app in compat mode, but while the build seems to complete fine, during boot the templates for several components are missing from the build output chunks. 

Components are co-located, very simple (just a text) and it doesn't matter whether they are Ember classic, Glimmer or template only components, the HBS/json parts of components are missing and nothing renders, while the original TS/JS , and even autogenerated JS for a template only component, is present.

Apart from this:
```
| building... [@embroider/webpack]The exported identifier "Error" is not declared in Babel's scope tracker
as a JavaScript value binding, and "@babel/plugin-transform-typescript"
never encountered it as a TypeScript type declaration.
It will be treated as a JavaScript value.

This problem is likely caused by another plugin injecting
"Error" without registering it in the scope tracker. If you are the author
 of that plugin, please use "scope.registerDeclaration(declarationPath)".
```

there is no error message in console in DEBUG=* (- couple of exceptions to prevent the flood) mode.

This message seems to be coming from babel plugins/AST transforms, but even after removing all addons that add these transforms, except from embroider/macros, the result is the same. Current AST transform list:
```
  ember-cli:registry loading htmlbars-ast-plugin: available plugins [
  '@embroider/macros/0',
  '@embroider/macros/1',
  'bind',
  'ember-maybe-in-element-transform'
]; found plugins [
  '@embroider/macros/0',
  '@embroider/macros/1',
  'bind',
  'ember-maybe-in-element-transform'
]; +8ms
```

I have no idea how to debug this anymore. Any ideas what could cause this, or what to look for in a debugger?

Everything latest (3.28) as of today, Windows.

**Comment by ef4** [comment]
What is your actual runtime error?

Are you passing any options to `compatBuild` in ember-cli-build.js?

**Comment by vlascik** [comment]
Most of the time there is no runtime error even, sometimes it crashes with a typical Error while rendering < component tree > / < my component >. `application.hbs` content is rendered, but the place where `<MyComponent/>` would be inserted, is empty. As I mentioned, the usual module with compiled handlebars JSON is missing from the output chunk, so it's not found by the resolver either.

compatBuild options are empty: `return require('@embroider/compat').compatBuild(app, Webpack, {});`

**Comment by bendemboski** [comment]
I am seeing that warning as well in my app, although I have no problems at runtime, just the warning. I do not co-locate my templates.

**Comment by vlascik** [comment]
Don't think this is still happening, so I'm going to close the issue.
