### ISSUE TITLE
Colocated components within folders do not render

### ISSUE THREAD

**Issue by esbanarango** [embroider-build/embroider#987]
I'm trying out Embroider `"0.44.2"` with an App with *colocated components*. So we have them as:

```
app
 - components
   - componentA
     - template.hbs
     - component.js
   - componentB
     - template.hbs
     - component.js
```

`componentA` and `componentB` do not render at all nor throw any error. But if I change the structure to:

```
app
 - components
   - componentA.hbs
   - componentA.js
   - componentB.hbs
   - componentB.js
```

That "fixes" it. I don't want to migrate them all as we have a ton, plus, having them encapsulated in a single folder per name is more manageable. 

I already tried disabling `staticComponents`. But no look... am I missing something?

Thank you :pray:

**Comment by NullVoxPopuli** [comment]
your first example isn't co-located components. Those are "pods". If you mass-rename component.js to index.js and template.hbs to index.hbs, things should start working again.

there is also a .ember-cli option to enable "nested" structure by default, if that suits you.

Here is an example of an embroider app using a mix of flat and nested component structure: https://github.com/NullVoxPopuli/limber/tree/main/frontend/app/components/limber/menu

**Comment by dcyriller** [comment]
Nice catch @lifeart! Unfortunately it doesn't seem to fix the issue ([the tests are still failing](https://github.com/dcyriller/__embroider-pods/pull/1/checks?check_run_id=3925781606)).

**Comment by dcyriller** [comment]
Thanks for the pointer @lifeart, I have submitted a possible fix to support pods components when `podModulePrefix === ''`.

As two of you mentionned, it might be the good opportunity for our team to move from a pods-based component structure to the colocated. There is a codemod to migrate to the colocated components and it could modified to support the [pods components](https://github.com/ember-codemods/ember-component-template-colocation-migrator/issues/4). But it would mean migrating many components in multiple applications shared between many developpers... We will probably end up migrating to colocated components. But if we ran into the issue, it might be a blocker for other teams? Also, this layout is still documented in [ember-cli official documentation](https://cli.emberjs.com/release/advanced-use/project-layouts/#podslayout). This is my reasoning to submit the fix :)

**Comment by acorncom** [comment]
Looks like this can be closed, as #1007 was merged

**Comment by rahulk94** [comment]
I'd suggest renaming this issue to say pods instead of co-located components to avoid confusion for people looking for issues.

**Comment by ef4** [comment]
I'm assuming this was covered by #1007.

**Comment by ijlee2** [comment]
For those who land on this issue, I wrote a [codemod to un-pod Ember projects](https://github.com/ijlee2/ember-codemod-pod-to-octane). Feel free to give it a try.
